### ISSUE TITLE
能否提供一个移除国际化的命令

### ISSUE THREAD

**Issue by wehuss** [arco-design/arco-design-pro-vue#10]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What problem does this feature solve?
就像Ant Design Pro那样:
![image](https://user-images.githubusercontent.com/48681136/150281274-92d25591-e270-4806-858c-09d621c0bb87.png)

**Comment by sHow8e** [comment]
目前没有移除i18n脚本相关的规划。这个建议先收集着啦，后续会对用户诉求提供一些定制化的命令。可以期待一下哈~

**Comment by lvreninfo** [comment]
## 去除国际化
_Fix Version：_arco-design-pro-vue  => 2.5.11 （简版）

_Ps：_$t()、t() 请结合 src/locale/zh-CN.ts 和 src/locale/zh-CN/settings.ts 进行手动替换

├── package.json #去掉 vue-i18n

├── src
  │   ├── components
  │          ├── breadcrumb
  │                    └── index.vue  #去掉 $t()
  │          ├── global-setting
  │                    └── block.vue  #去掉 $t()
  │                    └── index.vue  #去掉 $t()、useI18n()、t()
  │          ├── menu
  │                    └── index.vue  #去掉 useI18n()、t()
  │          ├── message-box
  │                    └── locale  #去掉（以下2个文件需要结合当前进行手动替换）
  │                    └── index.vue  #去掉 $t()、useI18n()、t()
  │                    └── list.vue  #去掉 $t()
  │          ├── navbar
  │                    └── index.vue  #去掉 $t()、LOCALE_OPTIONS、locales、useLocale()、changeLocale()
  │          ├── tab-bar
  │                    └── tab-item.vue  #去掉 $t()

  │   ├── hooks
  │          └── locale.ts  # 去掉

  │   ├── locale  # 去掉

  │   ├── views
  │          ├── folder*
  │                    └── locale*  #去掉
  │                    └── file*.ts  #去掉 useI18n()、t()
  │                    └── file*.vue  #去掉 useI18n()、t()、$t()

  │   ├── router
  │          ├── externalModules
  │                    └── arco.ts  # menu.arcoWebsite 替换 'Arco Design'
  │                    └── faq.ts  # menu.faq 替换 '常见问题'
  │          ├── modules
  │                    └── dashboard.ts  #替换menu.*
  │          └── locale.ts  # menu.dashboard.workplace 替换 '工作台'

  │   └── App.vue  # 去掉locale、useLocale()、zhCN、enUS

  │   └── main.ts  # 去掉i18n()

└── tsconfig.json
