### ISSUE TITLE
左侧菜单栏在发布后适配显示不正常

### ISSUE THREAD

**Issue by ktangel** [arco-design/arco-design-pro-vue#100]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.1
- **Browser:** chrome101.0.4951.64

## Extra info
使用官网的模板，下载后直接preview和build,然后我用fiddler模拟api/user/login api/user/info接口数据 登陆成功后同样出现上面的问题，已经把setting.json的menuFromServer设置为了false。

## What is expected?
但是当使用preview或者build发布后，按上面的步骤缩小窗口后，点击菜单按钮，弹出的菜单栏上面菜单空的，没有正常渲染出来，并且会有报错，然后窗口拉大回来正常

```
arco.db53d955.js:4 
        
       TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '_' -> object with constructor 'Object'
    |     property 'vnode' -> object with constructor 'Object'
    |     ...
    |     property 'ref' -> object with constructor 'tS'
    --- property '_rawValue' closes the circle
    at JSON.stringify (<anonymous>)
    at Tr.fn (default-layout.0c32ddd6.js:formatted:110:39)
    at Tr.run (arco.db53d955.js:1:6297)
    at rS.get value [as value] (arco.db53d955.js:1:14720)
    at h (default-layout.0c32ddd6.js:formatted:213:24)
    at Proxy.<anonymous> (default-layout.0c32ddd6.js:formatted:228:23)
    at ds (arco.db53d955.js:4:4341)
    at Tr.we [as fn] (arco.db53d955.js:4:35125)
    at Tr.run (arco.db53d955.js:1:6297)
    at N (arco.db53d955.js:4:35412)
```

通过排查，发现是在 `src/components/menu/useMenuTree.ts`的第18行，menuTree 计算时，使用了JSON.stringify抛出的错误。
```
  const menuTree = computed(() => {
    const copyRouter = JSON.parse(JSON.stringify(appRoute.value));
    
```

开发环境正常，为何到了发布打包后这里会报错呢。

## Steps to reproduce
开发时正常，登陆进去，菜单显示在拉小屏幕后，菜单会隐藏并出现一个菜单按钮在左上方，点击按钮会弹出抽屉菜单，这个是适合小屏幕的菜单显示。

**Comment by sHow8e** [comment]
@ktangel 这边由于getrouter会产生一些循环依赖问题。可以根据[v2.5.1](https://github.com/arco-design/arco-design-pro-vue/blob/eaef75cff8fca239d16c4f1e9eb78712017e498c/arco-design-pro-vite/src/components/menu/useMenuTree.ts#L17)做一层map。
