### ISSUE TITLE
使用pnpm安装依赖后，运行提示引入错误

### ISSUE THREAD

**Issue by dyggod** [arco-design/arco-design-pro-vue#104]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.5.2
- **框架版本:** 3.2.31
- **浏览器版本:** chrome102.0.5005.61

## 额外补充
issue #52  最后给出了一种解决方式为引入`@arco-design/web-vue/es/upload/interfaces.d`文件，但这并不常规

## 预期结果
预期：正常运行，打开3000端口看到登录页
实际：
   命令行提示：The following dependencies are imported but could not be resolved:

  @arco-design/web-vue/es/upload/interfaces (imported by D:/github/growser/src/views/user/setting/components/user-panel.vue?id=0)
![image](https://user-images.githubusercontent.com/49914353/171544531-0ec00030-7156-4e33-882f-f2e2a9314d1d.png)

Are they installed?

## 复现步骤
1. 使用arco-cli生成项目, `acro init my-project`
2. 进入项目，`cd my-project`
3. 删除原有node_modules目录
4. 使用pnpm管理依赖，`pnpm install`
5. 运行程序，`pnpm run dev`

**Comment by sHow8e** [comment]
@dyggod hihi 可以把 'import' 改成 'import type'试试看。

**Comment by dyggod** [comment]
> @dyggod hihi 可以把 'import' 改成 'import type'试试看。
感谢回复，将`import`修改为`import type`确实可行。不过此处是否应在源码中修复？

**Comment by sHow8e** [comment]
> > @dyggod hihi 可以把 'import' 改成 'import type'试试看。
> > 感谢回复，将`import`修改为`import type`确实可行。不过此处是否应在源码中修复？

是的。下个版本我修改一下。如果有兴趣也可以提交pr参与哈。

**Comment by hehehai** [comment]
@sHow8e 建议设置下 eslint 的规则 
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md

**Comment by sHow8e** [comment]
> @sHow8e 建议设置下 eslint 的规则 https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md

从提示信息来看，不像eslint的问题。应该是某个ts相关的模块解析的提示。规范一下写法比较好。

**Comment by sHow8e** [comment]
done [v2.5.3](https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.5.3)
