### ISSUE TITLE
只有一级菜单的路由该如何配置。使用hideChildrenInMenu后，内页是空白的

### ISSUE THREAD

**Issue by Yuxiaogang-Gavin** [arco-design/arco-design-pro-vue#106]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.2
- **Browser:** chrome86.0.4240.198

## Extra info

这样配置虽然能出来内页，但是点击菜单，还是会跳回空白页。
export default {
  path: '/home',
  name: '门户首页',
  component: DEFAULT_LAYOUT,
  meta: {
    locale: 'menu.home',
    requiresAuth: true,
    icon: 'icon-dashboard',
    order: 0,
    hideChildrenInMenu:true
  },
  children: [
    {
      path: '',
      name: '门户首页',
      component: () => import('@/views/dashboard/workplace/index.vue'),
      meta: {
        locale: 'menu.dashboard.workplace',
        requiresAuth: true,
        roles: ['*'],
        hideInMenu:true,
      },
    },
  ],
};

**Comment by sqlFC** [comment]
@Yuxiaogang-Gavin 例如下图这样就可以
![image](https://user-images.githubusercontent.com/29202691/171588058-080623a5-ec61-4c59-bc06-bdfe297e56a2.png)
