### ISSUE TITLE
webstrom报告input-password组件prefix插槽无法识别

### ISSUE THREAD

**Issue by SouthWan** [arco-design/arco-design-pro-vue#107]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.5.2
- **框架版本:** vue
- **浏览器版本:** chrome98.0.4758.81

**Comment by sHow8e** [comment]
这个应该是WebStorm的问题，安装相关插件。推荐使用vscode + volar
