### ISSUE TITLE
路由中 hideInMenu 和 activeMenu 的关系

### ISSUE THREAD

**Issue by pzgz** [arco-design/arco-design-pro-vue#108]
在 https://github.com/arco-design/arco-design-pro-vue/blob/78f0d7c97e46655e5f99f1dcea97b6f2bdee83c9/arco-design-pro-vite/src/components/menu/index.vue#L41 这里，如果一个当前route的`hideInMenu`设置为`true`，即使`activeMenu`也被设置为`true`，如果用户通过浏览器刷新了当前页面而不是从其他路由进入的话，会导致左侧菜单栏中不会高亮显示对应的 `activeMenu`。

感觉这个逻辑是有问题的，既然指定了 `activeMenu`，当然也是可以 `hideInMenu`的，这种情况还是可能出现的，主要是两个路由不希望放在同一个route的`children`下时，指定 `activeMenu`，很可能也就是希望这个路由本身不出现在菜单中。

所以这里建议把这个判断改成

`newRoute.meta.requiresAuth && (!newRoute.meta.hideInMenu || newRoute.meta.activeMenu)`

缺点是，隐藏的和活动的最好放在同一级，这样才能保证打开的上级菜单也是正确的

**Comment by sHow8e** [comment]
@pzgz hihi。[activeMenu](https://github.com/arco-design/arco-design-pro-vue/blob/78f0d7c97e46655e5f99f1dcea97b6f2bdee83c9/arco-design-pro-vite/src/router/typings.d.ts#L11)类型是字符串。相关的字段说明也涵盖在其中。'hideInMenu'后续补充上。

**Comment by pzgz** [comment]
> @pzgz hihi。[activeMenu](https://github.com/arco-design/arco-design-pro-vue/blob/78f0d7c97e46655e5f99f1dcea97b6f2bdee83c9/arco-design-pro-vite/src/router/typings.d.ts#L11)类型是字符串。相关的字段说明也涵盖在其中。

@sHow8e 

不好意思，我的描述有问题，`activeMenu`是字符串，我的意思是，如果当前页面是`hideInMenu`并且设置了`activeMenu`的情况下，这时候，在上面语句所在的路由监听方法捕捉到后，虽然通过`activeMenu`可以找到需要高亮的菜单条目，但因为上面语句内的判断中只针对`hideInMenu`，所以后续的处理也不会进行。

造成的现象就是，如果用户点击进去了某个设置了`hideInMenu`和`activeMenu`的路由进去，看上去是正常的，但如果用户在这个页面用浏览器的刷新，这时候菜单是不会正常高亮的。

个人感觉既然设置了`activeMenu`，这个条件可以和`hideInMenu`来进行协调决定是否做当前高亮菜单的一个捕获。

**Comment by sHow8e** [comment]
@pzgz 我通过你的描述知晓了问题所在哈。我会进行修复一下。3q

**Comment by sHow8e** [comment]
done [v2.5.3](https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.5.3)
