### ISSUE TITLE
我认为 arco pro vue 在语法 和 功能 上都有很多地方可以去完善

### ISSUE THREAD

**Issue by BaiGuangTeng** [arco-design/arco-design-pro-vue#11]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
script setup 可以发挥 Composition Api 和 Vue3 的完整优势
vue-element-admin 算得上是企业级的后台模板

## What problem does this feature solve?
1. 语法上, script setup sugar 是 future
2. 贵公司员工的 vue-element-admin 在业务功能上或许值得参考和借鉴

**Comment by sHow8e** [comment]
感谢建议。1、setup语法糖的写法有过尝试，彼时插件不完善以及遍地飘红的代码提示对于书写代码影响较大。如果喜欢可以暂时自行使用哈。2、vue-element-admin 是一款非常优秀的产品。目前pro很多功能需要时间完善很多功能并不是一蹴而就。同时有多架构上的考虑。并不是对vue-element-admin进行简单的参考或者借鉴就能尽善尽美。 这是一个开源项目，当然还是希望大家能够和我们一起参与到arco生态建设中。3q。
