### ISSUE TITLE
query传参数到同一页面会导致页面刷新

### ISSUE THREAD

**Issue by thislyc** [arco-design/arco-design-pro-vue#112]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.2
- **Browser:** chrome92.0.4515.107

## What is expected?
和vue-router默认的方式一样 页面不重新渲染

## Steps to reproduce
/dashboard/workplace?1=1
改为/dashboard/workplace?1=2
页面会重新渲染

**Comment by thislyc** [comment]
https://github.com/arco-design/arco-design-pro-vue/blob/cdc4a27e2dce0383ab9c5c36f8b91bfd37d3078e/arco-design-pro-vite/src/layout/page-layout.vue#L10
这里为什么要用fullpath来判断呢

**Comment by sHow8e** [comment]
> https://github.com/arco-design/arco-design-pro-vue/blob/cdc4a27e2dce0383ab9c5c36f8b91bfd37d3078e/arco-design-pro-vite/src/layout/page-layout.vue#L10
> 
> 
> 这里为什么要用fullpath来判断呢

@thislyc hihi 因为使用fullpath做了页面缓存，所以即便是同一个页面，fullpath不同会重新进行渲染。如果不需要可以关闭缓存，ignoreCache，或者key使用别的值。

**Comment by thislyc** [comment]
> > https://github.com/arco-design/arco-design-pro-vue/blob/cdc4a27e2dce0383ab9c5c36f8b91bfd37d3078e/arco-design-pro-vite/src/layout/page-layout.vue#L10
> > 
> > 这里为什么要用fullpath来判断呢
> 
> @thislyc hihi 因为使用fullpath做了页面缓存，所以即便是同一个页面，fullpath不同会重新进行渲染。如果不需要可以关闭缓存，ignoreCache，或者key使用别的值。

hi 这样会导致一个问题：如果同一个页面，我想要做部分参数放到链接中去，我只能用query传参，因为我希望这个链接是可以被分享的。如果我使用query传参数的话，fullpath会改变，导致重新渲染了当前页面，但是如果我们没有使用这种动态component的话，query传递参数是不会重新渲染页面的。 
我的理解是 应该使用route.path来判断 ，缓存的应该是单个页面组建，如果query传参数那就还是保持原来的页面，tab-bar也不应该再单独出现其他的不同的fullpath的tab， 包括https://github.com/arco-design/arco-design-pro-vue/blob/cdc4a27e2dce0383ab9c5c36f8b91bfd37d3078e/arco-design-pro-vite/src/components/tab-bar/index.vue#L11
这里的tab-bar中的判断应该也是如此，但是可能需要在tab-bar组件中修改一下push tagList的逻辑，在https://github.com/arco-design/arco-design-pro-vue/blob/cdc4a27e2dce0383ab9c5c36f8b91bfd37d3078e/arco-design-pro-vite/src/components/tab-bar/index.vue#L61 这里修改一下判断的逻辑，如果是新的路由中只是fullpath更新但是path一致 那其实也应该替换掉原有的缓存页面

如果您认同这一变化 我可以提一个pr，您也可以尝试一下在普通页面如果用query传参数会导致的情况

**Comment by yanbowe** [comment]
> > > https://github.com/arco-design/arco-design-pro-vue/blob/cdc4a27e2dce0383ab9c5c36f8b91bfd37d3078e/arco-design-pro-vite/src/layout/page-layout.vue#L10
> > > 
> > > 这里为什么要用fullpath来判断呢
> > 
> > 
> > @thislyc hihi 因为使用fullpath做了页面缓存，所以即便是同一个页面，fullpath不同会重新进行渲染。如果不需要可以关闭缓存，ignoreCache，或者key使用别的值。
> 
> hi 这样会导致一个问题：如果同一个页面，我想要做部分参数放到链接中去，我只能用query传参，因为我希望这个链接是可以被分享的。如果我使用query传参数的话，fullpath会改变，导致重新渲染了当前页面，但是如果我们没有使用这种动态component的话，query传递参数是不会重新渲染页面的。 我的理解是 应该使用route.path来判断 ，缓存的应该是单个页面组建，如果query传参数那就还是保持原来的页面，tab-bar也不应该再单独出现其他的不同的fullpath的tab， 包括
> 
> https://github.com/arco-design/arco-design-pro-vue/blob/cdc4a27e2dce0383ab9c5c36f8b91bfd37d3078e/arco-design-pro-vite/src/components/tab-bar/index.vue#L11
> 
> 
> 这里的tab-bar中的判断应该也是如此，但是可能需要在tab-bar组件中修改一下push tagList的逻辑，在
> https://github.com/arco-design/arco-design-pro-vue/blob/cdc4a27e2dce0383ab9c5c36f8b91bfd37d3078e/arco-design-pro-vite/src/components/tab-bar/index.vue#L61
> 
> 这里修改一下判断的逻辑，如果是新的路由中只是fullpath更新但是path一致 那其实也应该替换掉原有的缓存页面
> 如果您认同这一变化 我可以提一个pr，您也可以尝试一下在普通页面如果用query传参数会导致的情况

场景不同而已，对于我来说参数不同tab就是应该不一样的，相当于两个页面。

**Comment by sHow8e** [comment]
@thislyc 感谢建议。使用fullpath，页面缓存设计之初就是如此哈。然而path并不是一个通配式的方案，修改其对于项目而言有种倒行逆施的感觉。如果有需要可以自己在项目内进行修改哈。3q
