### ISSUE TITLE
Typography组件在谷歌翻译的情况下无法展开，且表格组件也会边框缺失

### ISSUE THREAD

**Issue by SouthWan** [arco-design/arco-design-pro-vue#113]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.5.2
- **框架版本:** vue
- **浏览器版本:** chrome98.0.4758.81

## 复现步骤
设置谷歌翻译为英文翻译中文

**Comment by sHow8e** [comment]
@SouthWan hihi 组件问题移步 [arco-design-vue](https://github.com/arco-design/arco-design-vue/issues)。3q
