### ISSUE TITLE
能否出一个关于不需要权限的教程

### ISSUE THREAD

**Issue by JieAnthony** [arco-design/arco-design-pro-vue#115]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
nothing

## What problem does this feature solve?
希望可以官方可以推出不需要权限的教程，比如删除哪些文件和代码

**Comment by sHow8e** [comment]
@JieAnthony hihi 可以查阅一下[文档](https://arco.design/vue/docs/pro/permission)。或者看一下内部代码哈。
