### ISSUE TITLE
可以增加多一种上下结构的布局吗

### ISSUE THREAD

**Issue by 981433814** [arco-design/arco-design-pro-vue#116]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
左右结构的布局，像是管理系统，希望能添加个菜单在上面的布局

## What problem does this feature solve?
左右结构的布局，像是管理系统，希望能添加个菜单在上面的布局

**Comment by sHow8e** [comment]
@981433814 hihi pro有自己的UI规范，上下布局目前并没有产出。可以自行调整哈。

**Comment by 981433814** [comment]
![image](https://user-images.githubusercontent.com/45874392/172759243-6a840fa6-67b7-4863-b460-9d90fa03a6ce.png)
可以做成可配置项吗~

**Comment by sHow8e** [comment]
@981433814 hihi 没有对应的UI规范，配置项也不抵用呀。后续我内部给UI小姐姐提一下哈。3q
