### ISSUE TITLE
menu From Server config don't work

### ISSUE THREAD

**Issue by ljnchn** [arco-design/arco-design-pro-vue#117]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.5.3
- **浏览器版本:** chrome102.0.5005.63

## 预期结果
after login the page is blank

## 复现步骤
change src/config/settings.json
"menuFromServer": true

**Comment by sHow8e** [comment]
@ljnchn hihi 我看了一下，功能不存在问题。麻烦具体描述一下。3q

**Comment by ljnchn** [comment]
> @ljnchn hihi 我看了一下，功能不存在问题。麻烦具体描述一下。3q

登录之后点击配置切换使用服务端菜单没问题，直接在配置里写上使用服务端菜单然后启动登录就不行，页面空白，中间就一个 back 的按钮。没有请求，本地存储的 app.serverMenu 是空的。

**Comment by sHow8e** [comment]
@ljnchn hihi 明白了你的意思。后续做个修复。3q

**Comment by dyggod** [comment]
我会修复这个问题。

**Comment by sHow8e** [comment]
done [v2.5.4](https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.5.4)
