### ISSUE TITLE
增加多页签功能

### ISSUE THREAD

**Issue by xiaochong44** [arco-design/arco-design-pro-vue#12]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
国内的ERP厂商如金蝶、用户、管家婆的bs版本都有多页签功能

## What problem does this feature solve?
多页签的模式对于做企业管理软件很受欢迎，特别是很多用户是从winform迁移过来的，多页签变的非常重要，希望增加多页签

**Comment by sHow8e** [comment]
get it~  目前这个功能需要UI提供契合页面的设计。同时还需要后期的开发。后续会进行推出哈。3q

**Comment by captree** [comment]
+1

**Comment by yanbowe** [comment]
> get it~ 目前这个功能需要UI提供契合页面的设计。同时还需要后期的开发。后续会进行推出哈。3q

不知道优先级如何，迫切需要这个功能

**Comment by sHow8e** [comment]
@yanbowe 目前这个优先级还只是提上议程，具体推出还是需要一段时间的哈。囧。有时间可以自己实现并且pr一下呀。

**Comment by captree** [comment]
> 

看下隔壁腾讯的td，已经在做了

**Comment by captree** [comment]
> > get it~ 目前这个功能需要UI提供契合页面的设计。同时还需要后期的开发。后续会进行推出哈。3q
> 
> 不知道优先级如何，迫切需要这个功能

看下隔壁腾讯的td，已经在做了

**Comment by aa824031637** [comment]
迫切需要+1

**Comment by sHow8e** [comment]
@aa824031637 已经向内部提了。需要一定的时间哈。

**Comment by taolei1990** [comment]
![image](https://user-images.githubusercontent.com/23173640/155934250-562f88ae-4bc1-4442-be62-d9055bfcdff6
迫切需要这个功能

**Comment by xinhaoxx** [comment]
我通过 keepAlive 和 pinia 实现了一版简单标签页，但是发现有个比较严重的问题，就是路由视图不能多层嵌套，如果多层嵌套会触发多次渲染。
查了一下发现这个问题是 vue 和 vue/router 导致的，目前为止还没有解决，具体可以看看这个 [issue](https://github.com/vuejs/router/issues/626)

**Comment by yanbowe** [comment]
@sHow8e hi，我看到更新日志里有多页签功能了，但是我没有找到在哪里
![0c78852346f8f9f672d592758832e83](https://user-images.githubusercontent.com/43030980/160311731-8a8af5c9-f264-4628-a682-e414352803c0.png)

**Comment by sHow8e** [comment]
@yanbowe 这个因为不是官方设计规范。所以我进行了隐藏。需要初始化项目，启动项目后点击右上角页面配置进行开启。如果是代码目录，详见component/tab-bar 以及 store的 modules/tab-bar

**Comment by yanbowe** [comment]
> @yanbowe 这个因为不是官方设计规范。所以我进行了隐藏。需要初始化项目，启动项目后点击右上角页面配置进行开启。如果是代码目录，详见component/tab-bar 以及 store的 modules/tab-bar

谢谢，看到了，这个功能计划什么时候正式上线呢

**Comment by sHow8e** [comment]
@yanbowe 这个目前已经正式上线了一版。明天会有一个修复版本发布。

**Comment by sHow8e** [comment]
目前新版本（v2.3.3）相关修复内容已经发布了。这个issue先关闭了哈

**Comment by xinhaoxx** [comment]
> > 我通过 keepAlive 和 pinia 实现了一版简单标签页，但是发现有个比较严重的问题，就是路由视图不能多层嵌套，如果多层嵌套会触发多次渲染。 查了一下发现这个问题是 vue 和 vue/router 导致的，目前为止还没有解决，具体可以看看这个 [issue](https://github.com/vuejs/router/issues/626)
> 
> 这个问题有解决的方法吗
把 router-view -> keep-alive 下的 component 的 key 设置为 undefined 即可，但治标不治本

`
  <router-view v-slot="{ Component }">
    <keep-alive :include="keepAliveRoute">
      <component :is="Component" :key="undefined" />
    </keep-alive>
  </router-view>
`

**Comment by Miofly** [comment]
> > > 我通过 keepAlive 和 pinia 实现了一版简单标签页，但是发现有个比较严重的问题，就是路由视图不能多层嵌套，如果多层嵌套会触发多次渲染。 查了一下发现这个问题是 vue 和 vue/router 导致的，目前为止还没有解决，具体可以看看这个 [issue](https://github.com/vuejs/router/issues/626)
> > 
> > 
> > 这个问题有解决的方法吗
> > 把 router-view -> keep-alive 下的 component 的 key 设置为 undefined 即可，但治标不治本
> 
> ```
>   <router-view v-slot="{ Component }">
>     <keep-alive :include="keepAliveRoute">
>       <component :is="Component" :key="undefined" />
>     </keep-alive>
>   </router-view>
> ```

这个能解决大多数情况setup的重复执行，但是在我有两个不同的 三级路由页面（二级路由也不是一个），当我打开一个三级路由页面，从三级路由切换到任意二级路由页面，setup不会重新触发，这里都是正常的。但是如果这时我再次开启系统中另一个三级路由页面，新的三级路由页面setup会触发两次，如下

<img width="921" alt="image" src="https://user-images.githubusercontent.com/42859910/211327653-d406ec77-309f-4c1d-926d-4428924fe857.png">

我再切换到之前打开的三级路由页面，发现setup又重新执行了
<img width="788" alt="image" src="https://user-images.githubusercontent.com/42859910/211327818-a5ed1d60-e418-49b6-b53f-36f33a55725a.png">

不知道你那边有没有这种情况

**Comment by xinhaoxx** [comment]
> > > > 我通过 keepAlive 和 pinia 实现了一版简单标签页，但是发现有个比较严重的问题，就是路由视图不能多层嵌套，如果多层嵌套会触发多次渲染。 查了一下发现这个问题是 vue 和 vue/router 导致的，目前为止还没有解决，具体可以看看这个 [issue](https://github.com/vuejs/router/issues/626)
> > > 
> > > 
> > > 这个问题有解决的方法吗
> > > 把 router-view -> keep-alive 下的 component 的 key 设置为 undefined 即可，但治标不治本
> > 
> > 
> > ```
> >   <router-view v-slot="{ Component }">
> >     <keep-alive :include="keepAliveRoute">
> >       <component :is="Component" :key="undefined" />
> >     </keep-alive>
> >   </router-view>
> > ```
> 
> 这个能解决大多数情况setup的重复执行，但是在我有两个不同的 三级路由页面（二级路由也不是一个），当我打开一个三级路由页面，从三级路由切换到任意二级路由页面，setup不会重新触发，这里都是正常的。但是如果这时我再次开启系统中另一个三级路由页面，新的三级路由页面setup会触发两次，如下
> 
> <img alt="image" width="921" src="https://user-images.githubusercontent.com/42859910/211327653-d406ec77-309f-4c1d-926d-4428924fe857.png">
> 
> 我再切换到之前打开的三级路由页面，发现setup又重新执行了 <img alt="image" width="788" src="https://user-images.githubusercontent.com/42859910/211327818-a5ed1d60-e418-49b6-b53f-36f33a55725a.png">
> 
> 不知道你那边有没有这种情况

我这边最深是三级菜单，好像没有重复挂载的问题，设置为 undefined 的方式对我有效
<img width="1070" alt="Snipaste_2023-01-09_22-21-03" src="https://user-images.githubusercontent.com/18677889/211329929-e944639b-7c31-4e5f-ac4e-9763da3a4006.png">

**Comment by Miofly** [comment]
@xinhaoxx 如果你还有一个和菜单管理一样的三级路由页面，这个页面和你现在这个菜单管理相互切换也不会重复执行吗

**Comment by xinhaoxx** [comment]
> @xinhaoxx 如果你还有一个和菜单管理一样的三级路由页面，这个页面和你现在这个菜单管理相互切换也不会重复执行吗

嗯，深层级页面切换不会重复执行，所以页面内我还需要写 onActivated 来判断路径 query/params 变化

**Comment by Miofly** [comment]
> > @xinhaoxx 如果你还有一个和菜单管理一样的三级路由页面，这个页面和你现在这个菜单管理相互切换也不会重复执行吗
> 
> 嗯，深层级页面切换不会重复执行，所以页面内我还需要写 onActivated 来判断路径 query/params 变化

我写了一个关于两个三级路由互相切换 setup 重复执行问题的最小 repo，大佬看看这种有办法可以解决吗，可以看控制台的打印
https://github.com/Miofly/vue-route-issue
