### ISSUE TITLE
Table在pro里sticky-header表头吸顶失效

### ISSUE THREAD

**Issue by cxiniao** [arco-design/arco-design-pro-vue#120]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.5.3
- **浏览器版本:** chrome102.0.0.0

## 预期结果
Table的表头正常吸顶

**Comment by sHow8e** [comment]
@cxiniao hihi。建议先把组件库升级到最新版。同时确保api使用正确。而后可以看看包裹table的父级元素有啥区别进行排查。

**Comment by cxiniao** [comment]
> @cxiniao hihi。建议先把组件库升级到最新版。同时确保api使用正确。而后可以看看包裹table的父级元素有啥区别进行排查。

版本分别是：arco 2.30.2，pro 2.5.2
Table 的 sticky-header 失效可能是因为pro模板里是 arco-layout-content 整个main滚动，导致失效。希望pro官方能进行适配。

**Comment by sHow8e** [comment]
@cxiniao hihi。感谢建议哈。然而sticky-header这个属性，本质上是使用sticky进行定位。对于样式问题，应该在自己的项目内对table的包裹容器做一下处理即可哈。3q

**Comment by cxiniao** [comment]
> @cxiniao hihi。感谢建议哈。然而sticky-header这个属性，本质上是使用sticky进行定位。对于样式问题，应该在自己的项目内对table的包裹容器做一下处理即可哈。3q
可以指点以下应该怎样处理吗？我前端小白 T T

**Comment by sHow8e** [comment]
@cxiniao 可以看一下文档，了解sticky的特性哈。[文档](https://developer.mozilla.org/zh-CN/docs/Web/CSS/position)
