### ISSUE TITLE
二级菜单跳转三级菜单，三级菜单页面不显示

### ISSUE THREAD

**Issue by BestLee1989** [arco-design/arco-design-pro-vue#123]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.3
- **Framework version:** vue: "^3.2.31"
- **Browser:** chrome95.0.4638.69

## Steps to reproduce
1、二级菜单下添加子菜单（三级菜单），2、二级菜单跳转到自己的子菜单，路由改变了，但是页面还是显示的二级菜单的页面

**Comment by sHow8e** [comment]
@BestLee1989 hihi 提供一下具体的配置代码哈。3q

**Comment by BestLee1989** [comment]
import { DEFAULT_LAYOUT } from '@/router/constans';

export default {
  path: '/',
  name: 'userManagement',
  component: DEFAULT_LAYOUT,
  meta: {
    locale: 'menu.userManagement',
    requiresAuth: true,
    icon: 'icon-user',
    order: 1,
  },
  children: [
    {
      path: '/userList',
      name: 'userList',
      component: () => import('@/views/userManagement/list.vue'),
      meta: {
        locale: 'menu.userList',
        requiresAuth: true,
        roles: ['*'],
      },
      children: [
        {
          path: '/userList/details',
          name: 'userDetails',
          component: () => import('@/views/userManagement/details.vue'),
          meta: {
            activeMenu: 'userList',
            locale: 'menu.userDetails',
            requiresAuth: true,
            roles: ['*'],
          },
        },
      ],
    },
  ],
};

**Comment by BestLee1989** [comment]
@sHow8e 
import { DEFAULT_LAYOUT } from '@/router/constans';

export default {
  path: '/',
  name: 'userManagement',
  component: DEFAULT_LAYOUT,
  meta: {
    locale: 'menu.userManagement',
    requiresAuth: true,
    icon: 'icon-user',
    order: 1,
  },
  children: [
    {
      path: '/userList',
      name: 'userList',
      component: () => import('@/views/userManagement/list.vue'),
      meta: {
        locale: 'menu.userList',
        requiresAuth: true,
        roles: ['*'],
      },
      children: [
        {
          path: '/userList/details',
          name: 'userDetails',
          component: () => import('@/views/userManagement/details.vue'),
          meta: {
            activeMenu: 'userList',
            locale: 'menu.userDetails',
            requiresAuth: true,
            roles: ['*'],
          },
        },
      ],
    },
  ],
};

**Comment by sHow8e** [comment]
@BestLee1989 hihi 我这边试了一下可以显示detail页。面作为list的子页面，估计你list页面里没有提供<router-view>容器。所以导致不显示。你先check一下。

**Comment by BestLee1989** [comment]
@sHow8e 好的  谢谢
