### ISSUE TITLE
安装启动项目成功后，无法直接登录

### ISSUE THREAD

**Issue by SamsonSir** [arco-design/arco-design-pro-vue#124]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.4
- **Browser:** chrome102.0.0.0

## What is expected?
arco init 项目后，直接启动项目，本地服务端口号默认3000，mockjs版本号"^1.1.0","@arco-design/web-vue": "^2.30.2","@types/mockjs": "^1.0.4","arco-design-pro-vue": "^2.5.4",。没有修改任何文件无法直接登录，也尝试去掉setup-mock文件里环境变量判断和更改.env下VITE_API_BASE_URL地址与本地服务端口号一直，都无法正常直接登录。（确认本地没有启其他服务）

step-1：
![1655536074(1)](https://user-images.githubusercontent.com/15686178/174427315-ba982640-0a82-4863-9b17-9d36d314e8f1.png)
step-2:
![1655536695(1)](https://user-images.githubusercontent.com/15686178/174427360-7c67dcab-32b6-4d86-9aa1-6457c5626ecb.png)
(更改.env.development下VITE_API_BASE_URL地址与端口号一致结果)
![1655536765(1)](https://user-images.githubusercontent.com/15686178/174427392-3ce503ed-9c8c-4fd3-8626-e472ea3c483e.png)

**Comment by sHow8e** [comment]
@SamsonSir hi。我这边进行多次初始化。使用同样版本的包无法复现这个问题。由于mockjs是默认开启，并且开发环境是不会有请求记录的。建议往mock这边进行排查。如果没有进行代码的修改，可以尝试删除依赖并重新安装依赖后换一个启动端口试试。3q

**Comment by SamsonSir** [comment]
我也是试过很多次的init项目，还有换了三台不同的机器。结果都是一样登录不了

**Comment by sHow8e** [comment]
@SamsonSir 你这三台都是windows么？

**Comment by sHow8e** [comment]
@SamsonSir 可能是你浏览器设置有问题（估计不是允许覆写xmlhttprequest，所以mock才不生效） 或者 插件有影响。你也试试别的浏览器，应该是好的。

**Comment by SamsonSir** [comment]
嗯嗯  感谢。

**Comment by mablevi** [comment]
我这边也出现这个问题了，精简代码之后也不行。但是我自己写个新的demo，用mockjs就可以拦截。但是运行咱们pro的项目，就必须用无痕模式。

**Comment by sHow8e** [comment]
@mablevi hihi 这个问题影响因素比较多，比如平台、浏览器版本、mockjs版本、插件影响。可以自行尝试排查一下。

**Comment by gcywss** [comment]
我也遇到这个问题了，我记得我一个月前测试时都还行，今天尝试 mock 怎么都不生效。怪哉

**Comment by gcywss** [comment]
我的问题找到了，是浏览器的一个插件引起的，Ajax Interceptor，卸载就好了。玛德

**Comment by mablevi** [comment]
@gcywss  你这么一说，我也是装了这个 Ajax Interceptor 这个插件后，不能mock了。

**Comment by MoncyJa** [comment]
@gcywss 我也是装了这个插件的原因 但很奇怪的是我有插件的情况下启了React版的ArcoDesign是可以mock Vue版的就不行 绝了

**Comment by li1164267803** [comment]
我也是这个插件的问题，垃圾真服气了
