### ISSUE TITLE
bulid后通过nginx部署，页面是空白的

### ISSUE THREAD

**Issue by ahualy** [arco-design/arco-design-pro-vue#125]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.4
- **Browser:** chrome102.0.5005.61

## Steps to reproduce
nginx 配置信息
 location / {
            root   /html/dist;
            index  index.html index.htm;
            try_files $uri $uri/ @router;
        }
        location @router {
            rewrite ^.*$ /index.html last;
        }

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40875528/174438163-1347195c-5dc1-45e1-bcc9-faf51f6b2179.png">

**Comment by sHow8e** [comment]
@ahualy hihi 我观察到你浏览器调试有个报错。可以看看报错是啥？在部署之前可以在本地文件夹执行一下 npm run preview命令。如果能够打开预览表示项目层面可能没什么问题。应该去看看nginx部分的配置。3q

**Comment by Yuxiaogang-Gavin** [comment]
我这也是，报‘css 未载入，因为它的 MIME 类型 “text/html” 不是 “text/css”。’

**Comment by Yuxiaogang-Gavin** [comment]
实施部署让我加上 type="text/css"，这个如何配置，还有如何给index.html配置css和js配置二级路径 才能让build时生效。

**Comment by sHow8e** [comment]
@Yuxiaogang-Gavin 这个着实是NGINX配置错误后返回的问题。不需要配置 `type="text/css"`。你可以先运行一下 npm run preview看看预览是否能打开。第二个问题看[vite](https://www.vitejs.net/config/#publicdir)的文档。

**Comment by Yuxiaogang-Gavin** [comment]
@sHow8e 是的，感谢
