### ISSUE TITLE
arco init hello-arco-pro 出现 “请提交你的 Git 修改后继续操作”

### ISSUE THREAD

**Issue by swurtheone** [arco-design/arco-design-pro-vue#126]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.5
- **Browser:** chrome101.0.0.0

**Comment by sHow8e** [comment]
@swurtheone 这个是arco-cli的报错。要求初始化的文件夹是全新的未进行git初始化的。

**Comment by swurtheone** [comment]
@sHow8e 
![image](https://user-images.githubusercontent.com/31538827/174942289-a034897c-a35d-4527-916e-864c6e9c0a1d.png)
是不是v1.27.1这个版本的问题，我更换了多个新文件夹和新环境都是如此

**Comment by sHow8e** [comment]
@sHow8e 这个错误提示确实是cli本身发出的。我现在本地用的`v1.26.1`，可以切换试试。如果还是不行，可以反馈到arco-cli。
