### ISSUE TITLE
可以有做一个一级菜单的demo吗？

### ISSUE THREAD

**Issue by huichen2017** [arco-design/arco-design-pro-vue#128]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 现有案例
希望可以支持一级和多级菜单。

## 预期解决问题
1、不知道是不是我使用错误了，我用一级菜单后头部和左侧菜单没有了（是否不支持一级菜单？）；
2、多级菜单可以，但是点击展开或者收缩的时候，2级和3级就都展开或者收缩了，我希望点击3级的收缩，2级的收缩不要动。

**Comment by sHow8e** [comment]
@huichen2017 hihi Pro支持一级菜单，看看是否配置有问题（如果是一级菜单，不要包含children字段）。多级菜单的问题可以看看菜单组件的[配置](https://arco.design/vue/component/menu)。

**Comment by huichen2017** [comment]
dashboard.ts 文件
export default {
  path: '/dashboard',
  name: 'Dashboard',
  component: () => import('@/views/dashboard/workplace/index.vue'),
  meta: {
    locale: 'menu.dashboard',
    requiresAuth: true,
    icon: 'icon-dashboard',
    order: 0,
  }
};
我是这么写的

**Comment by huichen2017** [comment]
参考这个 https://github.com/arco-design/arco-design-pro-vue/issues/85#issuecomment-1142289501 后可以实现了，谢谢大佬！！
多级菜单的问题没有出现了，可能是之前什么地方配置错了，谢谢。
