### ISSUE TITLE
适配ESLint最新版本

### ISSUE THREAD

**Issue by chenparty** [arco-design/arco-design-pro-vue#13]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
eslint升级到最新版8.7.0后，一共产生3类error、1类warning。
【error】：vue/multi-word-component-names、prefer-regex-literals、default-param-last
【warning】：warning  xxxx must be hyphenated. 此警告为某些绑定对象不能用驼峰命名，需要使用abc-def格式。

## Extra info
首先特别感谢有如此伟大的UI组件库和脚手架项目，希望TA越来越好，希望尽快完善。👍

**Comment by sHow8e** [comment]
hihi。感谢建议哈。
我这边使用cli初始化的项目，并且eslint升至v8.7.0。但是并没有出现相关的报错。麻烦提供一下具体报错信息以及依赖包版本进行排查哈。 如果是vscode内的报错，还需要仔细甄别一下是ts、eslint、vetur、又或者是volar的报错。3q

**Comment by chenparty** [comment]
![image](https://user-images.githubusercontent.com/16755257/150940446-8a8603b1-d23a-4511-a486-b5d862b0be80.png)
warning来源于vite2.7.13

**Comment by chenparty** [comment]
ERROR级别错误：
[plugin:vite:eslint] src\components\global-setting\index.vue
error  Component name "index" should always be multi-word  vue/multi-word-component-names

[plugin:vite:eslint] src\views\user\setting\mock.ts
error  Use a regular expression literal instead of the 'RegExp' constructor  prefer-regex-literals

[plugin:vite:eslint] src\utils\setup-mock.ts
error  Default parameters should be last  default-param-last

**Comment by sHow8e** [comment]
@chenparty hi 新版本2.2.1已经做了部分报错的兼容性处理。因为对应的依赖包会不断增加校验规则，所以出现个别报错信息在所难免哈。我这边也会尽量把控一下新版本规则。打码愉快哈~
