### ISSUE TITLE
image-preview 打包时找不到style/css.js

### ISSUE THREAD

**Issue by logben** [arco-design/arco-design-pro-vue#132]
Error: [vite]: Rollup failed to resolve import "XXXX/arco-design-pro-vite/node_modules/@arco-design/web-vue/es/image-preview/style/css.js" from "src/views/XXXXX/index.vue".
This is most likely unintended because it can break your application at runtime.
应该是文件不存在，重新yarn ，依然如故，不知原因，请赐教！！

**Comment by sHow8e** [comment]
@logben hi 可以参考一下这个 #71
