### ISSUE TITLE
建议：添加注册账号界面

### ISSUE THREAD

**Issue by CrazyBoyM** [arco-design/arco-design-pro-vue#133]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.7
- **Browser:** chrome103.0.5060.66

## What is expected?
如题，作为一个开箱即用的开发模板，只有登录界面而没有实现注册。

**Comment by sHow8e** [comment]
@CrazyBoyM 后续UI规范若有相关页面会进行添加哈。3q
