### ISSUE TITLE
feature requests: 增加mock开关以及完善文档示例

### ISSUE THREAD

**Issue by CrazyBoyM** [arco-design/arco-design-pro-vue#134]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.7
- **Browser:** chrome103.0.5060.66

## What is expected?
默认拉取的项目在dev模式下没有开启登录等接口mock，构建时也没办法把静态mock数据一并打包构建作为演示项目，在官网上查看文档没有相关介绍，可否补充一下这块的文档。我看其它后台模板项目自带的mock跟咱们的用法不是很一样，查看.env配置文件里面也没有对mock开关的相关配置

**Comment by sHow8e** [comment]
@CrazyBoyM 如果希望生成模式包含mock，可以把环境判断给去掉。

**Comment by CrazyBoyM** [comment]
嗯嗯，就是把项目拉下来yarn dev启动时，提示登录错误，感觉此时的登录mock接口匹配规则应该没生效。以及我自己配置了后端登录提示成功后，总要等半天才能进入到dashboard界面，有时刷新登录几次都进不去，还在查找原因。
