### ISSUE TITLE
vueuse 打包后无效，copy 方法会失效

### ISSUE THREAD

**Issue by 981433814** [arco-design/arco-design-pro-vue#136]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.7
- **Browser:** chrome102.0.0.0

## Steps to reproduce
useClipboard() 这个方法在本地是没有问题的，但是打包后方法就失效了，全局配置中的复制配置也无法使用

**Comment by sHow8e** [comment]
@981433814 hi 我本地打包以及线上demo都是没问题的。可以看看是否自己代码有误?或者是打包配置又或者是包版本问题。3q

**Comment by 981433814** [comment]
![image](https://user-images.githubusercontent.com/45874392/178202705-09ee0e17-cf7a-40e0-a29f-743a5c07826c.png)
@sHow8e  可能是vueuse的问题
