### ISSUE TITLE
TS类型报错

### ISSUE THREAD

**Issue by HavocZhang** [arco-design/arco-design-pro-vue#137]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.5.7
- **框架版本:** Vue
- **浏览器版本:** chrome103.0.5060.114

## 复现步骤
![image](https://user-images.githubusercontent.com/27353058/177968103-ba5f948c-b21c-4363-a6be-f9f5a6b6437b.png)

不能将类型“RouteRecordNormalized”分配给类型“RouteRecordRaw”。
  不能将类型“RouteRecordNormalized”分配给类型“RouteRecordMultipleViewsWithChildren”。

**Comment by HavocZhang** [comment]
还有一个报错
![image](https://user-images.githubusercontent.com/27353058/177968272-42fac02b-c360-4222-99a9-d981059be823.png)

**Comment by sHow8e** [comment]
@HavocZhang hi 由于依赖的版本变动，这些类型问题可以自行在项目中处理哈。

**Comment by GeekSRE** [comment]
请问怎么处理的？

**Comment by shuax** [comment]
同问如何修改
