### ISSUE TITLE
建议：增加页面KeepAlive能力

### ISSUE THREAD

**Issue by CrazyBoyM** [arco-design/arco-design-pro-vue#138]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.7
- **Browser:** chrome103.0.5060.66

## What is expected?
目前在不同页面之间跳转的话，页面中的数据都会丢失。如组件的状态，已经上传加载的图片等，请求支持页面级缓存。3q

**Comment by sHow8e** [comment]
@CrazyBoyM hi 该功能已经内置。打开多页签开关即可。或者按照自己需要，自行开启。

**Comment by CrazyBoyM** [comment]
实际测试多页签功能无效，页面的组件状态不会被缓存，当页面之前跳转时会丢失组件状态。


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月11日(周一) 上午10:45
收件人: ***@***.***&gt;;
抄送: &quot;Ke ***@***.******@***.***&gt;;
主题: Re: [arco-design/arco-design-pro-vue] 建议：增加页面KeepAlive能力 (Issue #138)




 
@CrazyBoyM hi 该功能已经内置。打开多页签开关即可。或者按照自己需要，自行开启。
 
&mdash;
