### ISSUE TITLE
 Rollup failed to resolve import  "***node_modules/_@arco-design_web-vue@2.33.0@/@arco-design/web-vue/es/message/style/css.js"

### ISSUE THREAD

**Issue by blly5** [arco-design/arco-design-pro-vue#139]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.7
- **Browser:** chrome103.0.0.0

## Steps to reproduce
arco-vue-pro v1.27.2
arco-design/web-vue v2.33.0
node_modules目录是 @arco-design_web-vue@2.33.0@@arco-design，打包时中间多了个"/" 就找不到文件了

**Comment by sHow8e** [comment]
@blly5  hi 可以参考一下这个 https://github.com/arco-design/arco-design-pro-vue/issues/71
