### ISSUE TITLE
import '@arco-design/theme-line/index.less'

### ISSUE THREAD

**Issue by blly5** [arco-design/arco-design-pro-vue#141]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.7
- **Browser:** chrome103.0.0.0

## Steps to reproduce
开发环境是可以的，构建后 主题包样式是有的，但是还是会被原来蓝色主题样式给覆盖了

**Comment by Gzbox** [comment]
我也遇到了  上来看看有没有解决方案呢   开发是好的  构建完样式就失效了
