### ISSUE TITLE
建议增加对 axios的封装，而不是在api模块中直接使用

### ISSUE THREAD

**Issue by easy-mj** [arco-design/arco-design-pro-vue#142]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.7
- **Browser:** chrome103.0.0.0

**Comment by sHow8e** [comment]
@easy-mj hi 首先感谢建议。在pro里axios本身已经配置了拦截器（interceptor.js），能覆盖大部分日常场景不需要再对axios进行二次封装。同时基于es模块的特性，导入的是引用而不是拷贝，利用这个特性可以直接使用即可。再来的话，因为pro的模块间存在一定的相互依赖，对axios封装会导致循环引用问题。如果真的项目有特别需要，可以自行进行实例化和配套处理。

**Comment by Fluox-Etine** [comment]
> @easy-mj hi 首先感谢建议。在pro里axios本身已经配置了拦截器（interceptor.js），能覆盖大部分日常场景不需要再对axios进行二次封装。同时基于es模块的特性，导入的是引用而不是拷贝，利用这个特性可以直接使用即可。再来的话，因为pro的模块间存在一定的相互依赖，对axios封装会导致循环引用问题。如果真的项目有特别需要，可以自行进行实例化和配套处理。

我觉应该还要封装一层的request的ts文件；因为一般服务器接口报错直接全局拦截；不用在请求中再去判断接口的是否正常的
