### ISSUE TITLE
自己重新 npm install 后，build报错

### ISSUE THREAD

**Issue by Yuxiaogang-Gavin** [arco-design/arco-design-pro-vue#143]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.7
- **Browser:** chrome86.0.4240.198

## Steps to reproduce
把原先的node_modules后，重新npm install后，再build
先是报 Please update to v0.35.0 or higher for TypeScript version: 4.7.4（下面的错也报了）
然后 改成 "vue-tsc": "^0.35.0"，还是报下面这个错。
 

src/router/index.ts:35:5 - error TS2322: Type 'RouteRecordNormalized' is not assignable to type 'RouteRecordRaw'.
  Type 'RouteRecordNormalized' is not assignable to type 'RouteRecordRedirect'.
    Types of property 'redirect' are incompatible.
      Type 'RouteRecordRedirectOption | undefined' is not assignable to type 'RouteRecordRedirectOption'.
        Type 'undefined' is not assignable to type 'RouteRecordRedirectOption'.

35 ...appRoutes,

**Comment by sHow8e** [comment]
@Yuxiaogang-Gavin hihi 这个是ts相关的报错。建议代码层面去解决。如果对代码有信心，可以尝试打包命令里去掉tsc检查。

**Comment by Yuxiaogang-Gavin** [comment]
好的，后来发现换个vue-router 版本解决了。vue-router使用4.0.14 版本，就行了。用最高的版本会出现上面错误

**Comment by sHow8e** [comment]
@Yuxiaogang-Gavin 版本更迭确实存在这些类型问题，根据提示去调整就行。组件库也类似~ good luck。

**Comment by Yuxiaogang-Gavin** [comment]
@sHow8e 是的。我自己用npm install 安装，安装的全是最高版本（不知道这个能否哪里控制）。所以就出现上面的问题，后来重新arco 一个，发现了版本不一样。
