### ISSUE TITLE
使用脚手架创建项目后，运行失败，访问不了呢

### ISSUE THREAD

**Issue by easy-mj** [arco-design/arco-design-pro-vue#144]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.7
- **Browser:** chrome103.0.0.0

<!-
- generated by arco-issue. DO NOT REMOVE -->
![20220720192342](https://user-images.githubusercontent.com/11886313/179970647-4e5c6506-3e71-4573-8ab0-7dfddbface82.jpg)
![image](https://user-images.githubusercontent.com/11886313/179971044-693b7f4c-a59f-40f8-aadb-49da2a2dd77d.png)

**Comment by sHow8e** [comment]
@easy-mj 你这个是不是端口和其它服务串了。。。你换个端口从默认访问路径试试。

**Comment by easy-mj** [comment]
@sHow8e 确实如此，运行成功了~
