### ISSUE TITLE
请问如何合并这些细小的文件为一个文件？  比如，我在一个父页面有a, b, c, d, e, f 6个小子组件，如果每个子组件打包成单独的js和css，这样的话加载网页时浏览器就会频繁请求资源，  所以，  我想把a, b, c, d, e, f等子组件打包在一起，或者说  把a, b, c, d, e, f页面打包在父页面的资源文件中，  把请问该如何配置？  谢谢。

### ISSUE THREAD

**Issue by 13538142489** [arco-design/arco-design-pro-vue#146]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 现有案例
    build: {
      rollupOptions: {
        output: {
          manualChunks: {
            arco: ['@arco-design/web-vue'],
            vue: ['vue', 'vue-router', 'pinia', '@vueuse/core'],
            // vue: ['vue', 'vue-router', 'pinia', '@vueuse/core', 'vue-i18n'],
          },
        },
      },
      chunkSizeWarningLimit: 2000,
    },

## 预期解决问题
合并父组件内的子组件的资源为和父组件同一个资源

**Comment by sHow8e** [comment]
@13538142489 vite基于rollup进行构建，可以看一下rollup代码拆分相关。还有问题描述不要写在标题。3q
