### ISSUE TITLE
[需求]大佬可以添加多页签功能嘛？

### ISSUE THREAD

**Issue by herofqy** [arco-design/arco-design-pro-vue#148]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
比如vue-vben-admin

## What problem does this feature solve?
后台应用一般都需要多页签（多标签页）。

**Comment by sHow8e** [comment]
@herofqy hi 该功能已经内置了。你登录进去后看一下右上角页面配置，有个多页签选项。打开就能开启了。
