### ISSUE TITLE
acro-web 从2.24.0 -> 2.27.0 全是typescript 类型保错 

### ISSUE THREAD

**Issue by 981433814** [arco-design/arco-design-pro-vue#149]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.7
- **Browser:** chrome103.0.0.0

## What is expected?
acro-web 从2.24.0 -> 2.27.0 全是typescript 类型保错 , 官网的例子不是typescript的，又看源码才知道传啥值，心累

**Comment by sHow8e** [comment]
@981433814 hi 我这边后续处理下周发个版本哈。目前你可以先根据vscode里的提示进行调整。3q
