### ISSUE TITLE
多页签启用时，当打开的页签挤满了页签栏时，再打开新的页签，其将不显示在页签栏的可视区域，且右侧出现无实际作用的上下箭头按钮

### ISSUE THREAD

**Issue by herofqy** [arco-design/arco-design-pro-vue#150]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.7
- **Framework version:** Vue
- **Browser:** chrome103.0.5060.134

## Extra info
参考：https://vvbin.cn/next/#/dashboard/analysis

## What is expected?
1. 在页签栏位被占满时，再打开新的页签，其将显示在页签栏的可视区域，且有按钮或者滚动鼠标中键将可视区外的页签滚动到可视区内。
2. 【新功能】添加刷新按钮重新加载当前页签。

## Steps to reproduce
1. 访问http://vue-pro.arco.design/
2. 将浏览器宽度缩小到1366以尽快占满页签栏
3. 依次打开尽可能多的页签
4. 在页签栏位被占满时，再打开新的页签，其将不显示在页签栏的可视区域，且右侧出现无实际作用的上下箭头按钮

**Comment by sHow8e** [comment]
@herofqy hihi 后续会新增“重新加载”功能。页签滚动到可视区内，可以使用tab组件自行处理。或者欢迎Pr哈。3q

**Comment by sHow8e** [comment]
done [v.2.5.9](https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.5.9)
