### ISSUE TITLE
div里面的表格内当前展开的子项能否定位到当前展开行

### ISSUE THREAD

**Issue by XM36578** [arco-design/arco-design-pro-vue#151]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
就是树形table 锚点 Anchor联合的一个效果，打开跳转并定位到当前的展开行

## What problem does this feature solve?
就是树形table 锚点 Anchor联合的一个效果，打开跳转并定位到当前的展开行

**Comment by sHow8e** [comment]
@XM36578 hi 组件使用问题 可以反馈到组件库的issue 或者进入飞书群提问哈。3q

**Comment by XM36578** [comment]
飞书群怎么进呢

**Comment by sHow8e** [comment]
@XM36578 hi 官网文档的底部有个二维码，可以扫描进群哈。
