### ISSUE TITLE
使用designlab的主题包组件自定义的样式打包发布后会被默认的覆盖掉

### ISSUE THREAD

**Issue by dodudo** [arco-design/arco-design-pro-vue#152]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.5.7
- **框架版本:** Vue
- **浏览器版本:** chrome97.0.4692.99

## 额外补充
使用designlab的主题包组件自定义的样式会被默认的覆盖掉，全局配置的颜色不会被覆盖掉，但单独修改某个组件样式，会被局部引用的默认样式覆盖掉，本地开发不会，请问是不是打包配置哪里有问题，我按照文档操作的，不是使用的开发者模式修改的样式，是直接修改单个组件的颜色
![image](https://user-images.githubusercontent.com/55090240/182089480-ea6554cb-cd6a-4696-9a94-712d998da73e.png)

**Comment by sHow8e** [comment]
@dodudo 这个是按需加载的插件引起的。你禁用 configArcoResolverPlugin 应该就可以了。
