### ISSUE TITLE
npm run build部署后登录请求405错误

### ISSUE THREAD

**Issue by AlienegraGeek** [arco-design/arco-design-pro-vue#154]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.5.7
- **框架版本:** @vue/cli 5.0.8
- **浏览器版本:** chrome104.0.0.0

## 复现步骤
本地npm run dev测试请求和接口都没有问题，修改对应的VITE_API_BASE_URL服务url之后，npm run build打包dist部署到服务器，登录界面提示请求405错误，请问是我缺少哪些配置吗？
nginx config 配置如下
![image](https://user-images.githubusercontent.com/33959579/183369096-6414af97-11fe-4e8b-83f1-72689ed5c25a.png)

生产环境如下
![image](https://user-images.githubusercontent.com/33959579/183369305-c8025b23-8847-4f74-9b5b-7c476b6086a8.png)

**Comment by sHow8e** [comment]
@AlienegraGeek hi 。如果你只想单纯打包部署看看。那你就要把https://github.com/arco-design/arco-design-pro-vue/blob/1cdd29a8f731bc86303fa0c32f25626eab103ab5/arco-design-pro-vite/src/utils/setup-mock.ts#L4
这部分给修改一下。否则mock在生成环境不会生效。如果你有自己的接口，你就要在nginx做一层proxy，代理到自己接口所在的地址。

**Comment by AlienegraGeek** [comment]
> @AlienegraGeek hi 。如果你只想单纯打包部署看看。那你就要把
> 
> https://github.com/arco-design/arco-design-pro-vue/blob/1cdd29a8f731bc86303fa0c32f25626eab103ab5/arco-design-pro-vite/src/utils/setup-mock.ts#L4
> 
> 
> 这部分给修改一下。否则mock在生成环境不会生效。如果你有自己的接口，你就要在nginx做一层proxy，代理到自己接口所在的地址。

好的，感谢，已经解决了，我发现是由于.env.production内没有定义VITE_API_BASE_URL，我定义之后，再将.env.development中的VITE_API_BASE_URL去掉，就可以调通自己的接口了

**Comment by EricDoZen** [comment]
> > @AlienegraGeek hi 。如果你只想单纯打包部署看看。那你就要把
> > https://github.com/arco-design/arco-design-pro-vue/blob/1cdd29a8f731bc86303fa0c32f25626eab103ab5/arco-design-pro-vite/src/utils/setup-mock.ts#L4
> > 
> > 这部分给修改一下。否则mock在生成环境不会生效。如果你有自己的接口，你就要在nginx做一层proxy，代理到自己接口所在的地址。
> 
> 好的，感谢，已经解决了，我发现是由于.env.production内没有定义VITE_API_BASE_URL，我定义之后，再将.env.development中的VITE_API_BASE_URL去掉，就可以调通自己的接口了

The .env.development file defaults is VITE_API_BASE_URL= 'http://localhost:8080'.
and I went to edit the file .env.production by adding
VITE_API_BASE_URL= 'http://localhost:8080' but still unable to login.
