### ISSUE TITLE
arco-design-pro-vue 控制台报错

### ISSUE THREAD

**Issue by SunYuanOnly** [arco-design/arco-design-pro-vue#155]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.5.8
- **框架版本:**  "vue": "^3.2.37",
- **浏览器版本:** Microsoft Edge 版本 104.0.1293.47 (正式版本) (64 位)
- **复现地址:** http://vue-pro.arco.design/dashboard/workplace

**Comment by SunYuanOnly** [comment]
![image](https://user-images.githubusercontent.com/16498201/183554982-be4ead63-789a-4733-8eb6-f000a324e747.png)

**Comment by hehehai** [comment]
@SunYuanOnly 你好，可以手动升级下 arco-vue 的版本，这个在新版本已经修复了

**Comment by SunYuanOnly** [comment]
> @SunYuanOnly 你好，可以手动升级下 arco-vue 的版本，这个在新版本已经修复了

Ok
