### ISSUE TITLE
arco init 初始化项目时提示eslint依赖错误

### ISSUE THREAD

**Issue by mooseen** [arco-design/arco-design-pro-vue#156]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.8
- **Browser:** chrome104.0.0.0

## Extra info
? Please select the framework you want to use Vue
? Please select the type of project you want to create Arco Pro Project
? Please choose the template of Arco Pro Full version (contains all pages)

✔ Get project template successfully
✔ Template content copy completed
✔ Template content adaptation completed
✖ Project dependency installation failed, you can try to manually install them later
Error: Command 「npm install」 executed failed:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: arco-design-pro-vue@1.0.0
npm ERR! Found: eslint@8.7.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"^8.7.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.16.0 || ^6.8.0 || ^7.2.0" from eslint-config-airbnb-base@14.2.1
npm ERR! node_modules/eslint-config-airbnb-base
npm ERR!   dev eslint-config-airbnb-base@"^14.2.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by fairySusan** [comment]
把package.json里的eslint：@"^8.7.0" 改为 eslint@"^7.2.0" npm install 就正常了

**Comment by zivenyang** [comment]
我把`package.json`中的`"eslint-config-airbnb-base": "^14.2.1",`改为`"eslint-config-airbnb-base": "^15.0.0",`之后`npm install`就不报错了
![image](https://user-images.githubusercontent.com/26645341/192922360-515998b6-1948-4dd5-995c-3ecbd3cd896c.png)
