### ISSUE TITLE
浏览器兼容

### ISSUE THREAD

**Issue by 379949990** [arco-design/arco-design-pro-vue#157]
- [ ] I'm sure this does not appear in [[the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 

- **Package Name And Version:** arco-design-pro-vue@2.5.6
- **Framework version:** vue: 3.2.37
- **Browser:** Chrome 版本 104.0.5112.79（正式版本） (arm64)

当我的Chrome更新到给我推送的最新版本【 104.0.5112.79（正式版本） (arm64)】后，浏览器控制台给了我一些警告：
<img width="595" alt="image" src="https://user-images.githubusercontent.com/66375788/184058390-73c11781-1b30-4a64-a9d4-9d55a3e70f64.png">

```bash
Found a 'popup' attribute. If you are testing the popup API, you must enable Experimental Web Platform Features. If not, note that custom attributes must start with 'data-': <URL>. This usage will *likely cause site breakage* when the popup API ships: <URL>.
-> Found a 'popup' attribute. If you are testing the popup API, you must enable Experimental Web Platform Features. If not, note that custom attributes must start with 'data-': https://html.spec.whatwg.org/multipage/dom.html#custom-data-attribute. This usage will *likely cause site breakage* when the popup API ships: https://chromestatus.com/feature/5463833265045504.
```

在更新Chrome前是不存在该警告的，我想知道这在未来是否会引发风险以及我是否可以无视它。

**Comment by sHow8e** [comment]
@379949990 hi 该问题已经在组件库(v2.34.1)进行了修复。当前把Pro里依赖的Arco组件库升至最新版本即可。3q [相关issue](https://github.com/arco-design/arco-design-vue/issues/1486)
