### ISSUE TITLE
Cannot login after run command "npm run preview"

### ISSUE THREAD

**Issue by EricDoZen** [arco-design/arco-design-pro-vue#158]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.9
- **Framework version:** vue : 3.2.31
- **Browser:** chrome104.0.5112.81

## Extra info
When run command "npm run dev" there is able to login, but  command build and preview is cannot to login.
运行命令“npm run dev”时可以登录，但运行命令构建和预览无法登录。

**Comment by sHow8e** [comment]
@EricDoZen hi ~ 构建和预览是需要调用真实接口的。如果你仅仅是想看打包效果，你得判断环境把mock数据加入进去。

**Comment by EricDoZen** [comment]
> @EricDoZen hi ~ 构建和预览是需要调用真实接口的。如果你仅仅是想看打包效果，你得判断环境把mock数据加入进去。

If so, which file do I need to add mock data to? Do you have an example? which files need to be edited and where to edit or what code to add?
如果是这样，我需要将模拟数据添加到哪个文件？ 你有一个例子吗？ 哪些文件需要编辑，在哪里编辑或添加什么代码？

**Comment by sHow8e** [comment]
@EricDoZen You can try to refer to this issue. [link](https://github.com/arco-design/arco-design-pro-vue/issues/154#issuecomment-1207909392)

**Comment by EricDoZen** [comment]
> @EricDoZen You can try to refer to this issue. [link](https://github.com/arco-design/arco-design-pro-vue/issues/154#issuecomment-1207909392)

I try the link But I don't quite understand what to do with the setup-mock.ts file. What am I going to do with this part of the code?
if (mock !== false && debug) setup();

我试试链接 但我不太明白如何处理 setup-mock.ts 文件。 我应该如何处理这部分代码？
if (mock !== false && debug) setup();

**Comment by EricDoZen** [comment]
> @EricDoZen You can try to refer to this issue. [link](https://github.com/arco-design/arco-design-pro-vue/issues/154#issuecomment-1207909392)

From this 
> > @AlienegraGeek hi 。如果你只想单纯打包部署看看。那你就要把
> > https://github.com/arco-design/arco-design-pro-vue/blob/1cdd29a8f731bc86303fa0c32f25626eab103ab5/arco-design-pro-vite/src/utils/setup-mock.ts#L4
> > 
> > 这部分给修改一下。否则mock在生成环境不会生效。如果你有自己的接口，你就要在nginx做一层proxy，代理到自己接口所在的地址。
> 
> 好的，感谢，已经解决了，我发现是由于.env.production内没有定义VITE_API_BASE_URL，我定义之后，再将.env.development中的VITE_API_BASE_URL去掉，就可以调通自己的接口了


The .env.development file defaults is VITE_API_BASE_URL= 'http://localhost:8080/'.
and I went to edit the file .env.production by adding
VITE_API_BASE_URL= 'http://localhost:8080/' but still unable to login.

**Comment by sHow8e** [comment]
@EricDoZen If you just want to pack mock data. `if (mock !== false && debug) setup(); ` >>>`if (mock !== false) setup(); `

**Comment by EricDoZen** [comment]
> @EricDoZen If you just want to pack mock data. `if (mock !== false && debug) setup(); ` >>>`if (mock !== false) setup(); `

It work, Thanks!
