### ISSUE TITLE
多页签重新加载没有重新调用页面接口

### ISSUE THREAD

**Issue by cxiniao** [arco-design/arco-design-pro-vue#159]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.5.9
- **浏览器版本:** chrome104.0.0.0

## 预期结果
多页签重新加载应该重新调用页面接口

**Comment by sHow8e** [comment]
@cxiniao hi 因为现在重载没有彻底清掉缓存，我下周把逻辑补充一下。-_-!

**Comment by sHow8e** [comment]
done [v2.5.10](https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.5.10)
