### ISSUE TITLE
官方示例收缩侧边栏时变形了

### ISSUE THREAD

**Issue by dfang** [arco-design/arco-design-pro-vue#16]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.2.1
- **System:** macOS big sur 11.6.2
- **Browser:** Safari 15.2
- **Reproduction Link:** https://vue-pro.arco.design/visualization/data-analysis

## What is expected?
侧边栏显示正常

## Steps to reproduce
无法上传截图

**Comment by sHow8e** [comment]
@dfang 看了一下，组件这边做了一下使用的调整。这周二发版进行修复哈。3q
