### ISSUE TITLE
官方提供多主题支持

### ISSUE THREAD

**Issue by wuchunfu** [arco-design/arco-design-pro-vue#161]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 现有案例
抖音创作服务平台品牌风格

## 预期解决问题
希望支持像 semi-design 提供的多主题，比如：抖音创作服务平台品牌风格、飞书Universe Design风格、剪映 - 艺术家开放平台风格、火山引擎品牌风格、一个轻量美观的桌面端设计系统、Figma theme by Semi Design 等，最希望支持的主题是 抖音创作服务平台品牌风格

**Comment by sHow8e** [comment]
@wuchunfu hi 主题方面。Arco提供了[风格配置平台](https://arco.design/themes/?currentPage=1&onlyPublished=false&pageSize=9&sortBy=starCount&tag=all)供使用。[使用文档](https://arco.design/docs/designlab/guideline)。

**Comment by shuax** [comment]
帮助是react的，vue怎么用呢？

**Comment by sHow8e** [comment]
@shuax 一样的用法。创建主题的时候选择vue就行。
