### ISSUE TITLE
使用多页签，点击详情页面时，报错

### ISSUE THREAD

**Issue by Yuxiaogang-Gavin** [arco-design/arco-design-pro-vue#163]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.7
- **Browser:** chrome86.0.4240.198

## Extra info
使用多页签，点击详情页面时（路由后面带id），报错。点击其他页面正常
arco.9c4b4982.js:4 Error: Missing required param "id"

我的详情页路由配置如下
{
      path: 'partymembers/:id',
      name: '党员信息',
      component: () => import('@/views/information/partymembers/info.vue'),
      meta: {
        locale: 'menu.information.partymembers.info',
        requiresAuth: true,
        roles: ['*'],
        hideInMenu: true,
      },
    },

**Comment by sHow8e** [comment]
@Yuxiaogang-Gavin hi 根据报错信息，应该是跳转过去路径没有带上id吧。可以看看vue-router的文档哈。如果确定是Pro的问题，麻烦补充更多细节。

**Comment by Yuxiaogang-Gavin** [comment]
@sHow8e 谢谢您的反馈
就是启用多页签后，点击多页签带id的页面，会报上面的错误。
在列表页用的是如下跳转：
// 新增
const addData = () => {
  router.push('/information/partymembers/add');
};
// 配置
const Update = (id) => {
  router.push(`/information/partymembers/${id}`);
};

在详情页用的是如下获取id：
router.currentRoute.value.params.id

**Comment by oaktreecode** [comment]
> @Yuxiaogang-Gavin hi 根据报错信息，应该是跳转过去路径没有带上id吧。可以看看vue-router的文档哈。如果确定是Pro的问题，麻烦补充更多细节。

为什么关闭了这个问题？这个有什么解决方案？谢谢

**Comment by mltpig** [comment]
同问，请问该问题如何解决啊~~~

**Comment by yangwulang** [comment]
解决办法：修改store/tab-bar/types.ts中TagProps的定义
`
export interface TagProps {
  title: string;
  name: string;
  fullPath: string;
  params?: any; // 此处是修改点
  query?: any;
  ignoreCache?: boolean;
}
`
修改同目录下index.ts的formatTag函数
`
const formatTag = (route: RouteLocationNormalized): TagProps => {
  const { name, meta, fullPath, query, params } = route;
  return {
    title: meta.locale || '',
    name: String(name),
    params,
    fullPath,
    query,
    ignoreCache: meta.ignoreCache,
  };
};
`
只需要修改上面两个地方就可以，其它不用动
