### ISSUE TITLE
多页签右键重载后，重载页面缓存失效

### ISSUE THREAD

**Issue by cxiniao** [arco-design/arco-design-pro-vue#164]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.5.10
- **框架版本:** 2.34.1
- **浏览器版本:** chrome104.0.0.0

## 预期结果
多页签右键重载后，重载页面缓存依然有效

**Comment by sHow8e** [comment]
@cxiniao hi 如果你希望重载后缓存生效，可以把清缓存那部分逻辑删掉。

**Comment by cxiniao** [comment]
@sHow8e 可能是我描述得不够清楚。现在的情况是，页面A在多页签进行右键重载后，每次切换多页签到页面A，页面A都是重载。在我的理解里，页面A点击重载按钮，仅仅是当前次进行重载，而不是页面A进行过重载操作后，每次切换到页面A都是重载。

**Comment by sHow8e** [comment]
@cxiniao 可以提供一下动图么？

**Comment by cxiniao** [comment]
> @cxiniao 可以提供一下动图么？

正常：
![正常](https://user-images.githubusercontent.com/42397970/185842929-58aa9af4-5879-454b-9fcb-eb84f34740b7.gif)

重载后（每次切换到该页面都重载了）：
![重载后](https://user-images.githubusercontent.com/42397970/185842956-caf90dec-af50-4939-831e-1abd0cb229a5.gif)

**Comment by cxiniao** [comment]
@sHow8e 我看了看源码，是清除缓存那部分逻辑没处理好。现在是清除了缓存 （tabBarStore.deleteCache(itemData);），但是没有考虑到重载页面清除缓存后，也应该把重载后的页面加入缓存。这样就导致了以上的问题。现在是需要把重载后的页面关掉再打开，才能重新正常生成缓存。

**Comment by sHow8e** [comment]
@cxiniao [源码](https://github.com/arco-design/arco-design-pro-vue/blob/03df674dd09f5919977579a858f0909e617bb0c4/arco-design-pro-vite/src/components/tab-bar/tab-item.vue#L162)中有做移除后又添加操作。

**Comment by cxiniao** [comment]
> @cxiniao [源码](https://github.com/arco-design/arco-design-pro-vue/blob/03df674dd09f5919977579a858f0909e617bb0c4/arco-design-pro-vite/src/components/tab-bar/tab-item.vue#L162)中有做移除后又添加操作。

看到了，确实是我这边项目的问题。
