### ISSUE TITLE
本地打包正常，放到服务器上访问报错 Failed to resolve module specifier "@arco-design/web-vue" 

### ISSUE THREAD

**Issue by abnereel** [arco-design/arco-design-pro-vue#166]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.5.10
- **框架版本:** 3.2.31
- **浏览器版本:** chrome104.0.0.0

## 错误信息
错误信息：Uncaught TypeError: Failed to resolve module specifier "@arco-design/web-vue". Relative references must start with either "/", "./", or "../".

## 依赖：
"dependencies": {
    "@aomao/engine": "^2.9.28",
    "@aomao/plugin-alignment": "^2.9.27",
    "@aomao/plugin-backcolor": "^2.9.27",
    "@aomao/plugin-bold": "^2.9.27",
    "@aomao/plugin-code": "^2.9.28",
    "@aomao/plugin-codeblock-vue": "^2.9.29",
    "@aomao/plugin-file": "^2.9.27",
    "@aomao/plugin-fontcolor": "^2.9.27",
    "@aomao/plugin-fontfamily": "^2.9.27",
    "@aomao/plugin-fontsize": "^2.9.27",
    "@aomao/plugin-heading": "^2.9.27",
    "@aomao/plugin-hr": "^2.9.27",
    "@aomao/plugin-image": "^2.9.28",
    "@aomao/plugin-indent": "^2.9.27",
    "@aomao/plugin-italic": "^2.9.27",
    "@aomao/plugin-line-height": "^2.9.27",
    "@aomao/plugin-link-vue": "^2.9.30",
    "@aomao/plugin-mark": "^2.9.27",
    "@aomao/plugin-math": "^2.9.27",
    "@aomao/plugin-mention": "^2.9.29",
    "@aomao/plugin-orderedlist": "^2.9.27",
    "@aomao/plugin-paintformat": "^2.9.27",
    "@aomao/plugin-quote": "^2.9.27",
    "@aomao/plugin-redo": "^2.9.27",
    "@aomao/plugin-removeformat": "^2.9.27",
    "@aomao/plugin-selectall": "^2.9.27",
    "@aomao/plugin-status": "^2.9.27",
    "@aomao/plugin-strikethrough": "^2.9.27",
    "@aomao/plugin-sub": "^2.9.27",
    "@aomao/plugin-sup": "^2.9.28",
    "@aomao/plugin-table": "^2.9.31",
    "@aomao/plugin-tasklist": "^2.9.27",
    "@aomao/plugin-underline": "^2.9.27",
    "@aomao/plugin-undo": "^2.9.27",
    "@aomao/plugin-unorderedlist": "^2.9.27",
    "@aomao/plugin-video": "^2.9.28",
    "@aomao/toolbar-vue": "^2.9.31",
    "@arco-design/web-vue": "^2.35.1",
    "@babel/core": "^7.0.0-0",
    "@types/mockjs": "^1.0.4",
    "@vue/compiler-sfc": "^3.2.33",
    "@vueuse/core": "^7.3.0",
    "ant-design-vue": "v3.2.10",
    "arco-design-pro-vue": "^2.5.7",
    "axios": "^0.24.0",
    "dayjs": "^1.10.7",
    "echarts": "^5.2.2",
    "lodash": "^4.17.21",
    "mitt": "^3.0.0",
    "nprogress": "^0.2.0",
    "pinia": "^2.0.9",
    "qs": "^6.10.2",
    "query-string": "^7.0.1",
    "screenfull": "^6.0.1",
    "vue": "^3.2.31",
    "vue-echarts": "^6.0.0",
    "vue-router": "^4.0.14"
  }

## vite.config.prod.ts配置文件
import { mergeConfig } from 'vite';
import baseConfig from './vite.config.base';
import configCompressPlugin from './plugin/compress';
import configVisualizerPlugin from './plugin/visualizer';
import configArcoResolverPlugin from './plugin/arcoResolver';
import configStyleImportPlugin from './plugin/styleImport';
import configImageminPlugin from './plugin/imagemin';

export default mergeConfig(
  {
    base: ’/abc/‘,
    mode: 'production',
    plugins: [
      configCompressPlugin('gzip'),
      configVisualizerPlugin(),
      configArcoResolverPlugin(),
      configStyleImportPlugin(),
      configImageminPlugin(),
    ],
    build: {
      rollupOptions: {
        external: ['@arco-design/web-vue'],
        output: {
          manualChunks: {
            arco: ['@arco-design/web-vue'],
            chart: ['echarts', 'vue-echarts'],
            vue: ['vue', 'vue-router', 'pinia', '@vueuse/core'],
            aomao: [
              '@aomao/engine',
              '@aomao/plugin-alignment',
              '@aomao/plugin-backcolor',
              '@aomao/plugin-bold',
              '@aomao/plugin-code',
              '@aomao/plugin-codeblock-vue',
              '@aomao/plugin-file',
              '@aomao/plugin-fontcolor',
              '@aomao/plugin-fontfamily',
              '@aomao/plugin-fontsize',
              '@aomao/plugin-heading',
              '@aomao/plugin-hr',
              '@aomao/plugin-image',
              '@aomao/plugin-indent',
              '@aomao/plugin-italic',
              '@aomao/plugin-line-height',
              '@aomao/plugin-link-vue',
              '@aomao/plugin-mark',
              '@aomao/plugin-math',
              '@aomao/plugin-mention',
              '@aomao/plugin-orderedlist',
              '@aomao/plugin-paintformat',
              '@aomao/plugin-quote',
              '@aomao/plugin-redo',
              '@aomao/plugin-removeformat',
              '@aomao/plugin-selectall',
              '@aomao/plugin-status',
              '@aomao/plugin-strikethrough',
              '@aomao/plugin-sub',
              '@aomao/plugin-sup',
              '@aomao/plugin-table',
              '@aomao/plugin-tasklist',
              '@aomao/plugin-underline',
              '@aomao/plugin-undo',
              '@aomao/plugin-unorderedlist',
              '@aomao/plugin-video',
              '@aomao/toolbar-vue',
            ],
            screenfull: ['screenfull'],
            qs: ['qs'],
            axios: ['axios'],
            lodash: ['lodash'],
            nprogress: ['nprogress'],
          },
        },
      },
      chunkSizeWarningLimit: 2000,
    },
  },
  baseConfig
);

**Comment by sHow8e** [comment]
@abnereel 我这边用最新的pro打包部署是没问题。首先建议你把vite文档看一下。把打包配置项一步一步往里加。进而排除干扰。
