### ISSUE TITLE
尝试更新了一下页签右键操作，发现登录的时候在路径上拼接了一些参数，会出现两个工作台的页签

### ISSUE THREAD

**Issue by 981433814** [arco-design/arco-design-pro-vue#168]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.10
- **Browser:** chrome104.0.0.0

**Comment by sHow8e** [comment]
@981433814 hi 在页签内，只要url不一样，即生成不同的页签。

**Comment by shuax** [comment]
可能因为整个tab-bar对参数处理不太行，调用`router.push`会丢掉`params`和`query`，就会出现两个页签。
![image](https://user-images.githubusercontent.com/6940583/189819390-c46d830c-49a3-4198-a766-5868e053c7f1.png)
![image](https://user-images.githubusercontent.com/6940583/189819543-c13ac0fd-1710-4f41-bf14-7c449dc79f4d.png)
![image](https://user-images.githubusercontent.com/6940583/189819507-bf7ea3f8-5eb6-4d6a-82e3-f01ab019eea9.png)
我自己补充了一部分。
