### ISSUE TITLE
如何关闭内部的table filter 使用服务器来进行过滤啊？

### ISSUE THREAD

**Issue by Gzbox** [arco-design/arco-design-pro-vue#169]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.10
- **Browser:** chrome104.0.0.0

**Comment by sHow8e** [comment]
@Gzbox hi 可以看看组件文档哈 [table](https://arco.design/vue/component/table)
