### ISSUE TITLE
为什么react版本权限控制会比vue版本更细致，并且使用文档有独立说明

### ISSUE THREAD

**Issue by llocry** [arco-design/arco-design-pro-vue#17]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
react版本

## What problem does this feature solve?
可精准控制控件级别权限，譬如某按钮等

**Comment by sHow8e** [comment]
@llocry vue版本的也内置了权限指令，能够对元素进行精确控制。参见directive目录。文档说明后续补充哈。感谢提醒。
