### ISSUE TITLE
BUG: resize 集成vue-echarts自适应问题！

### ISSUE THREAD

**Issue by ZephyrTan** [arco-design/arco-design-pro-vue#171]
https://github.com/arco-design/arco-design-pro-vue/blob/03df674dd09f5919977579a858f0909e617bb0c4/arco-design-pro-vite/src/components/chart/index.vue#L5
嵌入vue-echarts时的auto-resize问题，此处传参不能写成kebab-case (短横线分隔命名) , 源码中用的是autoresize，必须使用这个才生效。

**Comment by shuax** [comment]
https://github.com/arco-design/arco-design-pro-vue/pull/122#discussion_r944158891

反馈很久了

**Comment by sHow8e** [comment]
@ZephyrTan @shuax 感谢反馈和pr。今天下午我review一下进行发版哈。3q
