### ISSUE TITLE
一级菜单不能设置为隐藏

### ISSUE THREAD

**Issue by liaorg** [arco-design/arco-design-pro-vue#173]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.10
- **Browser:** chrome105.0.0.0

## What is expected?
希望可以隐藏一级菜单
use-menu-tree.ts
30行这样：
        // 隐藏一级菜单
        if (element.meta?.hideInMenu === true) {
          return null;
        }

## Steps to reproduce
设置一级菜单的：hideInMenu: true

**Comment by sHow8e** [comment]
@liaorg hi 估计是你把属性写到了meta之外。可以检查一下哈。

**Comment by liaorg** [comment]
是在meta中配置的hideInMenu 属性。
要隐藏一级菜单的做法要修改use-menu-tree.ts源码：
30行这样：
// 隐藏一级菜单
if (element.meta?.hideInMenu === true) {
  return null;
}
改完才有效果
