### ISSUE TITLE
代码依赖存在安全隐患

### ISSUE THREAD

**Issue by liaorg** [arco-design/arco-design-pro-vue#176]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.10
- **Browser:** chrome105.0.0.0
![image](https://user-images.githubusercontent.com/7478660/189871674-22f8507e-2d66-4463-89af-ad2c31266b6a.png)

## What is expected?
能够解决这些隐藏或提供规避方式

## Steps to reproduce
在项目中运行 yarn audit

**Comment by sHow8e** [comment]
@liaorg hi 这部分提示有风险的依赖大部分是多层级依赖造成的。可以自行先进行更新升级。后续我这边也会做一下更新。3q
