### ISSUE TITLE
通过arco-cli 安装的项目，一些包的依赖如何更新

### ISSUE THREAD

**Issue by liaorg** [arco-design/arco-design-pro-vue#179]
![升级](https://user-images.githubusercontent.com/7478660/191486104-04f114fc-699b-47eb-802b-9adff568871e.png)
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.11
- **Browser:** chrome105.0.0.0

## What is expected?
黄色和绿色的依赖已经升级了。就是标红的依赖不知道可不可以升级，升级是否会导致项目不能用？
希望可以升级标红的依赖

## Steps to reproduce
yarn outdated

**Comment by sHow8e** [comment]
@liaorg hi 后续我会对相关依赖进行升级。感谢建议哈。如果有意愿自己也可以自行进行依赖更新，不过可能会有出乎意料的问题哈。
