### ISSUE TITLE
安装依赖时错误

### ISSUE THREAD

**Issue by FlameMida** [arco-design/arco-design-pro-vue#180]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.5.11
- **浏览器版本:** chrome105.0.0.0

用npm安装就提示这个
```log
789 error gifsicle@5.2.0 postinstall: `node lib/install.js`
789 error Exit status 1
790 error Failed at the gifsicle@5.2.0 postinstall script.
790 error This is probably not a problem with npm. There is likely additional logging output above.
```

用yarn 2 就提示
```log
➤ YN0016: │ bin-wrapper@npm:bin-wrapper-china: Registry failed to return tag "bin-wrapper-china"
➤ YN0000: └ Completed in 8s 166ms
➤ YN0000: Failed with errors in 8s 170ms
```

**Comment by sHow8e** [comment]
@FlameMida hi 可以参考一下 https://github.com/arco-design/arco-design-pro-vue/issues/56
