### ISSUE TITLE
动态路由的时候能否自定义 component:  指定的页面？

### ISSUE THREAD

**Issue by lgcrr** [arco-design/arco-design-pro-vue#183]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.11
- **Browser:** chrome98.0.4758.82

## What is expected?
希望后端接口 返回 这个页面 框架自动解析 component: 'views/dashboard/workplace/index.vue',

**Comment by TenMoons** [comment]
> 不是动态注册[#147 (comment)](https://github.com/arco-design/arco-design-pro-vue/issues/147#issuecomment-1193792337) 路由都是前端控制的

那么从服务端拉取菜单过来，如何注册这些路由？必须由前端在`routes/modules`文件夹下都配置好？

**Comment by Loongphy** [comment]
是的，需要前端注册好，然后通过路由meta信息中的roles进行拦截https://github.com/arco-design/arco-design-pro-vue/blob/5530726c8c3279a6a163619381287dcaf9fae826/arco-design-pro-vite/src/hooks/permission.ts#L7-L13

**Comment by TenMoons** [comment]
你好，邮件我已收到。

**Comment by wind959** [comment]
如果前端配置好，不能动态配置，那还叫动态路由？

**Comment by featue** [comment]
。。。。这咋办呢？必须在routes/xxx.ts中写死出来？不能直接从服务器端调用？
