### ISSUE TITLE
table组件的展开行数据如何渲染

### ISSUE THREAD

**Issue by ynkingstar** [arco-design/arco-design-pro-vue#184]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What problem does this feature solve?
展开行数据，需要渲染一个类似商品SKU的数据格式

## What are the similar cases of this feature
expandedRowRender: (record) => {
        if(record.key==='3'){
          return `My Name is ${record.name}`
        }
      }

**Comment by Loongphy** [comment]
组件使用可以到 [arco-design-vue](https://github.com/arco-design/arco-design-vue) 提issue
相关解决可以参考 https://github.com/arco-design/arco-design-vue/issues/1155
