### ISSUE TITLE
表格多选的时候如何获取整行数据

### ISSUE THREAD

**Issue by GGB321** [arco-design/arco-design-pro-vue#185]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
表格如何获取整行数据

## What problem does this feature solve?
表格如何获取整行数据

**Comment by sHow8e** [comment]
@GGB321 这个应该是组件使用和Vue知识点的问题吧。你可以参看arco组件库的文档。表格每一行都是由传入的数据渲染出来的，获取的话可以表格组件有相应的插槽属性。
