### ISSUE TITLE
能够将 Vite 升级到3.0吗

### ISSUE THREAD

**Issue by WilsonXinxin** [arco-design/arco-design-pro-vue#186]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
希望将 Vite 升级到3.0

## What problem does this feature solve?
希望将 Vite 升级到3.0

**Comment by Loongphy** [comment]
自己直接升就行了，`globEager` 3.0 废弃，修改 `src/router/routes/index.ts` 
```
const modules = import.meta.glob('./modules/*.ts', { eager: true })
const externalModules = import.meta.glob('./externalModules/*.ts', { eager: true })
```

**Comment by WilsonXinxin** [comment]
> 自己直接升就行了，`globEager` 3.0 废弃，修改 `src/router/routes/index.ts`
> 
> ```
> const modules = import.meta.glob('./modules/*.ts', { eager: true })
> const externalModules = import.meta.glob('./externalModules/*.ts', { eager: true })
> ```

已经升级了  谢谢
