### ISSUE TITLE
yarn.lock 里面包含 http://bnpm.byted.org/ 这个下载地址造成无法更新

### ISSUE THREAD

**Issue by deluxebear** [arco-design/arco-design-pro-vue#188]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.12
- **Browser:** chrome106.0.0.0

**Comment by sHow8e** [comment]
@deluxebear 我本周做一下调整哈。

**Comment by sHow8e** [comment]
@deluxebear  done [v2.5.13](https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.5.13)
