### ISSUE TITLE
路由版本导致的TS类型报错

### ISSUE THREAD

**Issue by HavocZhang** [arco-design/arco-design-pro-vue#192]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.13
- **Browser:** chrome106.0.0.0

## What is expected?
当"vue-router": "^4.0.14"的时候是没有类型报错的，但是升级vue-router之后会报错，超过4.0.14就报错

## Steps to reproduce
src/router/index.ts:26:5 - error TS2322: Type 'RouteRecordNormalized | AppRouteRecordRaw | { path: string; name: string; component: () => Promise<typeof import("*.vue")>; }' is not assignable to type 'RouteRecordRaw'.
  Type 'AppRouteRecordRaw' is not assignable to type 'RouteRecordRaw'.
    Type 'AppRouteRecordRaw' is not assignable to type 'RouteRecordRedirect'.
      Types of property 'redirect' are incompatible.
        Type 'string | undefined' is not assignable to type 'RouteRecordRedirectOption'.
          Type 'undefined' is not assignable to type 'RouteRecordRedirectOption'.       

26     ...appRoutes,
       ~~~~~~~~~~~~

src/router/index.ts:27:5 - error TS2322: Type 'AppRouteRecordRaw' is not assignable to type 'RouteRecordRaw'.

27     REDIRECT_MAIN,
       ~~~~~~~~~~~~~

src/router/index.ts:28:5 - error TS2322: Type 'RouteRecordNormalized | AppRouteRecordRaw | { path: string; name: string; component: () => Promise<typeof import("*.vue")>; }' is not assignable to type 'RouteRecordRaw'.

28     NOT_FOUND_ROUTE,
       ~~~~~~~~~~~~~~~

<!--- Disclaimer: Submitting offensive issues will result in being blocked from arco-design organization. -->
<!-- generated by arco-issue. DO NOT REMOVE -->

**Comment by sHow8e** [comment]
@HavocZhang 版本原因导致的TS报错问题。可以本地先进行处理哈。后续如果有相关的依赖升级会进行处理。3q

**Comment by GENERALTUNE** [comment]
遇到同样问题 能说下如何处理吗

(alias) const REDIRECT_MAIN: AppRouteRecordRaw
import REDIRECT_MAIN
Type 'AppRouteRecordRaw' is not assignable to type 'RouteRecordRaw'.ts(2322)
No quick fixes available

**Comment by Aurorxa** [comment]
> 遇到同样问题 能说下如何处理吗
> 
> (alias) const REDIRECT_MAIN: AppRouteRecordRaw import REDIRECT_MAIN Type 'AppRouteRecordRaw' is not assignable to type 'RouteRecordRaw'.ts(2322) No quick fixes available

"@arco-design/web-vue": "2.37.4"

**Comment by GENERALTUNE** [comment]
@Aurorxa  你啥意思 ？？？

**Comment by Aurorxa** [comment]
> @Aurorxa 你啥意思 ？？？

你将版本锁定一下，不然会报错
