### ISSUE TITLE
路由菜单隐藏

### ISSUE THREAD

**Issue by ZhangTomLiang** [arco-design/arco-design-pro-vue#193]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.11
- **Framework version:** Vue
- **Browser:** chrome106.0.0.0

## Steps to reproduce
path: '/exception',
  name: 'exception',
  component: DEFAULT_LAYOUT,
  meta: {
    locale: 'menu.exception',
    requiresAuth: false,
    hideInMenu: true,
    icon: 'icon-exclamation-circle',
    order: 2,
  },

![Snipaste_2022-10-25_20-24-34](https://user-images.githubusercontent.com/18275926/197772274-ccb575ac-c474-4bf7-91a9-87154808a40e.png)
![Snipaste_2022-10-25_20-24-55](https://user-images.githubusercontent.com/18275926/197772281-1a240d19-7694-4cbc-99ba-84ef07f2cad0.png)

**Comment by sHow8e** [comment]
@ZhangTomLiang 其实是子级和父级互斥了。因为子级没有隐藏的判断被前置了。https://github.com/arco-design/arco-design-pro-vue/blob/5530726c8c3279a6a163619381287dcaf9fae826/arco-design-pro-vite/src/components/menu/use-menu-tree.ts#L44
项目内可以先自行调整一下。 我后续看看处理一下。
