### ISSUE TITLE
打包时出现Type '() => void' is not assignable to type 'MouseEvent'

### ISSUE THREAD

**Issue by thckbuibuibui** [arco-design/arco-design-pro-vue#194]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.13
- **Browser:** chrome105.0.0.0

## What is expected?
Type '() => void' is not assignable to type 'MouseEvent'

**Comment by sHow8e** [comment]
@thckbuibuibui hihi 两种方法。
1、按照类型提示进行修改。
2、关闭vue-tsc检查。(不推荐)

**Comment by thckbuibuibui** [comment]
> @thckbuibuibui hihi 两种方法。 1、按照类型提示进行修改。 2、关闭vue-tsc检查。(不推荐)

 报错的内容是模版里自带的组件 例如src/components/message-box/list.vue  <div class="item-wrap" @click="onItemClick(item)">

**Comment by thckbuibuibui** [comment]
@sHow8e 
报错的内容是模版里自带的组件 例如src/components/message-box/list.vue <div class="item-wrap" @click="onItemClick(item)">

**Comment by Chanzhaoyu** [comment]
@sHow8e 
应该不是代码问题，我也发现了

@thckbuibuibui 
应该是更新了 vue 版本的问题，看下这个 issuse 能不能解决你的问题

https://github.com/vuejs/core/pull/6855

**Comment by Chanzhaoyu** [comment]
> @sHow8e 应该不是代码问题，我也发现了
> 
> @thckbuibuibui 应该是更新了 vue 版本的问题，看下这个 issuse 能不能解决你的问题
> 
> [vuejs/core#6855](https://github.com/vuejs/core/pull/6855)

项目内安装 "@types/node": "18.7.16" 锁定版本可解决这个问题
