### ISSUE TITLE
Textarea 不能设置行数

### ISSUE THREAD

**Issue by G-Akiraka** [arco-design/arco-design-pro-vue#202]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.13
- **Framework version:** vue
- **Browser:** chrome107.0.0.0

## Steps to reproduce
为什么不能像其他的ui那样，文本域可以设置个指定行数，因为有的时候需要一个指定多行出来满足效果

**Comment by ZhangTomLiang** [comment]
<template>
  <a-textarea default-value="This is the contents of the textarea. This is the contents of the textarea. This is the contents of the textarea." auto-size />
  <a-textarea default-value="This is the contents of the textarea. This is the contents of the textarea. This is the contents of the textarea." :auto-size="{
    minRows:2,
    maxRows:5
  }" style="margin-top: 20px"/>
</template>

这个例子官网上有

**Comment by ZhangTomLiang** [comment]
<template>
  <a-textarea default-value="This is the contents of the textarea. This is the contents of the textarea. This is the contents of the textarea." auto-size />
  <a-textarea default-value="This is the contents of the textarea. This is the contents of the textarea. This is the contents of the textarea." :auto-size="{
    minRows:2,
    maxRows:5
  }" style="margin-top: 20px"/>
</template>

**Comment by ZhangTomLiang** [comment]
:auto-size="{
    minRows:2,
    maxRows:5
  }"

**Comment by sHow8e** [comment]
@ZhangTomLiang 可以先查看组件库版本和组件使用文档。确保引入及使用方式正确。如果有问题可以组件库提issue呀。
