### ISSUE TITLE
Uncaught SyntaxError:Export 'e'is not defined in module

### ISSUE THREAD

**Issue by JasonUnion** [arco-design/arco-design-pro-vue#203]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.13
- **Browser:** chrome107.0.0.0

## Steps to reproduce
根据官网文档进行初始化，执行yarn dev之后，没有报错，但是页面一片空白，控制台显示Uncaught SyntaxError:Export 'e'is not defined in module，是缺少了哪个依赖？

**Comment by sHow8e** [comment]
@JasonUnion 先试试删除node_modules后重装一下依赖。同时提供的信息不足，我这边没法帮你定位问题呀。
