### ISSUE TITLE
请问一下能完善一下菜单后端请求的文档嘛，前端技术有限，看不懂

### ISSUE THREAD

**Issue by XiaodengziBoy** [arco-design/arco-design-pro-vue#205]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
无菜单加载，后端提供接口数据正常

## What problem does this feature solve?
无菜单加载，后端提供接口数据正常

**Comment by sHow8e** [comment]
@XiaodengziBoy 项目有内置相关mock菜单的接口。[文档](https://arco.design/vue/docs/pro/start)https://github.com/arco-design/arco-design-pro-vue/blob/5530726c8c3279a6a163619381287dcaf9fae826/arco-design-pro-vite/src/mock/user.ts#L71

**Comment by XiaodengziBoy** [comment]
麻烦了，我先看看，问问公司前端看能理解不，总感觉不是mock的问题和后端接口的问题，我数据对比的/src/config/setting.json的serverMenu对应的结构

**Comment by XiaodengziBoy** [comment]
![image](https://user-images.githubusercontent.com/30485698/201859024-216efda2-534e-4bce-9db5-5990701b3c6b.png)

缩减版有这个问题，完整版可以正常显示
