### ISSUE TITLE
反向代理为什么设置不成功？

### ISSUE THREAD

**Issue by qiushuaichang** [arco-design/arco-design-pro-vue#206]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
能给个详细的设置么？

## What problem does this feature solve?
在config/vite.config.dev.ts中添加反向代理，不成功

**Comment by qiushuaichang** [comment]
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/33740060/201482950-e2c065a2-3d29-47c2-a1ac-a17b4b196bbb.png">
<img width="555" alt="image" src="https://user-images.githubusercontent.com/33740060/201482960-3ffbf831-680c-43fa-b797-6e8a35d569ec.png">

**Comment by qiushuaichang** [comment]
设置好之后，重启了服务

**Comment by sHow8e** [comment]
@qiushuaichang 看看是否这行有影响？先确认接口是否可用。再检查接口地址和端口。https://github.com/arco-design/arco-design-pro-vue/blob/5530726c8c3279a6a163619381287dcaf9fae826/arco-design-pro-vite/src/api/interceptor.ts#L15
