### ISSUE TITLE
动态路由传参问题，tab显示不正确

### ISSUE THREAD

**Issue by ZhangTomLiang** [arco-design/arco-design-pro-vue#208]
![Snipaste_2022-11-15_11-45-55](https://user-images.githubusercontent.com/18275926/201821550-41037425-d408-40af-bc35-af3d7fe1fbff.png)
![Snipaste_2022-11-15_11-46-41](https://user-images.githubusercontent.com/18275926/201821652-a86ffd1f-d050-4258-8b56-75eb644f7988.png)
![Snipaste_2022-11-15_11-48-00](https://user-images.githubusercontent.com/18275926/201821819-fb7ac15a-afa9-4731-923a-2e94c8a46d50.png)
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.13
- **Browser:** chrome107.0.0.0

## What is expected?
请教一下，如何去支持动态路由的配置，可以指导一下如何去修改这块的逻辑，目前form是在一个三级菜单下，也就是详情页面，编辑页面也是公用这一套逻辑

## Steps to reproduce
这边有一个页面配置的路由为form, 比如router.push(path: '/form',  query:{action: view})去查看，可能还有编辑router.push(path: '/form',  query:{action: edit})，这时候会生成两个页签，但是一旦刷新，页签消失，同时页签所展示的PAGE_LAYOUT为空白，不管是刷新还是返回上一级， 都会有此问题。

**Comment by ZhangTomLiang** [comment]
从页签编辑决策点击决策列表 以及编辑决策router.back(-1)回到决策列表页PAGE_LAYOUT的内容都为空，正常列表是有的

[
![Snipaste_2022-11-15_11-48-40](https://user-images.githubusercontent.com/18275926/201821938-da2553a0-dbbf-434f-9272-9550ea5769f9.png)
](url)

**Comment by sHow8e** [comment]
@ZhangTomLiang 不了解你内部怎么写的。你可以先看一下刷新后上一层级的router-view是否加载。或者本层级是否有router-view。

**Comment by ZhangTomLiang** [comment]
已解决
