### ISSUE TITLE
单级路由的父级组件展示

### ISSUE THREAD

**Issue by 6dy** [arco-design/arco-design-pro-vue#209]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 现有案例
当只有单级路由时，组件的内容无法展示

## 预期解决问题
当只有单级路由时，展示组件内容

**Comment by 6dy** [comment]
<img width="1323" alt="image" src="https://user-images.githubusercontent.com/39676628/201894282-4125af02-d641-4a9f-baf1-60e405eedd95.png">

**Comment by sHow8e** [comment]
@6dy hi 你看看你路由是否配置正确。或者你是否漏了router-view这个容器。

**Comment by wenner** [comment]
这应该本身就是个问题，因为所有路由都设置了一个 DEFAULT_LAYOUT, 而一级路由如果不设置这个， 那么就没有route_view，自然都不显示了

**Comment by icooooler** [comment]
确实，现在如果设置纯一级菜单，那就没法在路由中设置compenents为DEFAULTLAYOUT，直接导致菜单栏、导航栏这些都没了，很不灵活

**Comment by a1029382825** [comment]
这个问题应该可以在生成menu阶段解决，给路由配置上加个属性，当仅有一个子路由时是否提升到上一级，然后生成菜单的时候根据这个判断就可以了

**Comment by mojerro** [comment]
@sHow8e 这个有计划优化一下吗

**Comment by mojerro** [comment]
补充一下，发现只需要在父级路由`meta`参数中设置`hideChildrenInMenu: true,`即可实现此功能

**Comment by lzp0301** [comment]
> 补充一下，发现只需要在父级路由`meta`参数中设置`hideChildrenInMenu: true,`即可实现此功能

是不是父级路由还得设置个 redirect:xxxx 才能重定向到子路由，现在设置完之后父路由不高亮了

**Comment by mojerro** [comment]
这块需要修改一下官方的路由解析逻辑，因为pro的所有代码其实都是在业务侧，没有封装新的库，所以直接调试修改一下就行了
