### ISSUE TITLE
Found a 'popup' attribute. If you are testing the popup API, you must enable Experimental Web Platform Features. If not, note that custom attributes must start with 'data-': <URL>. 

### ISSUE THREAD

**Issue by ikilobyte** [arco-design/arco-design-pro-vue#210]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.3.3
- **Browser:** chrome107.0.0.0

## Steps to reproduce
menu菜单组件chrome浏览器下有报错

**Comment by sHow8e** [comment]
@ikilobyte  hi 试试升级组件库版本
