### ISSUE TITLE
可否提供js选项

### ISSUE THREAD

**Issue by lwxk** [arco-design/arco-design-pro-vue#212]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
可否提供js选项

## What problem does this feature solve?
后端开发人员，实在不想重新定义2套对象

**Comment by Loongphy** [comment]
Vue3 + TS 是标配，不想用可以使用 any

**Comment by 107295472** [comment]
后端和ts是标配
