### ISSUE TITLE
Mock 丢失responseType，导致文件下载乱码

### ISSUE THREAD

**Issue by Nash-x9** [arco-design/arco-design-pro-vue#213]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.14
- **Browser:** chrome107.0.0.0

## What is expected?
https://github.com/PanJiaChen/vue-element-admin/pull/1779

**Comment by sHow8e** [comment]
@Nash-x9 mock就是模拟数据。可以去调用真实接口进行下载。
