### ISSUE TITLE
在菜单特别多的情况下，可否支持菜单上左分割

### ISSUE THREAD

**Issue by seantech2000** [arco-design/arco-design-pro-vue#214]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
一级菜单展示在顶部，二级及以下菜单展示在左侧

## What problem does this feature solve?
在一级二级菜单过多，仅仅左侧菜单展示不够友好的情况下

**Comment by 107295472** [comment]
参考mineadmin

**Comment by sHow8e** [comment]
@seantech2000 hi 这种功能需要自行去进行设计和处理哈。
