### ISSUE TITLE
dev 没有问题， build 报错  ，那个配置是啥？

### ISSUE THREAD

**Issue by icetech233** [arco-design/arco-design-pro-vue#215]
C:\webcode\arcod\arco-pro>npm run build

> arco-design-pro-vue@1.0.0 build
> vue-tsc --noEmit && vite build --config ./config/vite.config.prod.ts

src/router/index.ts:26:5 - error TS2322: Type 'RouteRecordNormalized | AppRouteRecordRaw | { path: string; name: string; component: () => Promise<typeof import("C:/webcode/arcod/arco-pro/src/views/not-found/index.vue")>; }' is not assignable to type 'RouteRecordRaw'.
  Type 'AppRouteRecordRaw' is not assignable to type 'RouteRecordRaw'.
    Type 'AppRouteRecordRaw' is not assignable to type 'RouteRecordRedirect'.
      Types of property 'redirect' are incompatible.
        Type 'string | undefined' is not assignable to type 'RouteRecordRedirectOption'.
          Type 'undefined' is not assignable to type 'RouteRecordRedirectOption'.

26     ...appRoutes,
       ~~~~~~~~~~~~

src/router/index.ts:27:5 - error TS2322: Type 'AppRouteRecordRaw' is not assignable to type 'RouteRecordRaw'.

27     REDIRECT_MAIN,
       ~~~~~~~~~~~~~

src/router/index.ts:28:5 - error TS2322: Type 'RouteRecordNormalized | AppRouteRecordRaw | { path: string; name: string; component: () => Promise<typeof import("C:/webcode/arcod/arco-pro/src/views/not-found/index.vue")>; }' is not assignable to type 'RouteRecordRaw'.

28     NOT_FOUND_ROUTE,
       ~~~~~~~~~~~~~~~


Found 3 errors in the same file, starting at: src/router/index.ts:26

**Comment by icetech233** [comment]
能run dev

**Comment by jiabochao** [comment]
可以参考这个：https://github.com/arco-design/arco-design-pro/issues/94#issuecomment-1336352539

**Comment by sHow8e** [comment]
@icetech233 hihi [常见问题](https://arco.design/vue/docs/pro/faq) 可以看看构建TS类型报错。
