### ISSUE TITLE
如何去除界面最上方的全局加载进度条

### ISSUE THREAD

**Issue by jiabochao** [arco-design/arco-design-pro-vue#219]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
能否自定义更加美观的界面中央的加载动画。类似ant-design-pro的效果：https://preview.pro.ant.design/dashboard/analysis

## What problem does this feature solve?
本地化应用不走网络，加载很快，不希望给用户加载的感觉

**Comment by sHow8e** [comment]
@jiabochao  hi 可以禁用哈。https://github.com/arco-design/arco-design-pro-vue/blob/d85d0d5efdad1455d559fa5bf9664750787aea5b/arco-design-pro-vite/src/router/guard/userLoginInfo.ts#L9 我们关注点是加载各个子单元。所以对于页面级别的加载统一使用了进度条。如果需要可以自行添加哈。

**Comment by jiabochao** [comment]
解决
