### ISSUE TITLE
火狐浏览器下，左侧菜单栏收起时，样式错乱

### ISSUE THREAD

**Issue by gaoopop** [arco-design/arco-design-pro-vue#22]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.2.2
- **System:** win10
- **Browser:** FireFox 97.0(64位)
- **Reproduction Link:** http://vue-pro.arco.design/dashboard/workplace

## What is expected?
左侧菜单栏收起时，样式正常，而不是图标和文字重叠一起了

**Comment by oaktreecode** [comment]
目前不支持响应式？ 我看和react版本差别很大，不管是样式和体验上。希望继续改善一下。

**Comment by sHow8e** [comment]
@gaojinsheng 能否提供一下图片或者更加详细的信息。我这边在火狐里表现是正常的。

**Comment by sHow8e** [comment]
@oaktreecode 感谢建议，这个会持续迭代下去的哈。如果有特别影响到使用的可以单独提个issue哈。

**Comment by gaojinsheng** [comment]
@sHow8e Win10  FireFox 97.0(64位)

![微信图片_20220218101737](https://user-images.githubusercontent.com/9443321/154605411-79c83201-ff9b-42d7-b79c-2f12b3305fc9.png)

**Comment by sHow8e** [comment]
@gaoopop 感谢反馈哈。预览站点已经重新部署了新包。3q
