### ISSUE TITLE
多级路由页面缓存, 容器内部已添加name

### ISSUE THREAD

**Issue by ZhangTomLiang** [arco-design/arco-design-pro-vue#221]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.11
- **Browser:** chrome108.0.0.0

## Steps to reproduce
三级菜单，组件内部已添加name， 页面依旧无法缓存

**Comment by pxc180** [comment]
请问你缓存问题弄好了吗

**Comment by ZhangTomLiang** [comment]
弄好了，只不过有点麻烦。

function setupPageGuard(router: Router) {
  router.beforeEach(async (to) => {
    if (to.matched && to.matched.length > 2) {
      to.matched.splice(1, to.matched.length - 2);
    }
    // emit route change
    setRouteEmitter(to);
  });
}

**Comment by pxc180** [comment]
> 弄好了，只不过有点麻烦。
> 
> function setupPageGuard(router: Router) { router.beforeEach(async (to) => { if (to.matched && to.matched.length > 2) { to.matched.splice(1, to.matched.length - 2); } // emit route change setRouteEmitter(to); }); }

这个写法我不太理解，能解释下吗，感谢
