### ISSUE TITLE
关闭tab标签页前增加一个确认关闭的钩子

### ISSUE THREAD

**Issue by Huzhengtao** [arco-design/arco-design-pro-vue#222]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
tab页面中点击关闭标签页前增加一个可自定义是否确认关闭的钩子，用来防止用户误操作丢失编辑数据

**Comment by Huzhengtao** [comment]
现在关闭tab标签和vue-router的onBeforeRouteLeave事件不能正确响应，中断路由跳转，标签依然会被×掉

**Comment by sHow8e** [comment]
@Huzhengtao 这部分功能感觉有点冗余。可以自行添加确认操作哈。3q
