### ISSUE TITLE
在userLoginInfo.ts这个路由守卫中，请求用户信息过于频繁，token过期之后会一直刷新页面造成死循环

### ISSUE THREAD

**Issue by HavocZhang** [arco-design/arco-design-pro-vue#223]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 现有案例
例如在await userStore.info()之前进行判断是否存在用户信息，存在的话就不请求了，但是这也存在一个问题，就是如果设置的是后台路由，那么前端什么时候进行更新

## 预期解决问题
可以提前判断一下用户信息是否获取，然后再进行请求，避免重复请求

**Comment by sHow8e** [comment]
@HavocZhang https://github.com/arco-design/arco-design-pro-vue/blob/d85d0d5efdad1455d559fa5bf9664750787aea5b/arco-design-pro-vite/src/router/guard/userLoginInfo.ts#L12 这行就是判断逻辑呀。你换成你自己的标识就行。
