### ISSUE TITLE
新版打包后访问无法加载js(打包后的index.htm没有引入任何入口js文件), 问题是这个configArcoResolverPlugin插件导致,而正真原因是vite4及以上改插件有问题

### ISSUE THREAD

**Issue by zxiaozhou** [arco-design/arco-design-pro-vue#225]
- [ ✅] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.15
- **Framework version:** vue 
- **Browser:** chrome108.0.0.0

## Steps to reproduce
1. 运行arco init初始化项目
2. 运行npm run build打包
3. 部署ng

## 问题分析
1. 打包后index.html没有引用一个js。不知道这样ng要怎么配置。 打包后index.html应该有引入入口js,在由这个js加载其他(请求ng时)，而这个项目打包后index.html结果为(没有引用任何入口js文件)
<img width="1546" alt="image" src="https://user-images.githubusercontent.com/62740686/208673988-eea102b5-b0c2-4264-89ef-c7927640bbbf.png">

2. 正常的应该在打包后index.html中有js入口文件引用
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/62740686/208677421-5f1398db-379f-411a-ad2e-28061bf2bd5a.png">

3. 问题是这个configArcoResolverPlugin插件导致的，去掉后打包一切正常，ng访问也正常了
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/62740686/208680039-46ed78b7-09be-4417-90cc-e7b9e2b5c9a6.png">

**Comment by sHow8e** [comment]
@zxiaozhou 估计是两者有冲突了。或者尝试把vite降级到3.x也是可以的。

**Comment by zxiaozhou** [comment]
@sHow8e 刚刚查明，vite4以上unplugin-vue-components有问题，降低就正常了

**Comment by sHow8e** [comment]
@zxiaozhou 可能是vite4.x的问题。因为本次更新，我做了依赖的升级。vite升到了4.x。如果是vite的feature导致的，后续估计 unplugin-vue-components 会做相关的兼容处理。目前比较保险的做法是把vite降级到3.x。

**Comment by zxiaozhou** [comment]
@sHow8e 非常感觉，已经降低了，估计是运气好，刚好新创建的项目arco的模板用到最新的vite。我已经在unplugin-vue-components那边提了bug以及最小demo。只能等那边消息了

**Comment by holyrong** [comment]
> @sHow8e 非常感觉，已经降低了，估计是运气好，刚好新创建的项目arco的模板用到最新的vite。我已经在unplugin-vue-components那边提了bug以及最小demo。只能等那边消息了

这个问题到现在好像也没解决吧
