### ISSUE TITLE
Axios与mock冲突导致responseType失效

### ISSUE THREAD

**Issue by caoxiaotong** [arco-design/arco-design-pro-vue#226]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.14
- **Browser:** chrome107.0.0.0

## Steps to reproduce
return axios.get<ArrayBuffer>("/public/code", {
    params: params,
    responseType:'arraybuffer'
  });
已设置responseType但是在axios.interceptors.request.use并不生效，axios.interceptors.response.use返回的里面也不生效。然后在请求拦截器里面手动设置也不生效。 最终在https://github.com/PanJiaChen/vue-element-admin/issues/1466 这个里面也发现类似的问题。
我这边目前的解决办法是吧mock给注释了 就可以正常使用了

**Comment by sHow8e** [comment]
@caoxiaotong 这个好像是mockjs的问题。不过如果你有自己的接口可以替换mockjs。
