### ISSUE TITLE
执行npm run build  后 生成的index.html没有js与css 导致页面空白

### ISSUE THREAD

**Issue by 2011shao** [arco-design/arco-design-pro-vue#227]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.15
- **Framework version:** 最新
- **Browser:** chrome108.0.0.0

## What is expected?
正常访问

## Steps to reproduce
arco init mydemo 
npm install 
npm run build

**Comment by sHow8e** [comment]
@2011shao hi 可以参考一下 这个issue https://github.com/arco-design/arco-design-pro-vue/issues/225

**Comment by sHow8e** [comment]
@2011shao done [v2.6.0](https://github.com/arco-design/arco-design-pro-vue/blob/main/docs/changelog.zh-CN.md)
