### ISSUE TITLE
Setting中的themeColor修改了不能起作用

### ISSUE THREAD

**Issue by superwen** [arco-design/arco-design-pro-vue#229]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.15
- **Browser:** chrome108.0.0.0

## Steps to reproduce
当我在src/config/setting.json中的themeColor从原来的值#165DFF修改为其他颜色时，刷新页面时不起作用。而其他设置项修改后会立即生效。有谁知道这是为啥？

**Comment by sHow8e** [comment]
@superwen hi 这个属性在项目中并未使用。可以结合自己项目进行处理哈。
