### ISSUE TITLE
有预览吗？

### ISSUE THREAD

**Issue by Silentdoer** [arco-design/arco-design-pro-vue#23]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Reproduction Link:** http://github.com/aaa
- **Browser:** firefox92.0
- **Package Name And Version:** arco-design-pro-vue@2.2.2

## What is expected?
能够预览

**Comment by sHow8e** [comment]
@Silentdoer 有的呀。更多可以参见arco官网哈。 [Pro预览](http://vue-pro.arco.design/login)

**Comment by Silentdoer** [comment]
最好是放到redme里，不过这个预览是react还是vue的呢？

**Comment by sHow8e** [comment]
> 最好是放到redme里，不过这个预览是react还是vue的呢？

感谢建议！我给的是vue版本的

**Comment by Silentdoer** [comment]
好的，谢谢
