### ISSUE TITLE
为什么每个页面第一次打开都很慢，有没有什么解决的办法

### ISSUE THREAD

**Issue by fanqie** [arco-design/arco-design-pro-vue#231]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.15
- **Browser:** chrome108.0.0.0

**Comment by sHow8e** [comment]
@fanqie 我这边是没问题的。麻烦提供一下详细描述信息。3q。

**Comment by holyrong** [comment]
![image](https://user-images.githubusercontent.com/8318475/231673232-a464635b-d922-4e0e-a78a-f9f6d71a59e5.png)

每次打开页面都很慢：比如当前是A页面，再打开B页面时，可以马上看到tab增加了B页面，但Layout的Content都还是停留在A页面，快的时候1两秒，慢的时候好几秒。

**Comment by fanqie** [comment]
目测是vite 编译时机问题，的确是打开页面的时候才会发生编译，编译完成后才会进行渲染，这个问题只发发生在修改后的第一次，打包部署后，没有此现象
