### ISSUE TITLE
menuCollapse配置不生效

### ISSUE THREAD

**Issue by jiabochao** [arco-design/arco-design-pro-vue#232]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.15
- **Browser:** chrome108.0.0.0

## Steps to reproduce

```
src / config / settings.json 
```

将 `"menuCollapse": true` 设置为 `true` 不能始终折叠菜单

**Comment by sHow8e** [comment]
@jiabochao hi 感谢反馈哈。这确实是个bug。后续修改一下。如果可以欢迎提Pr呀！

**Comment by jiabochao** [comment]
PR~😍😍😍
看了一下，刚进入首页时菜单是折叠的，但是由于 `layout-sider` 触发了一次响应事件，把 `menuCollapse` 又设置回了 `false`。

```
<a-layout-sider
    v-if="renderMenu"
    v-show="!hideMenu"
    class="layout-sider"
    breakpoint="xl"
    :collapsed="collapsed"
    :collapsible="true"
    :width="menuWidth"
    :style="{ paddingTop: navbar ? '60px' : '' }"
    :hide-trigger="true"
    @collapse="setCollapsed"
  >
...

const setCollapsed = (val: boolean) => {
  appStore.updateSettings({ menuCollapse: val });
};
```

所以在`setCollapsed`里判断一下如果是响应式触发并且原始`menuCollapse`配置为`true`时就阻止设置值可行。

```
const setCollapsed = (val: boolean, type: string) => {
  if (
    type === 'responsive' &&
    defaultSettings.menuCollapse &&
    appStore.menuCollapse
  ) {
    return;
  }
  appStore.updateSettings({ menuCollapse: val });
};
```

但是最好是一进首页不触发响应事件，把`layout-sider`的`breakpoint`设置为`xs`也好使，但是页面响应就有问题了。

**Comment by sHow8e** [comment]
done [v2.6.1](https://github.com/arco-design/arco-design-pro-vue/blob/main/docs/changelog.zh-CN.md)
