### ISSUE TITLE
暗黑模式下登录界面部分文字看不清

### ISSUE THREAD

**Issue by jiabochao** [arco-design/arco-design-pro-vue#233]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.15
- **Browser:** chrome108.0.0.0
- **Reproduction Link:** https://vue-pro.arco.design/login

## Steps to reproduce
1. 登录系统
2. 切换暗黑模式
3. 退出登录回到登录界面
![企业微信截图_16721916443133](https://user-images.githubusercontent.com/16523012/209744085-44e51539-05a5-4860-9e71-7b267373f5d7.png)

**Comment by sHow8e** [comment]
@jiabochao hi 可以根据需要自己修改一下变量色值哈。3q
