### ISSUE TITLE
添加 vue 代码，提交commit失败

### ISSUE THREAD

**Issue by lusson-luo** [arco-design/arco-design-pro-vue#235]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.15
- **Browser:** chrome105.0.0.0

## Extra info
错误信息
/Users/xxx/workspace/hello-arco-pro/everythingPaaSStoreFront/src/views/dashboard/users/index. vue: When linting something other than CSS, you should install an appropriate syntax, e.g.  "postcss-html", and use the "customSyntax" option
/Users/xxx/workspace/hello-arco-pro/everythingPaaSStoreFront/src/views/inspection/inspection/index. vue: When linting something other than CSS, you should install an appropriate syntax, e.g.  "postcss-html", and use the "customSyntax" option

src/views/dashboard/users/index.vue
90:20  ✖  Unknown word  CssSyntaxError

src/views/inspection/inspection/index.vue
6:12  ✖  Unknown word  CssSyntaxError

2 problems (2 errors, 0 warnings)

我的解决办法，网上查询得知错误是 eslint 不能识别该语法，是因为 eslint 14 之后，需要下载插件识别 vue
npm install --save-dev postcss-html stylelint-config-recommended-vue
stylelint 配置文件添加extends，'stylelint-config-recommended-vue',
<img width="520" alt="image" src="https://user-images.githubusercontent.com/19859400/209823380-5df6f69f-d143-476d-a69c-f901328e237d.png">

## What is expected?
应该提交成功

## Steps to reproduce
只要添加一个 vue 文件，提交就会失败

**Comment by sHow8e** [comment]
@lusson-luo 这部分问题是之前升级依赖导致的。了解了一下相关，按照如上提供的方式进行了处理。3q。[v2.6.0](https://github.com/arco-design/arco-design-pro-vue/blob/main/docs/changelog.zh-CN.md）
