### ISSUE TITLE
增加electron打包配置

### ISSUE THREAD

**Issue by a1029382825** [arco-design/arco-design-pro-vue#237]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
是否可以增加打包为electron应用的配置？

## What problem does this feature solve?
是否可以增加打包为electron应用的配置？

**Comment by sHow8e** [comment]
@a1029382825 hi 目前无相关计划。可以参阅文档自行处理哈。3q
