### ISSUE TITLE
build bug index.html 里面不会引用 js 文件

### ISSUE THREAD

**Issue by hsbbhjdks** [arco-design/arco-design-pro-vue#238]
- [  ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.15
- **Browser:** chrome108.0.0.0

yarn build 构建时，生成的 index.html 里面不会引用 js 文件，如图：
![aa](https://user-images.githubusercontent.com/121224009/210934839-ac17a312-ff34-400c-905c-7eea6738a4ed.png)

**Comment by Charles7c** [comment]
hi 可以参考一下 这个issue https://github.com/arco-design/arco-design-pro-vue/issues/225

**Comment by sHow8e** [comment]
@hsbbhjdks done [v2.6.0](https://github.com/arco-design/arco-design-pro-vue/blob/main/docs/changelog.zh-CN.md)
