### ISSUE TITLE
a-tree default-checked-keys and default-expanded-keys property not work.

### ISSUE THREAD

**Issue by imtiger** [arco-design/arco-design-pro-vue#239]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.15
- **Framework version:** 3.2.40
- **Browser:** chrome108.0.0.0

## Steps to reproduce
<a-tree
              v-if="originTreeData.length>0"
              v-model:checked-keys="checkedKeys"
              v-model:expanded-keys="expandedKeys"
              :data="treeData"
              :multiple="multiple"
              :default-checked-keys="**defaultCheckedKeys**"
              :default-expanded-keys="**defaultExpandedKeys**"
              :checked-strategy="'parent'"
              :auto-expand-parent="true"
              :default-expand-checked="true"
              :checkable="checkable"
      >

export default {
  name: 'ThirdCategory',
  props: {
    type: String,
    showConfirm: Boolean,
    checkedIds: Array
  },
  data() {
    return {
      checkedKeys: [],
      expandedKeys: [],
      multiple: true,
      checkable: true,
      categoryMap: {},
      originTreeData: [],
      searchKey: '',
      defaultCheckedKeys:[5947,5948,5945],
      defaultExpandedKeys:[5947,5948,5945]
    }
  }
}

**Comment by sHow8e** [comment]
@imtiger Hi. For component usage, you can go to [arco design vue](https://github.com/arco-design/arco-design-vue/issues) to ask questions. thanks.
