### ISSUE TITLE
组件库项目 生成时 显示构建失败

### ISSUE THREAD

**Issue by bqzhaoyan** [arco-design/arco-design-pro-vue#240]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.15
- **Browser:** chrome86.0.4240.198

## Steps to reproduce
F:\vue3>arco init lib-project

        ___                    ____            _
       /   |  ______________  / __ \___  _____(_)___ _____
      / /| | / ___/ ___/ __ \/ / / / _ \/ ___/ / __ `/ __ \
     / ___ |/ /  / /__/ /_/ / /_/ /  __(__  ) / /_/ / / / /
    /_/  |_/_/   \___/\____/_____/\___/____/_/\__, /_/ /_/
                                             /____/

                                                v1.27.4

? 请选择你希望使用的技术栈 Vue
? 请选择所要创建项目的类型 组件库
? 请输入 NPM 包名 common-components
? 请输入物料标题 公共组件
? 请描述你的物料 公共组件
? 请输入 NPM 包版本号 0.1.0
? 请选择物料的关键词（可多选） 数据展示, 信息展示, 表格, 筛选, 弹出框, 编辑器, [自定义输入]
? 输入新值，多个值之间可以使用逗号隔开

正在初始化项目于 F:\vue3\lib-project
√ 获取项目模板成功
√ 模板内容拷贝完成
√ 模板内容适配完成
√ 项目依赖安装完成
‼ 项目构建失败
Command executed failed: npm run build
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
"build.lib.formats" will be ignored because "build.rollupOptions.output" is already an array format
"build.lib.formats" will be ignored because "build.rollupOptions.output" is already an array format
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
"build.lib.formats" will be ignored because "build.rollupOptions.output" is already an array format
You must supply options.input to rollup
F:\vue3\lib-project\node_modules\rollup\dist\shared\rollup.js:23039
            throw new Error('You must supply options.input to rollup');
                  ^

Error: You must supply options.input to rollup
    at Graph.generateModuleGraph (F:\vue3\lib-project\node_modules\rollup\dist\shared\rollup.js:23039:19)
    at async Graph.build (F:\vue3\lib-project\node_modules\rollup\dist\shared\rollup.js:22982:9)
    at async F:\vue3\lib-project\node_modules\rollup\dist\shared\rollup.js:23680:13
    at async catchUnfinishedHookActions (F:\vue3\lib-project\node_modules\rollup\dist\shared\rollup.js:23162:20)
    at async rollupInternal (F:\vue3\lib-project\node_modules\rollup\dist\shared\rollup.js:23677:5)
    at async doBuild (F:\vue3\lib-project\node_modules\vite\dist\node\chunks\dep-689425f3.js:41710:24)
    at async build (F:\vue3\lib-project\node_modules\vite\dist\node\chunks\dep-689425f3.js:41552:16)

---------------------------------------------------------------------------------------
 项目初始化完成！
 阅读 README.md 获取快速指引。执行如下命令，启动项目
   $ cd lib-project
   $ npm run dev
---------------------------------------------------------------------------------------

**Comment by sHow8e** [comment]
@bqzhaoyan hi 物料问题往 [arco-cli](https://github.com/arco-design/arco-cli/issues) 反馈哈。或者进入飞书群提问。3q
