### ISSUE TITLE
添加vscode插件提示

### ISSUE THREAD

**Issue by Last-Order-Wsk** [arco-design/arco-design-pro-vue#246]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 现有案例
类似于Element UI Snippets的插件，在编写时能够友好提示

## 预期解决问题
代码提示

**Comment by sHow8e** [comment]
@Last-Order-Wsk  相关插件正在开发中哈。可以关注一下动态呀。
