### ISSUE TITLE
打包后general-card这个class不生效

### ISSUE THREAD

**Issue by sohenk** [arco-design/arco-design-pro-vue#249]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.1
- **Browser:** chrome108.0.0.0

## Steps to reproduce
npm run build 之后 general-card 里的border还是出来了

**Comment by sHow8e** [comment]
@sohenk 感觉是vite打包插件的问题。你可以注释https://github.com/arco-design/arco-design-pro-vue/blob/fa4847bd77afd870e1771ebd294a229a2cf3c664/arco-design-pro-vite/config/vite.config.prod.ts#L15 https://github.com/arco-design/arco-design-pro-vue/blob/fa4847bd77afd870e1771ebd294a229a2cf3c664/arco-design-pro-vite/config/vite.config.prod.ts#L16 这两行打包试试。
