### ISSUE TITLE
路由的多级菜单是否有问题？

### ISSUE THREAD

**Issue by bytrix** [arco-design/arco-design-pro-vue#25]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.2.2
- **System:** MacOS
- **Browser:** chrome98.0.4758.102
- **Reproduction Link:** https://gitee.com/bytrix/arco-pro-menu-bug

## What is expected?
要正常显示多级子菜单

## Steps to reproduce
仪表盘-工作台中有两个demo子菜单，似乎有点不太正常（二级菜单不能收缩、三级菜单不需要显示展开图标）

**Comment by sHow8e** [comment]
@bytrix 目前的Pro里的菜单只是一个示例代码（代码的注释有说明）。需要什么样的子菜单和子节点需要自己去做调整哈。
