### ISSUE TITLE
多级路由是一个很常见功能，但是目前系统参考vue-router官方配置是会出现页面嵌套的

### ISSUE THREAD

**Issue by zxiaozhou** [arco-design/arco-design-pro-vue#250]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.6.0
- **Browser:** chrome109.0.0.0

## What is expected?
1. 能支持多级路由，而不是只是两级
2. 如果确实配置错了，还麻烦官方提供一个示例

## Steps to reproduce
无法配置

**Comment by zxiaozhou** [comment]
@sHow8e 
1. 已经处理好，实际是需要增加一个空的parentlayout,代码如下：
```
<template>
  <router-view />
</template>
```
2. 多级路由配置方式
<img width="540" alt="image" src="https://user-images.githubusercontent.com/62740686/216563498-6671a2f8-fc0d-40fb-8938-ec451f23b478.png">

**Comment by xiaoxiaohuayu** [comment]
您好。我能请教您个问题吗？我页面没有子级的话，应该如何写路由？就是说layout的组件下面展示的是我一级菜单的视图而不是一级菜单下面的children
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/30976418/216874719-68123086-837f-4b2d-b2c9-071e09ee02b0.png">

**Comment by sHow8e** [comment]
@xiaoxiaohuayu 该页面的路由配置不需要children属性即可。或者配置hideChildrenInMenu:true属性也能满足要求。

**Comment by sHow8e** [comment]
@zxiaozhou 这个issue我先关闭了哈。Pr的评论里有说明了。3q
