### ISSUE TITLE
注册账户和忘记密码点击没有反应

### ISSUE THREAD

**Issue by lusson-luo** [arco-design/arco-design-pro-vue#252]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.6.0
- **浏览器版本:** chrome105.0.0.0
- **复现地址:** https://vue-pro.arco.design/

## 预期结果
调到对应表单页面

## 复现步骤
点击 注册账户/忘记密码

**Comment by sHow8e** [comment]
@lusson-luo 抱歉这部分属于业务层面，页面用户自行补充哈。

**Comment by lusson-luo** [comment]
> 

可以做个通用的吗

**Comment by xflihaibo** [comment]
deme 点击登录 密码错误
