### ISSUE TITLE
使用iconfont图标，build报错

### ISSUE THREAD

**Issue by SunYuanOnly** [arco-design/arco-design-pro-vue#254]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.6.1
- **框架版本:** "vue": "^3.2.37"
- **浏览器版本:** chrome110.0.0.0

## 复现步骤
在styleImport.ts文件ignoreList已加上icon和icon-font情况还是报错

## 额外补充
  开发环境运行正常，下面是依赖项
  "dependencies": {
    "@amap/amap-jsapi-loader": "^1.0.1",
    "@arco-design/web-vue": "^2.42.0",
    "@arco-themes/vue-emcrm": "^0.0.1",
    "@vueuse/core": "^9.0.0",
    "axios": "^0.27.2",
    "crypto-js": "^4.1.1",
    "date-fns": "^2.29.1",
    "echarts": "^5.3.3",
    "electron-updater": "^5.2.1",
    "exceljs": "^4.3.0",
    "file-saver": "^2.0.5",
    "js-audio-recorder": "^1.0.7",
    "lamejs": "^1.2.1",
    "lamejstmp": "^1.0.1",
    "nprogress": "^0.2.0",
    "pinia": "^2.0.17",
    "qs": "^6.11.0",
    "ts-md5": "^1.2.11",
    "vue": "^3.2.37",
    "vue-clipboard3": "^2.0.0",
    "vue-echarts": "^6.2.3",
    "vue-i18n": "^9.2.0",
    "vue-router": "^4.1.3",
    "xlsx": "0.17.3"
  },
  "devDependencies": {
    "@arco-plugins/vite-vue": "^1.3.5",
    "@types/crypto-js": "^4.1.1",
    "@types/lodash": "^4.14.177",
    "@types/node": "^18.11.18",
    "@types/nprogress": "^0.2.0",
    "@types/qs": "^6.9.7",
    "@typescript-eslint/eslint-plugin": "^5.31.0",
    "@typescript-eslint/parser": "^5.31.0",
    "@vitejs/plugin-vue": "^3.0.0",
    "@vitejs/plugin-vue-jsx": "^2.0.0",
    "@vue/babel-plugin-jsx": "^1.1.1",
    "electron": "^20.1.1",
    "electron-builder": "^23.3.3",
    "eslint": "^8.20.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-prettier": "^8.5.0",
    "eslint-import-resolver-typescript": "^3.3.0",
    "eslint-plugin-import": "^2.26.0",
    "eslint-plugin-prettier": "^4.2.1",
    "eslint-plugin-vue": "^9.3.0",
    "less": "^4.1.3",
    "lint-staged": "^13.0.3",
    "mockjs": "^1.1.0",
    "prettier": "^2.7.1",
    "rollup-plugin-visualizer": "^5.7.1",
    "typescript": "^4.6.4",
    "unplugin-vue-components": "^0.23.0",
    "vite": "^3.0.0",
    "vite-plugin-compression": "^0.5.1",
    "vite-plugin-eslint": "^1.7.0",
    "vite-plugin-imagemin": "^0.6.1",
    "vite-plugin-mock": "^2.9.6",
    "vite-plugin-style-import": "1.4.1",
    "vite-svg-loader": "^3.4.0",
    "vue-tsc": "^0.38.4"
  },
  "resolutions": {
    "bin-wrapper": "npm:bin-wrapper-china",
    "rollup": "^2.56.3",
    "gifsicle": "5.2.0"
  }

**Comment by SunYuanOnly** [comment]
![image](https://user-images.githubusercontent.com/16498201/218616035-4036ed3c-6918-4535-a680-9a83fb9c5522.png)

**Comment by sHow8e** [comment]
@SunYuanOnly 你在项目中如何使用的？提供一下复现的case吧。

**Comment by SunYuanOnly** [comment]
> @SunYuanOnly 你在项目中如何使用的？提供一下复现的case吧。
### Vue
               <template>
                          <div>
                              <a-space>
                                <span>#户号</span>
                                <a-divider direction="vertical" />
                                <icon-font type="icon-card" :size="22" />法人代表
                                <a-divider direction="vertical" />
                                <icon-font type="icon-cny" :size="20" />注册资本
                                <a-divider direction="vertical" />
                                <icon-font type="icon-bank" :size="22" />AAA
                                <a-divider direction="vertical" />
                                <icon-font type="icon-area" :size="23" />行业类别
                                <a-divider direction="vertical" />
                                <icon-font type="icon-cmanager" :size="20" />张三 1895809000
                              </a-space>
                            </div>
             </template>
### JS
               <script lang="ts" setup>
                 import { Icon } from '@arco-design/web-vue'
                 const IconFont = Icon.addFromIconFontCn({
                 src: 'https://at.alicdn.com/t/c/font_3892420_i5la0xozs3.js'})
              </script>
### styleImport.ts
           `/**
               * Introduces component library styles on demand.
               * 按需引入组件库样式
               * https://github.com/anncwb/vite-plugin-style-import
               */
              
              import styleImport from 'vite-plugin-style-import'
              
              export default function configStyleImportPlugin() {
                const styleImportPlugin = styleImport({
                  libs: [
                    {
                      libraryName: '@arco-design/web-vue',
                      esModule: true,
                      resolveStyle: name => {
                        // The use of this part of the component must depend on the parent, so it can be ignored directly.
                        // 这部分组件的使用必须依赖父级，所以直接忽略即可。
                        const ignoreList = [
                          'countdown',
                          'config-provider',
                          'anchor-link',
                          'sub-menu',
                          'menu-item',
                          'menu-item-group',
                          'breadcrumb-item',
                          'form-item',
                          'step',
                          'card-grid',
                          'card-meta',
                          'collapse-panel',
                          'collapse-item',
                          'descriptions-item',
                          'list-item',
                          'list-item-meta',
                          'table-column',
                          'table-column-group',
                          'tab-pane',
                          'tab-content',
                          'timeline-item',
                          'tree-node',
                          'skeleton-line',
                          'skeleton-shape',
                          'grid-item',
                          'carousel-item',
                          'doption',
                          'option',
                          'optgroup',
                          'icon',
                          'icon-font'
                        ]
                        // List of components that need to map imported styles
                        // 需要映射引入样式的组件列表
                        const replaceList = {
                          'typography-text': 'typography',
                          'typography-title': 'typography',
                          'typography-paragraph': 'typography',
                          'typography-link': 'typography',
                          'dropdown-button': 'dropdown',
                          'input-password': 'input',
                          'input-textarea': 'input',
                          'input-search': 'input',
                          'input-group': 'input',
                          'radio-group': 'radio',
                          'checkbox-group': 'checkbox',
                          'layout-sider': 'layout',
                          'layout-content': 'layout',
                          'layout-footer': 'layout',
                          'layout-header': 'layout',
                          'month-picker': 'date-picker',
                          'range-picker': 'date-picker',
                          row: 'grid',
                          col: 'grid',
                          icon: 'icon',
                          'avatar-group': 'avatar',
                          'image-preview': 'image',
                          'image-preview-group': 'image'
                        }
                        if (ignoreList.includes(name)) return ''
                        // eslint-disable-next-line no-prototype-builtins
                        return replaceList.hasOwnProperty(name)
                          ? `@arco-design/web-vue/es/${replaceList[name]}/style/css.js`
                          : `@arco-design/web-vue/es/${name}/style/css.js`
                        // less
                        // return `@arco-design/web-vue/es/${name}/style/index.js`;
                      }
                    }
                  ]
                })
                return styleImportPlugin
              }
`

**Comment by SunYuanOnly** [comment]
已解决，使用的主题对应的@arco-design/web-vue版本和项目环境@arco-design/web-vue版本不一致导致
