### ISSUE TITLE
breadcrumb 动态路由

### ISSUE THREAD

**Issue by lqxlearn** [arco-design/arco-design-pro-vue#255]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
breadcrumb 可以根据路由变化动态变化,不需要每个页面配置.

## What problem does this feature solve?
目前点击breadcrumb没有跳转到路由

**Comment by sHow8e** [comment]
@lqxlearn 这部分功能可以自行编码处理哈。
