### ISSUE TITLE
使用主题风格配置后打包后，global样式会被主题样式覆盖

### ISSUE THREAD

**Issue by SunYuanOnly** [arco-design/arco-design-pro-vue#256]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.6.1
- **框架版本:** "vue": "^3.2.40",
- **浏览器版本:** chrome110.0.0.0

## 复现步骤

-     cd  arco-design-pro-vite目录 yarn install     
-      安装自定义主题 @arco-themes/vue-test-crm 
-      安装@arco-plugins/vite-vue，在vite.config.base.ts文件里配置
       ` vitePluginForArco({
         theme: '@arco-themes/vue-test-crm',
        })`
-     main.ts 
       `import '@arco-themes/vue-test-crm/css/arco.css';`
       `import '@/assets/style/global.less';`

##  依赖项
    `  "dependencies": {
        "@arco-design/web-vue": "^2.40.0",
        "@arco-plugins/vite-vue": "^1.4.2",
        "@arco-themes/vue-test-crm": "^0.0.1",
        "@vueuse/core": "^9.3.0",
        "axios": "^0.24.0",
        "dayjs": "^1.11.5",
        "echarts": "^5.4.0",
        "lodash": "^4.17.21",
        "mitt": "^3.0.0",
        "nprogress": "^0.2.0",
        "pinia": "^2.0.23",
        "query-string": "^8.0.3",
        "sortablejs": "^1.15.0",
        "vue": "^3.2.40",
        "vue-echarts": "^6.2.3",
        "vue-i18n": "^9.2.2",
        "vue-router": "^4.0.14"
      },`

**Comment by SunYuanOnly** [comment]
## global.less
   .general-card {
    border-radius: 4px;
    border: none;
    & > .arco-card-header {
      height: auto;
      padding: 20px;
      border: none;
    }
    & > .arco-card-body {
      padding: 0 20px 20px 20px;
    }
  }
## 效果, 样式引入顺序错乱
![image](https://user-images.githubusercontent.com/16498201/218674614-d3c068ce-de66-41c8-9079-fea282acb07f.png)

**Comment by sHow8e** [comment]
@SunYuanOnly 参考一下这个哈 https://github.com/arco-design/arco-design-pro-vue/issues/72

**Comment by SunYuanOnly** [comment]
> @SunYuanOnly 参考一下这个哈 #72

- vite.config.prod.ts 中注释了按需加载也还是会出现样式顺序问题
```
import { mergeConfig } from 'vite';
import baseConfig from './vite.config.base';
import configCompressPlugin from './plugin/compress';
import configVisualizerPlugin from './plugin/visualizer';
// import configArcoResolverPlugin from './plugin/arcoResolver';
// import configStyleImportPlugin from './plugin/styleImport';
import configImageminPlugin from './plugin/imagemin';

export default mergeConfig(
  {
    mode: 'production',
    plugins: [
      configCompressPlugin('gzip'),
      configVisualizerPlugin(),
      // configArcoResolverPlugin(),
      // configStyleImportPlugin(),
      configImageminPlugin(),
    ],
    build: {
      rollupOptions: {
        output: {
          manualChunks: {
            arco: ['@arco-design/web-vue'],
            chart: ['echarts', 'vue-echarts'],
            vue: ['vue', 'vue-router', 'pinia', '@vueuse/core', 'vue-i18n'],
          },
        },
      },
      chunkSizeWarningLimit: 2000,
    },
  },
  baseConfig
);
```
- main.ts
```
import { createApp } from 'vue';
import ArcoVue from '@arco-design/web-vue';
import ArcoVueIcon from '@arco-design/web-vue/es/icon';
import globalComponents from '@/components';
import router from './router';
import store from './store';
import i18n from './locale';
import directive from './directive';
import './mock';
import App from './App.vue';
import '@arco-themes/vue-test-crm/css/arco.css';
import '@/assets/style/global.less';
import '@/api/interceptor';

const app = createApp(App);

app.use(ArcoVue, {});
app.use(ArcoVueIcon);

app.use(router);
app.use(store);
app.use(i18n);
app.use(globalComponents);
app.use(directive);

app.mount('#app');
```
- vite.config.base.ts
```
 import { resolve } from 'path';
import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import vueJsx from '@vitejs/plugin-vue-jsx';
import svgLoader from 'vite-svg-loader';
import vitePluginForArco from '@arco-plugins/vite-vue';

export default defineConfig({
  plugins: [
    vue(),
    vueJsx(),
    svgLoader({ svgoConfig: {} }),
    vitePluginForArco({
      theme: '@arco-themes/vue-test-crm',
    }),
  ],
  resolve: {
    alias: [
      {
        find: '@',
        replacement: resolve(__dirname, '../src'),
      },
      {
        find: 'assets',
        replacement: resolve(__dirname, '../src/assets'),
      },
      {
        find: 'vue-i18n',
        replacement: 'vue-i18n/dist/vue-i18n.cjs.js', // Resolve the i18n warning issue
      },
      {
        find: 'vue',
        replacement: 'vue/dist/vue.esm-bundler.js', // compile template
      },
    ],
    extensions: ['.ts', '.js'],
  },
  define: {
    'process.env': {},
  },
  css: {
    preprocessorOptions: {
      less: {
        modifyVars: {
          hack: `true; @import (reference) "${resolve(
            'src/assets/style/breakpoint.less'
          )}";`,
        },
        javascriptEnabled: true,
      },
    },
  },
});
```
请问会是什么原因？

**Comment by sHow8e** [comment]
@SunYuanOnly 我看你主题导入了两次。全局导入和arco-plugin二选一，确保主题样式只导入一次，再进行顺序的排查。

**Comment by sHow8e** [comment]
@SunYuanOnly 建议先使用全量导入的方式进行样式引入。Arco-plugin目前样式处理有点问题。我推动修复一下哈。

**Comment by SunYuanOnly** [comment]
> @SunYuanOnly 我看你主题导入了两次。全局导入和arco-plugin二选一，确保主题样式只导入一次，再进行顺序的排查。

- 嗯，已经解决了，使用全局引入主题样式，谢谢 @sHow8e

**Comment by Charles7c** [comment]
怎么解决的兄弟？

**Comment by Charles7c** [comment]
> 怎么解决的兄弟？

已参考摸索解决，详情可参考：https://github.com/Charles7c/continew-admin/commit/be8732d812e021631864b0ff6225b4da24cafcee
