### ISSUE TITLE
Less 变量替换 配置未生效

### ISSUE THREAD

**Issue by lqxlearn** [arco-design/arco-design-pro-vue#259]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.15
- **Framework version:** vue
- **Browser:** chrome104.0.0.0
- **Reproduction Link:** https://arco.design/vue/docs/theme

## What is expected?
css: {
    preprocessorOptions: {
      less: {
        modifyVars: {
          hack: `true; @import (reference) "${resolve(
            'src/assets/style/breakpoint.less'
          )}";`,
          'arcoblue-6': '#f85959',
        },
        javascriptEnabled: true,
      },
    },
  },
还是显示蓝色.

## Steps to reproduce
 "@arco-design/web-vue": "^2.40.0",
    "@vueuse/core": "^9.3.0",
    "arco-design-pro-vue": "^2.5.15",

**Comment by sHow8e** [comment]
@lqxlearn 主文件入口导入的是css。你换成less应该就行了。https://github.com/arco-design/arco-design-pro-vue/blob/7be804c3c0097b597f64b5733ad45132fc711ca0/arco-design-pro-vite/src/main.ts#L11
