### ISSUE TITLE
能否加出来个菜单管理？具有前端控路由和后端控路由的配置

### ISSUE THREAD

**Issue by lt1067066026** [arco-design/arco-design-pro-vue#26]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
很多vue3 ts管理系统，例如vben，都有菜单配置这个功能，并且能灵活的选择是前端控由还是后端控由模式

## What problem does this feature solve?
更加灵活。现目前路由是完全交由前端控制的，可配置性不强，每次都要重新发包。

**Comment by sHow8e** [comment]
@lt1067066026 hihi 你的需求已经收录，这个功能近期可以进行完善推出哈。敬请期待哈

**Comment by deluxebear** [comment]
这个功能已经在开发了吗，大概什么时候推出，本打算自己改造的，无奈自己前端技术有限。而且我发现这个框架目前的菜单只能二级菜单路由，不能对一级菜单路由，可以的话，顺便把这个功能也加进去

**Comment by sHow8e** [comment]
@deluxebear 这个功能目前还未开始。如果可以的话可以先行查看[权限控制](https://arco.design/vue/docs/pro/permission)文档进行处理。菜单的话目前组件内也只是处理到二级菜单。更多级菜单可以根据自身需要自行拓展。如果出现更多级的菜单也可能是产品设计不合理问题，可以和产品经理进行协调再进行开发哈。

**Comment by lt1067066026** [comment]
期待通过后台来动态生成路由表(后台方式控制)，有了菜单管理，项目框架选型也就可以敲定了，哈哈

**Comment by captree** [comment]
> 

是可以使用后端路由的把，在src\components\menu\index.vue里，试试把copyRouter更换为你后端获取的值

**Comment by captree** [comment]
> 期待通过后台来动态生成路由表(后台方式控制)，有了菜单管理，项目框架选型也就可以敲定了，哈哈
是可以使用后端路由的把，在src\components\menu\index.vue里，试试把copyRouter更换为你后端获取的值

**Comment by captree** [comment]
> 期待通过后台来动态生成路由表(后台方式控制)，有了菜单管理，项目框架选型也就可以敲定了，哈哈

是可以使用后端路由的把，在src\components\menu\index.vue里，试试把copyRouter更换为你后端获取的值

**Comment by lt1067066026** [comment]
怎么删除了，这个功能不继续做了是吗？

**Comment by sHow8e** [comment]
@lt1067066026 后续会有相关的开发计划

**Comment by sHow8e** [comment]
@chocolate1012 会做的。预计这个月底哈。

**Comment by CangJieStore** [comment]
@sHow8e 今天立夏，不知道动态路由的功能是否可以发出参考了？

**Comment by sHow8e** [comment]
done v2.4.1

**Comment by leleccccc** [comment]
@sHow8e 最新的版本左侧的菜单管理似乎还是没有，只是代码里面有mock模拟从后端拿菜单
