### ISSUE TITLE
select组件无法映射空字符串

### ISSUE THREAD

**Issue by yuqiuwen** [arco-design/arco-design-pro-vue#261]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.6.1
- **Browser:** chrome110.0.0.0

## Steps to reproduce
下拉框中某个选项值为空字符串的话，则无法选择此项

**Comment by sHow8e** [comment]
@yuqiuwen 具体组件使用问题可以到组件库[issue](https://github.com/arco-design/arco-design-vue/issues)里提哈。 3q
