### ISSUE TITLE
使用多页签，点击详情页面，路由没有参数导致报错

### ISSUE THREAD

**Issue by mltpig** [arco-design/arco-design-pro-vue#267]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Browser:** firefox110.0
- **Package Name And Version:** arco-design-pro-vue@2.6.1

## Extra info
从列表跳转到详情的路由http://localhost:3011/#/datas/info/69, ID为69. 
切换标签页时报错：
runtime-core.esm-bundler.js:218 Uncaught Error: Missing required param "id"

**Comment by mltpig** [comment]
原来是需要使用query传参方式

**Comment by anbring** [comment]
> 原来是需要使用query传参方式

请问列表页跳转到详情页，是如何写的？
