### ISSUE TITLE
模板内容拷贝失败

### ISSUE THREAD

**Issue by 2738325971** [arco-design/arco-design-pro-vue#269]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.6.1
- **Framework version:** Vue
- **Browser:** chrome111.0.0.0

## Steps to reproduce
npm i -g @arco-design/arco-cli
acro init vue-arco

**Comment by sHow8e** [comment]
@2738325971 hi 参考一下这个https://github.com/arco-design/arco-design-pro-vue/issues/127
