### ISSUE TITLE
range picker locale does not match

### ISSUE THREAD

**Issue by Kefeng2017** [arco-design/arco-design-pro-vue#27]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.2.3
- **System:** windows 10
- **Browser:** chrome80.0.3987.132
- **Reproduction Link:** http://vue-pro.arco.design/list/search-table

## What is expected?
range picker show the correct locale

**Comment by Kefeng2017** [comment]
[](url
![Snipaste_2022-03-01_09-28-27](https://user-images.githubusercontent.com/33170776/156090367-831edc3a-2e6a-4d6f-95e9-8a96b9afe15b.png)
)

**Comment by sHow8e** [comment]
You are advised to consult the component documentation for possible component usage problems.
[DatePicker Document](https://arco.design/vue/component/date-picker)

**Comment by Kefeng2017** [comment]
> 

yes，it's useful to set a locale prop for date picker, but in your vue demo, it's just not work while i try to switch language in navbar.

**Comment by sHow8e** [comment]
@Kefeng2017 oops~ I get it. A fix will be released tonight. thx!

**Comment by sHow8e** [comment]
@Kefeng2017 release [V2.2.4](https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.2.4)
