### ISSUE TITLE
发布后是白屏

### ISSUE THREAD

**Issue by holyrong** [arco-design/arco-design-pro-vue#271]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.6.1
- **Framework version:** 2.44.2
- **Browser:** chrome111.0.0.0

## What is expected?
能正常打开站点

## Steps to reproduce
1.所有的插件都已经升级到最新版本；
2.修改了styleImport.ts，引用import { createStyleImportPlugin } from 'vite-plugin-style-import';修改 const styleImportPlugin = createStyleImportPlugin
3.yarn build 发布到IIS
4.打开发布后的站点，白屏
浏览器监测到只有两个请求：localhost和logo-xxx.svg

**Comment by sHow8e** [comment]
@holyrong 首先你部署前跑一遍npm run preview命令。预览一下Pro打包是否正常。至于部署线上白屏，可能是你部署的问题，检查ip端口和目标文件夹配置正确。

**Comment by holyrong** [comment]
> @holyrong 首先你部署前跑一遍npm run preview命令。预览一下Pro打包是否正常。至于部署线上白屏，可能是你部署的问题，检查ip端口和目标文件夹配置正确。

把vite版本降级后正常了
