### ISSUE TITLE
页签较多时，不显示滚动条

### ISSUE THREAD

**Issue by sunjingz0502** [arco-design/arco-design-pro-vue#273]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.7.0
- **Framework version:** 3.2.40
- **Browser:** chrome111.0.0.0

## What is expected?
页签很多时有滚动条，可以拖动滚动条。打开新页签时自动滚动，显示刚打开的页签

## Steps to reproduce
1.arco-cli创建完整项目
2.页面配置勾选上多页签
3.打开很多个页签
4.水平方向没有滚动条，无法显示后面的页签
5.尝试用了Scrollbar组件，没设置成功

**Comment by sHow8e** [comment]
@sunjingz0502 hi 水平滚动条是做了一个隐藏处理。如果想要看到滚动条可以把容器高度调整一下。
