### ISSUE TITLE
a-modal 表单验证失效

### ISSUE THREAD

**Issue by RedCarl** [arco-design/arco-design-pro-vue#278]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 现有案例
    <a-modal
      v-model:visible="addVisible"
      width="auto"
      :mask-closable="false"
      :title="$t('searchTable.columns.modal.add.title')"
      @before-ok="addBeforeOk"
      @ok="addOk"
      @cancel="addCancel"
    >
      <a-form :ref="formRef" :model="form" :style="{ width: '600px' }">
        <a-form-item
          field="name"
          label="名称"
          :rules="[{ required: true, message: '应用名称不能为空！' }]"
          :validate-trigger="['input']"
        >

## 预期解决问题
点击按钮后不会去校验表单

## 额外补充
      const addBeforeOk = (done: (closed: boolean) => void) => {
        if (formRef.value) {
          formRef.value
            .validate()
            .then((res) => done(!res))
            .catch((error) => done(false));
        } else {
          done(true);
        }
      };
      const addOk = async () => {

**Comment by sHow8e** [comment]
@RedCarl hi 组件的问题在[组件库]( https://github.com/arco-design/arco-design-vue/issues)里提哈。3q
