### ISSUE TITLE
a-tree-select的下拉箭头初始在整个组件的中间

### ISSUE THREAD

**Issue by yan357174356** [arco-design/arco-design-pro-vue#283]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.7.0
- **Browser:** chrome111.0.0.0

## Steps to reproduce
初始这个箭头应该在组件的靠右位置，现在只有选择一个选项后，才会靠右

**Comment by sHow8e** [comment]
@yan357174356 组件问题可以提到这里 [issue](https://github.com/arco-design/arco-design-vue/issues) 3q
