### ISSUE TITLE
pro顶部检索框点击没反应

### ISSUE THREAD

**Issue by samchenws** [arco-design/arco-design-pro-vue#288]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.7.2
- **Framework version:** Vue
- **Browser:** chrome86.0.4240.198
- **Reproduction Link:** http://vue-pro.arco.design/dashboard/workplace

## Extra info
pro顶部检索框点击没反应，react版本就有

## What is expected?
pro顶部检索框点击没反应，react版本就有

**Comment by sHow8e** [comment]
@samchenws 交互不一致。这部分可以自己加上哈。
