### ISSUE TITLE
我想在 table  template中渲染出data中children的数据。

### ISSUE THREAD

**Issue by wsaxq** [arco-design/arco-design-pro-vue#291]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 现有案例
    <template #weight="{ rowIndex }">
        <a-input
          :default-value="data[rowIndex].weight   ''"
          :style="{
            width: '50px',
            border: '1px solid #D4D4D4',
            textAlign: 'center',
          }"
          data-category="data[rowIndex]"
          @blur="changeWeight($event, data[rowIndex].id)"
        />
      </template>

0: {key: "15", id: 15, name: "新分类22", pid: 1, level: 2, …}
1: {
createTime: "2023年01月04日16:42:27"
id: 2
isClose: 0
key: "2"
level: 2
name: "券问题"
pid: 1
weight: 0
}
 
createTime: "2023年01月04日16:42:01"
id: 1
isClose: 0
key: "1"
level: 1
name: "小程序点单"
pid: 0
weight: 80

## 预期解决问题
在 template 中获取展示 children数据

## 额外补充
在 template 中渲染children的数据

**Comment by wsaxq** [comment]
![image](https://user-images.githubusercontent.com/104194880/233252926-8aa3ded0-e023-4b29-b70a-6eacb0dc5080.png)
这是数据

**Comment by sHow8e** [comment]
@wsaxq 我理解这部分是业务逻辑和组件使用的问题。具体可以看[Table文档](https://arco.bytedance.net/vue/component/table#custom)来自行实现哈。
