### ISSUE TITLE
a-pagination 分页组件点击页面无法切换 点击size 也无法切换

### ISSUE THREAD

**Issue by Aichen517** [arco-design/arco-design-pro-vue#292]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.7.2
- **Browser:** chrome112.0.0.0

**Comment by zjy4fun** [comment]
有代码片段吗？
我看官方示例没有问题啊

**Comment by sHow8e** [comment]
@Aichen517 组件问题可以到[Arco Vue](https://github.com/arco-design/arco-design-vue/issues)提问哈。
