### ISSUE TITLE
目前通过hideChildrenInMenu与activeMenu配合无法完成一级菜单同时高亮显示(除非点击菜单两次，或者父类不要使用重定向)

### ISSUE THREAD

**Issue by zxuanhong** [arco-design/arco-design-pro-vue#294]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.7.2
- **Browser:** chrome113.0.0.0

## Steps to reproduce
1. 按照#85 issue方式实现一级菜单，无法高亮。原因在于菜单高亮实现根本不可能获取到路由子类的activeMenu
2. 具体代码分析如下
<img width="1060" alt="image" src="https://github.com/arco-design/arco-design-pro-vue/assets/62740686/531dc60e-0394-4d7a-8c9c-d370bbe61842">

**Comment by ankyo** [comment]
src/router/app-menus/index.ts

```typescript
const appClientMenus = mixinRoutes.map((el) => {
  const { name, path, meta, redirect, children } = el;
  return {
    name,
    path,
    meta,
    redirect,
    children,
  };
});
```

改为

```typescript
const clientMenus = mixinRoutes.map((route) => {
  let { name, path, meta, redirect, children } = route
  if (meta?.hideChildrenInMenu && children?.length) {
    name = children[0].name
  }
  return {
    name,
    path,
    meta,
    redirect,
    children,
  }
})
```
然后这样定义路由就可以了

```typescript
export default {
  path: '/overview',
  component: DEFAULT_LAYOUT,
  meta: {
    order: 0,
    icon: 'icon-dashboard',
    locale: 'menu.overview',
    hideChildrenInMenu: true,
    ...REQUIRES_PERMISSION,
  },
  children: [
    {
      path: '',
      name: 'overview',
      component: () => import('@/views/overview/index.vue'),
    },
  ],
} as AppRouteRecordRaw
```

**Comment by zxuanhong** [comment]
@ankyo 非常感谢。我觉得这些都应该官方实现下。而不是用户到使用了各种改

**Comment by ankyo** [comment]
> @ankyo 非常感谢。我觉得这些都应该官方实现下。而不是用户到使用了各种改

官方就是提供个样版，实际使用要改的地方很多的，我是参考官方的重新写的
