### ISSUE TITLE
请问有没有非ts版的arco pro

### ISSUE THREAD

**Issue by lovesL** [arco-design/arco-design-pro-vue#299]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.7.2
- **浏览器版本:** chrome112.0.0.0

**Comment by sHow8e** [comment]
@lovesL 纯js版本没有哈。ts是趋势是主流，且是js的超集。可以用起来了哈。
