### ISSUE TITLE
Can not init vue project with arco-cli

### ISSUE THREAD

**Issue by parse-code** [arco-design/arco-design-pro-vue#3]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** @arco-design/arco-design-pro-vue
- **System:** Mac
- **Browser:** Chrome
- **Reproduction Link:** https://github.com/arco-design/arco-design-pro-vue

## What is expected?
Can create arco design pro vue

## Steps to reproduce
```
npm i @arco-design/arco-cli@latest yarn -g
arco init my-project
```
can not see `- Arco Pro 项目`

**Comment by parse-code** [comment]
It works now, please close this issue

**Comment by parse-code** [comment]
It works now

**Comment by sHow8e** [comment]
> It works now

Have a good time！
