### ISSUE TITLE
菜单来源于后台设置true的时候 多页签刷新页面 会not found

### ISSUE THREAD

**Issue by leif0419** [arco-design/arco-design-pro-vue#301]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.7.2
- **Browser:** chrome113.0.0.0

**Comment by leif0419** [comment]
菜单来源后台、多页签设置为true
右击多页签  重新加载 not found

**Comment by tongxin2013** [comment]
我是在/src/router/guard/permission.ts调整了相关代码

` const element = serverMenuConfig.shift();`
`if (to.name === 'Redirect') exist = true; `
` if (element?.name === to.name) exist = true;`
        
第二行为新增代码        
大家都怎么实现的呢？方便贴个代码不
