### ISSUE TITLE
✖ stylelint --fix: TypeError: opts.node.rangeBy is not a function

### ISSUE THREAD

**Issue by Wjinlei** [arco-design/arco-design-pro-vue#302]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.7.2
- **Browser:** chrome114.0.0.0

**Comment by java668** [comment]
解决了吗，我也遇到了

**Comment by Wjinlei** [comment]
> 解决了吗，我也遇到了

解决了，要更新`styleline`，我更新到了`15.7.0`版本，然后移除这个包`stylelint-config-prettier`,新版本用不着了，然后`.stylelintrc.js`中删除`stylelint-config-prettier`

**Comment by GitHub-Ronald** [comment]
> 

我也是更新版本就好了

**Comment by mouyong** [comment]
怎么更新的，我尝试
pnpm upgrade styleline
pnpm remove stylelint-config-prettier

然后注释 .stylelintrc.js 的 stylelint-config-prettier

报错反而更多了。

![image](https://github.com/arco-design/arco-design-pro-vue/assets/10336437/7c747e2e-bf37-4934-9ab9-d669e3b18074)

**Comment by Wjinlei** [comment]
> styleline

是更新stylelint,我打错字了。

**Comment by mouyong** [comment]
![image](https://github.com/arco-design/arco-design-pro-vue/assets/10336437/b6b68cb3-1ae5-4f6b-9778-bbe062a796db)

我注释后可以提交

**Comment by mouyong** [comment]
@Wjinlei 还是不行。我测试了下重新提交。

![image](https://github.com/arco-design/arco-design-pro-vue/assets/10336437/e393985c-ba8b-4e19-bae2-fe433fcf0293)

**Comment by Wjinlei** [comment]
@mouyong 你重新来一次把stylelint更新到15.7.0试试

**Comment by mouyong** [comment]
咋操作“重新来”。

代码里面目前属于刚初始化。主要gai dong改动是下方2个文件的 title ，注释 img

![image](https://github.com/arco-design/arco-design-pro-vue/assets/10336437/989ebc8d-c273-42b7-a644-5101893c5ec3)

**Comment by Wjinlei** [comment]
@mouyong pnpm upgrade stylelint@15.7.0

**Comment by mouyong** [comment]
看起来可能得放弃。

![image](https://github.com/arco-design/arco-design-pro-vue/assets/10336437/00e995a5-d982-4f39-b27a-0d108ae28d74)

**Comment by Wjinlei** [comment]
![preview](https://github.com/arco-design/arco-design-pro-vue/assets/11342964/ac8e4699-940c-4ca2-ba5c-96b159acb589)

我目前的包，我现在一切正常，你可以参考下。

**Comment by Wjinlei** [comment]
@mouyong 惹毛了，你重新拉项目，重新弄下呗，哈哈哈

**Comment by mouyong** [comment]
我目前的依赖。

计划是，如果找不到解决办法，就干脆在 .husky 的 pre-commit 里面关掉 lint-staged 操作，禁止校验格式。

至少后人看到 issue 的时候，可以这样做。

![image](https://github.com/arco-design/arco-design-pro-vue/assets/10336437/456e2815-e224-4125-88d4-35f7bdb42aae)

**Comment by Wjinlei** [comment]
@mouyong 这个项目问题是挺多的，我做完这个项目都要换了。

**Comment by mouyong** [comment]
项目是一小时之前拉的，放弃折腾了。有这个时间不如节约下来喝杯咖啡，打打游戏。

**Comment by mouyong** [comment]
有道理。我现在就换 antdv

**Comment by mouyong** [comment]
之前的时候就踩过一些坑了。然后当时结果是说等官方修复。

我是想着字节家的。所以才多次尝试。

**Comment by mouyong** [comment]
反正刚初始化。换了换了。

**Comment by mouyong** [comment]
总之这个项目给我一种不稳定的感觉。

**Comment by mouyong** [comment]
> 有道理。我现在就换别的。

你有没有推荐的。

**Comment by Wjinlei** [comment]
@mouyong 不清楚，我目前也只用过antdv和这个arco, https://github.com/vbenjs/vue-vben-admin 看起来不错，看作者更新的挺勤快的。

**Comment by mouyong** [comment]
vben 我之前用过，我在看一下。

**Comment by GitHub-Ronald** [comment]
我只是把stylelint更新，其他没动，就可以了

**Comment by lxccc812** [comment]
也有可能是postcss与stylelint不兼容的问题

**Comment by mrhuangzh** [comment]
提升stylelint版本至 15 后，有遇到依赖冲突问题么：Issues with peer dependencies found
.
├─┬ stylelint-config-prettier 9.0.5
│ └── ✕ unmet peer stylelint@">= 11.x < 15": found 15.11.0
├─┬ stylelint-config-recommended-vue 1.5.0
│ └─┬ stylelint-config-recommended 14.0.1
│   └── ✕ unmet peer stylelint@^16.1.0: found 15.11.0
├─┬ stylelint-config-standard 29.0.0
│ ├── ✕ unmet peer stylelint@^14.14.0: found 15.11.0
│ └─┬ stylelint-config-recommended 9.0.0
│   └── ✕ unmet peer stylelint@^14.10.0: found 15.11.0
└─┬ stylelint-order 5.0.0
  └── ✕ unmet peer stylelint@^14.0.0: found 15.11.0

**Comment by hunterMG** [comment]
也遇到这个问题了, 遍寻网络后无果, 然后把 stylelint\postcss 和相关的包都更新到最新版, 移除 stylelint-config-prettier.(感谢LLM)

```bash
pnpm add stylelint@latest postcss@latest --save-dev
pnpm rm stylelint-config-prettier
pnpm upgrade stylelint-config-standard@latest stylelint-order@latest
```

再注释 .stylelintrc.js 中的 stylelint-config-prettier, 就能commit了.

### `pnpm ls` 输出:
```
Legend: production dependency, optional only, dev only

arco-design-pro-vue@1.0.0 /fe (PRIVATE)

dependencies:
@arco-design/web-vue 2.56.3  axios 0.24.0                 lodash 4.17.21               pinia 2.2.5                  vue 3.5.12                   vue-router 4.4.5
@vueuse/core 9.13.0          dayjs 1.11.13                mitt 3.0.1                   query-string 8.2.0           vue-echarts 6.7.3
arco-design-pro-vue 2.7.3    echarts 5.5.1                nprogress 0.2.0              sortablejs 1.15.3            vue-i18n 9.14.1

devDependencies:
@arco-plugins/vite-vue 1.4.5             @vue/babel-plugin-jsx 1.2.5              less 4.2.0                               stylelint-config-standard 36.0.1
@commitlint/cli 17.8.1                   consola 2.15.3                           lint-staged 13.3.0                       stylelint-order 6.0.4
@commitlint/config-conventional 17.8.1   cross-env 7.0.3                          mockjs 1.1.0                             typescript 4.9.5
@types/lodash 4.17.13                    eslint 8.57.1                            postcss 8.4.47                           unplugin-vue-components 0.24.1
@types/mockjs 1.0.10                     eslint-config-airbnb-base 15.0.0         postcss-html 1.7.0                       vite 3.2.11
@types/nprogress 0.2.3                   eslint-config-prettier 8.10.0            prettier 2.8.8                           vite-plugin-compression 0.5.1
@types/sortablejs 1.15.8                 eslint-import-resolver-typescript 3.6.3  rollup 2.79.2                            vite-plugin-eslint 1.8.1
@typescript-eslint/eslint-plugin 5.62.0  eslint-plugin-import 2.31.0              rollup-plugin-visualizer 5.12.0          vite-plugin-imagemin 0.6.1
@typescript-eslint/parser 5.62.0         eslint-plugin-prettier 4.2.1             stylelint 16.10.0                        vite-svg-loader 3.6.0
@vitejs/plugin-vue 3.2.0                 eslint-plugin-vue 9.30.0                 stylelint-config-rational-order 0.1.2    vue-tsc 1.8.27
@vitejs/plugin-vue-jsx 2.1.1             husky 8.0.3                              stylelint-config-recommended-vue 1.5.0
```

**Comment by polaurs** [comment]
这个项目我原先在2022-2023年的一个项目在用，当时觉得挺稳定的。没想到现在这么多坑。来自2025-1-3，最新的模板(node22)又遇到这个问题了

**Comment by Theadmaster** [comment]
https://github.com/arco-design/arco-design-pro-vue/issues/302#issuecomment-2448954886

按照上面这位大佬的提示

把`stylelint`相关的包都升级到最新，删掉`stylelint-config-prettier`以及其相关配置，就可以了。

感谢大佬～

```
pnpm upgrade stylelint@latest 
pnpm rm stylelint-config-prettier
pnpm upgrade stylelint-config-standard@latest stylelint-order@latest
```
附一张`pnpm list`

![Image](https://github.com/user-attachments/assets/c76e4fd8-43c4-4c9e-9840-582b428fbd81)
