### ISSUE TITLE
希望增加横向一级菜单  侧边栏为 二 三级菜单

### ISSUE THREAD

**Issue by lovesL** [arco-design/arco-design-pro-vue#307]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
![image](https://github.com/arco-design/arco-design-pro-vue/assets/27960630/0d1e2d5e-fda4-4b41-8c5c-2a01371360b6)

## 现有案例
可以搜索ruoyi 有实现

## 预期解决问题
菜单过多

**Comment by lovesL** [comment]
提个小需求  我最近遇到个需求就是 有些年龄的大眼神不好  闲整体字体有点小  要放大。。。不知能否设置整体布局

**Comment by sHow8e** [comment]
@lovesL 这部分功能属于可编辑自定义功能，可以根据自身业务需要进行调整哈。
