### ISSUE TITLE
build结束后生成的index.html中没有script引用，导致打开页面空白

### ISSUE THREAD

**Issue by jianxing-xu** [arco-design/arco-design-pro-vue#308]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.7.2
- **Framework version:** Vue
- **Browser:** chrome114.0.0.0

## Extra info
import { resolve } from 'path';
import { defineConfig, loadEnv } from 'vite';
import vue from '@vitejs/plugin-vue';
import vueJsx from '@vitejs/plugin-vue-jsx';
import svgLoader from 'vite-svg-loader';
import UnoCSS from 'unocss/vite'
import configArcoStyleImportPlugin from './plugin/arcoStyleImport';
import configCompressPlugin from './plugin/compress';
import configVisualizerPlugin from './plugin/visualizer';
import configArcoResolverPlugin from './plugin/arcoResolver';
import configImageminPlugin from './plugin/imagemin';

const PROD_PLUGINS = [
  configCompressPlugin,
  configVisualizerPlugin,
  configArcoResolverPlugin,
  configImageminPlugin
]

export default defineConfig(({ mode }) => {
  const port = parseInt(process.env.port || process.env.npm_config_port || '8082')
  const IS_PROD = process.env.NODE_ENV === 'production';
  function getEnv(key) { // 定义获取环境变量的方法
    return loadEnv(mode, process.cwd(), '')[key] // 第三个参数非常重要，下面有详解
  }
  console.log('process.evn:', process.env.NODE_ENV)
  console.log('VITE_API_BASE_URL', getEnv('VITE_API_BASE_URL'))
  return {
    debug: !IS_PROD,
    plugins: [
      vue(),
      vueJsx(),
      svgLoader({ svgoConfig: {} }),
      configArcoStyleImportPlugin(),
      UnoCSS(),
      ...(IS_PROD ? PROD_PLUGINS : [])
    ],
    resolve: {
      alias: [
        {
          find: '@',
          replacement: resolve(__dirname, '../src'),
        },
        {
          find: 'assets',
          replacement: resolve(__dirname, '../src/assets'),
        },
        {
          find: 'vue-i18n',
          replacement: 'vue-i18n/dist/vue-i18n.cjs.js', // Resolve the i18n warning issue
        },
        {
          find: 'vue',
          replacement: 'vue/dist/vue.esm-bundler.js', // compile template
        },
      ],
      extensions: ['.ts', '.js'],
    },
    define: {
      'process.env': {},
    },
    css: {
      preprocessorOptions: {
        less: {
          modifyVars: {
            hack: `true; @import (reference) "${resolve(
              'src/assets/style/breakpoint.less'
            )}";`,
          },
          javascriptEnabled: true,
        },
      },
    },
    server: {
      open: true,
      fs: {
        strict: true,
      },
      host: '0.0.0.0',
      port,
      // https: true,
      proxy: {
        '/proxy_api': {
          target: getEnv('VITE_API_BASE_URL'),
          changeOrigin: true,
          rewrite: p => p.replace(/^\/proxy_api/, '')
        }
      }
    },
    build: {
      ...(!IS_PROD ? {} : {
        rollupOptions: {
          output: {
            manualChunks: {
              arco: ['@arco-design/web-vue'],
              chart: ['echarts', 'vue-echarts'],
              vue: ['vue', 'vue-router', 'pinia', '@vueuse/core', 'vue-i18n'],
            },
          },
        },
        chunkSizeWarningLimit: 2000,
      })
    }
  }
})

**Comment by Wenpiner** [comment]
解决了吗？

**Comment by holyrong** [comment]
我把vite降级到3.x时，打包后可以运行了

**Comment by liaowentao1016** [comment]
同问

**Comment by liaowentao1016** [comment]
这个问题可坑死我了

**Comment by sHow8e** [comment]
@holyrong 可以参考这个issue。https://github.com/arco-design/arco-design-pro-vue/issues/225
