### ISSUE TITLE
发布的版本是否有经过足够的测试？bug真多。

### ISSUE THREAD

**Issue by Wjinlei** [arco-design/arco-design-pro-vue#309]
新创建的项目，什么都没动，代码检查就过不了，好像`stylelint`有问题。

`stylelint`总是报错`TypeError: node.rangeBy is not a function`详见[https://github.com/okonet/lint-staged/issues/1298](https://github.com/okonet/lint-staged/issues/1298)

这项目怕不是个半成品吧？

**Comment by sHow8e** [comment]
@Wjinlei lint相关的报错可能是包版本的变更导致。这部分可以自行升级处理。
