### ISSUE TITLE
默认初始化的项目无法使用页头快速检索功能

### ISSUE THREAD

**Issue by martinx** [arco-design/arco-design-pro-vue#312]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.7.2
- **Framework version:** Vue 3.2.40
- **Browser:** chrome114.0.0.0

## What is expected?
期望点击搜索，能出现搜索框。

## Steps to reproduce
```
1. arco init sample
 * Vue
 * Arco Pro Project
 * Full version (contains all pages)

2. cd sample

3. pnpm run dev

4. Login
```

登录成功后，点击Header 右侧最左边的搜索按钮，没有任何反应。

![image](https://github.com/arco-design/arco-design-pro-vue/assets/6499/80907af4-502c-49ae-a7b5-3c6a6970a662)

**Comment by sHow8e** [comment]
@martinx 检索功能需要用户根据自身需求去增加哈。这个仅仅是个样式占位。
