### ISSUE TITLE
开关组件 a-switch 绑定不生效问题

### ISSUE THREAD

**Issue by raylin666** [arco-design/arco-design-pro-vue#315]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.7.2
- **Browser:** chrome114.0.0.0

## Steps to reproduce
<img src="https://yd.tengzhihh.com/image/fe5d85c05d130f-2642x512.png" />

如上是我的列表数据展示, 我点击编辑按钮并保存后重新请求列表数据, 开关组件并不会更新。并且我已经设置了 v-model，通过浏览器F12也能看到 v-model 的值是会变化的(布尔值)，这是不是个BUG?

如下是开关组件的 v-model 值更新代码:
<img src="https://yd.tengzhihh.com/image/b2d8361ab69b79-1954x1034.png" />
<img src="https://yd.tengzhihh.com/image/b2b20ee96f8678-2066x1164.png" />

**Comment by sHow8e** [comment]
@raylin666 组件使用问题可以提到[组件库](https://github.com/arco-design/arco-design-vue/issues)哈
