### ISSUE TITLE
可否增加下顶部导航的多标签页功能

### ISSUE THREAD

**Issue by ohacn** [arco-design/arco-design-pro-vue#316]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
希望能提供多标签页支持，这样就可以同时打开多个标签页，切换的时候也不会导致页面刷新数据丢失，用户体验可以更好，谢谢！

## What problem does this feature solve?
目前不支持同时打开多个标签页，每次通过左侧菜单打开页面，再切换回之前的页面就会重新加载页面，对于需要进行频繁页面切换的场景非常不友好。

**Comment by leslieeilsel** [comment]
![image](https://github.com/arco-design/arco-design-pro-vue/assets/25165449/44f41c11-eab8-43f3-b2ec-b53767a89c7c)
是支持的

**Comment by ohacn** [comment]
> ![image](https://user-images.githubusercontent.com/25165449/257065603-44f41c11-eab8-43f3-b2ec-b53767a89c7c.png) 是支持的

感谢！

**Comment by kcersing** [comment]
react 版的不支持啊
