### ISSUE TITLE
初始化项目失败

### ISSUE THREAD

**Issue by Tea-brother** [arco-design/arco-design-pro-vue#317]
arco-init  项目初始化失败！
Error: spawnSync pnpm.cmd ENOENT求个解决办法

**Comment by Robin3D** [comment]
相同的错误
arco v1.27.5 
node v18.16.0 
npm 9.5.1

**Comment by sHow8e** [comment]
@Tea-brother @Robin3D 这部分应该是cli的问题。尝试提给[arco-cli](https://github.com/arco-design/arco-cli/issues)。

**Comment by LetMeHappyCode** [comment]
arco-init  项目初始化失败！
Error: spawnSync pnpm ENOENT  这个错误

安装pnpm后初始化成功

**Comment by moonlight2012** [comment]
cd hello-arco-pro

**pnpm run dev**
