### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by Fluox-Etine** [arco-design/arco-design-pro-vue#320]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
有时候项目不需要国际化（绝大部分）

## What problem does this feature solve?
希望官方能提供命令形式删除国际化的命令。手动改国际化有点头疼。或者可以提供国际化和非国际化的版本。谢谢

**Comment by sHow8e** [comment]
@Fluox-Etine 感谢建议。目前暂无这方面的打算。可以使用简化版本进行处理哈。

**Comment by dingshaohua-com** [comment]
我已经写了   

https://github.com/dingshaohua-com/arco-rm-i18n
