### ISSUE TITLE
菜单图标如何使用本地或iconfont的图标？

### ISSUE THREAD

**Issue by raferlyan** [arco-design/arco-design-pro-vue#321]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.7.2
- **Browser:** chrome115.0.0.0

## What is expected?
菜单的图标配置项是string,可以使用本地svg/png或者iconfont的图标吗？

**Comment by leslieeilsel** [comment]
https://arco.design/vue/component/icon#icon-font
