### ISSUE TITLE
Error: [plugin vite:dep-pre-bundle] failed to resolve entery for package "@intlify/shared"

### ISSUE THREAD

**Issue by HappyXuan** [arco-design/arco-design-pro-vue#334]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.7.2
- **框架版本:** 3.2.40
- **浏览器版本:** chrome116.0.0.0

## 额外补充
error message:
[ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "@intlify/shared". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "@intlify/shared" package

## 预期结果
After the project dependency installation is complete, it should start smoothly.

## 复现步骤
After creating a project using acro-cli, enter the project and obtain the dependency through pnpm. During startup, an error message is displayed.

**Comment by HappyXuan** [comment]
Node Version: 18.17.1
pnpm Version: 8.7.4.
And I found that in nodejs 16.x, the bug disappears.

**Comment by ohhusr** [comment]
我们遇到了相同错误，解决方案见
`https://github.com/arco-design/arco-design-pro-vue/issues/335#issue-1885165563`

**Comment by HappyXuan** [comment]
> 我们遇到了相同错误，解决方案见 `https://github.com/arco-design/arco-design-pro-vue/issues/335#issue-1885165563`

好的, 感谢您.
