### ISSUE TITLE
是否可提供删除国际化的命令?

### ISSUE THREAD

**Issue by developeryvan** [arco-design/arco-design-pro-vue#34]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
antd 中有提供类似的命令

## What problem does this feature solve?
大部分人不需要国际化命令

**Comment by sHow8e** [comment]
@developeryvan hihi 这个其实在规划中。目前可以先使用Pro的简单模式初始化项目，再去删除国际化相关的代码，工作量可能会小一点哈。

**Comment by developeryvan** [comment]
![image](https://user-images.githubusercontent.com/47513562/157159665-34186d94-a5cb-46b7-a194-dfec7fcd7f75.png)
那我先用着,win里面得修改参数才能启动.

**Comment by lvreninfo** [comment]
## 去除国际化
_Fix Version：_arco-design-pro-vue  => 2.5.11 （简版）

_Ps：_$t()、t() 请结合 src/locale/zh-CN.ts 和 src/locale/zh-CN/settings.ts 进行手动替换

├── package.json #去掉 vue-i18n

├── src
  │   ├── components
  │          ├── breadcrumb
  │                    └── index.vue  #去掉 $t()
  │          ├── global-setting
  │                    └── block.vue  #去掉 $t()
  │                    └── index.vue  #去掉 $t()、useI18n()、t()
  │          ├── menu
  │                    └── index.vue  #去掉 useI18n()、t()
  │          ├── message-box
  │                    └── locale  #去掉（以下2个文件需要结合当前进行手动替换）
  │                    └── index.vue  #去掉 $t()、useI18n()、t()
  │                    └── list.vue  #去掉 $t()
  │          ├── navbar
  │                    └── index.vue  #去掉 $t()、LOCALE_OPTIONS、locales、useLocale()、changeLocale()
  │          ├── tab-bar
  │                    └── tab-item.vue  #去掉 $t()

  │   ├── hooks
  │          └── locale.ts  # 去掉

  │   ├── locale  # 去掉

  │   ├── views
  │          ├── folder*
  │                    └── locale*  #去掉
  │                    └── file*.ts  #去掉 useI18n()、t()
  │                    └── file*.vue  #去掉 useI18n()、t()、$t()

  │   ├── router
  │          ├── externalModules
  │                    └── arco.ts  # menu.arcoWebsite 替换 'Arco Design'
  │                    └── faq.ts  # menu.faq 替换 '常见问题'
  │          ├── modules
  │                    └── dashboard.ts  #替换menu.*
  │          └── locale.ts  # menu.dashboard.workplace 替换 '工作台'

  │   └── App.vue  # 去掉locale、useLocale()、zhCN、enUS

  │   └── main.ts  # 去掉i18n()

└── tsconfig.json

**Comment by objlong** [comment]
> @developeryvan hihi 这个其实在规划中。目前可以先使用Pro的简单模式初始化项目，再去删除国际化相关的代码，工作量可能会小一点哈。

2024年了。。

**Comment by dingshaohua-com** [comment]
我已经写了，一键移除

https://github.com/dingshaohua-com/arco-rm-i18n
