### ISSUE TITLE
基于arco design pro和vitesse的中后台模板，🤔️获得更好的开发体验

### ISSUE THREAD

**Issue by sukbearai** [arco-design/arco-design-pro-vue#348]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
使用vitesse重新适配arco design pro的中后台模板，以提供更好的开发体验

## What problem does this feature solve?
访问 👉 https://github.com/sukbearai/dcy-admin/tree/1.1.2 下载代码，支持注册使用

**Comment by georgeJzzz** [comment]
> * [ ]  I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)
> 
> ## Basic Info
> ## What are the similar cases of this feature
> 使用vitesse重新适配arco design pro的中后台模板，以提供更好的开发体验
> 
> ## What problem does this feature solve?
> 访问 👉 https://github.com/sukbearai/dcy-admin/tree/1.1.2 下载代码，支持注册使用

无法访问，是否可以更新下地址

**Comment by sukbearai** [comment]
抱歉🥲删库了

**Comment by georgeJzzz** [comment]
> 抱歉🥲删库了

> 好的， 期待下次开源

**Comment by sukbearai** [comment]
> > 抱歉🥲删库了
> 
> > 好的， 期待下次开源

推荐nuxt，很丝滑
