### ISSUE TITLE
有计划做table与form的封装吗?

### ISSUE THREAD

**Issue by crazyTanuki** [arco-design/arco-design-pro-vue#372]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
类似vxe-table

## What problem does this feature solve?
减少冗余对接form与table的互动的代码

## Extra info
参考地址:https://github.com/x-extends/vxe-table

**Comment by Charles7c** [comment]
可参考 Arco 表格及表单封装：https://github.com/Charles7c/continew-admin-ui/tree/dev/src/components
