### ISSUE TITLE
官方预览VUE版，UI异常

### ISSUE THREAD

**Issue by zja0918** [arco-design/arco-design-pro-vue#38]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.2.5
- **Browser:** chrome98.0.4758.102
- **Reproduction Link:** http://vue-pro.arco.design/user/setting

## What is expected?
文字不重叠，UI能正常显示

## Steps to reproduce
1、访问http://vue-pro.arco.design/user/setting
2、点击【实名认证】
3、【企业实名认证】UI异常，文字重叠。表单与label重叠

**Comment by sHow8e** [comment]
@zja0918 样式版本没更新。(已修复) 感谢提醒哈。3q
