### ISSUE TITLE
列表页-查询表格中列设置，点击多个隐藏会出现只隐藏单个现象

### ISSUE THREAD

**Issue by georgeJzzz** [arco-design/arco-design-pro-vue#382]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.7.3
- **Framework version:** Vue
- **Browser:** chrome125.0.0.0

## What is expected?
1. 修复选择列隐藏问题
2. 默认页面页 可以设置下字段隐藏。

## Steps to reproduce
1. 列设置隐藏一个
2. 再次隐藏一个， 上次隐藏的会出现

**Comment by georgeJzzz** [comment]
并不完善的框架

**Comment by ttjimsen** [comment]
这么低级的问题，没人维护？
