### ISSUE TITLE
增加多标签页功能以及缓存

### ISSUE THREAD

**Issue by yanbowe** [arco-design/arco-design-pro-vue#4]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
vbenAdmin：https://vvbin.cn/next/#/dashboard/analysis

## What problem does this feature solve?
可以方便的切换页面

**Comment by sHow8e** [comment]
这个功能后续提上，敬请期待哈~
