### ISSUE TITLE
List 组件的视觉缺陷

### ISSUE THREAD

**Issue by SouthWan** [arco-design/arco-design-pro-vue#40]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 现有案例
Message notifications in official presentations

## 预期解决问题
Empty state components inside the list components are expected to be custom rather than mandatory in the absence of data

**Comment by sHow8e** [comment]
@SouthWan  hihi 麻烦提供详细描述哈。

**Comment by SouthWan** [comment]
列表组件在没有数据的情况下我希望它不要显示空状态组件，我希望能够对他进行自定义

**Comment by SouthWan** [comment]
> 

列表组件在没有数据的情况下我希望它不要显示空状态组件，我希望能够对他进行自定义

**Comment by sHow8e** [comment]
@SouthWan (select)[https://arco.design/vue/component/select] 使用empty slot哈。
