### ISSUE TITLE
npm install failed 

### ISSUE THREAD

**Issue by cqmking** [arco-design/arco-design-pro-vue#43]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.3.2
- **System:** win10
- **Browser:** chrome98.0.4758.102

## What is expected?
npm install success

## Steps to reproduce
Node  v12.13.1
Npm  8.5.5
arco 1.26.1

$ npm i arco-cli@latest yarn -g
$ arco init my-project
This step failed when npm install

Then I did the following steps:
$ cd my-project
$ npm i

-------------------------------------------------------------------------
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: arco-design-pro-vue@1.0.0
npm ERR! Found: eslint@8.7.0
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"8.7.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"^5.16.0 || ^6.8.0 || ^7.2.0" from eslint-config-airbnb-base@14.2.1
npm ERR! node_modules/eslint-config-airbnb-base
npm ERR!   dev eslint-config-airbnb-base@"^14.2.1" from the root project
-------------------------------------------------------------------------

Then I modify the package.json 
update "eslint": "^8.7.0"  to  "eslint": "^7.2.0"

Then npm install again, but fialed with the following issue:
-------------------------------------------------------------------------
npm ERR! code 1
npm ERR! path F:\XXX2022\vue-blender-lib\node_modules\jpegtran-bin
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node lib/install.js
npm ERR! F:\App2022\vue-blender-lib\node_modules\jpegtran-bin\lib\install.js:1
npm ERR! import process from 'node:process';
npm ERR! ^^^^^^
npm ERR!
npm ERR! SyntaxError: Cannot use import statement outside a module
npm ERR!     at Module._compile (internal/modules/cjs/loader.js:895:18)
npm ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
npm ERR!     at Module.load (internal/modules/cjs/loader.js:815:32)
npm ERR!     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
npm ERR!     at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
npm ERR!     at internal/main/run_main_module.js:17:11
-------------------------------------------------------------------------

**Comment by sHow8e** [comment]
@cqmking hihi。The node version needs to be greater than or equal to V14. Try to upgrade the node version.

**Comment by cqmking** [comment]
> 
Yes, it works with node v14.19.1, thx
