### ISSUE TITLE
升级 vue 3.2.16 --> 3.2.31 

### ISSUE THREAD

**Issue by mo4223** [arco-design/arco-design-pro-vue#45]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.3.2
- **System:** MAC Os
- **Browser:** chrome99.0.4844.51
- **Reproduction Link:** http://vue-pro.arco.design/dashboard/workplace

## What is expected?
修复

## Steps to reproduce
采用arco-cli 创建Vue工程，

1：升级所有版本
2：登录后，任意点击2个菜单
3：用户注销，页面路由无法正常处理，同时控制台异常

其他：
默认不升级 vue ，使用3.2.16  版本，其他依赖升级最新，无此异常

**Comment by sHow8e** [comment]
@mo4223 hihi 麻烦详细描述一下现象。我这边使用vue最新版并无异常。同时我用另一台电脑初始化工程也无异常。

**Comment by mo4223** [comment]
![image](https://user-images.githubusercontent.com/102282780/160048901-c59f8e96-185e-40df-ba26-7bfd7624e4a6.png)

**Comment by sHow8e** [comment]
@mo4223 抱歉。我这边根据步骤还是无法复现这个现象。可以加一下我们用户群反馈一下哈。3q
