### ISSUE TITLE
能不能加上openid的登录功能(oidc) ，这个功能很需要。

### ISSUE THREAD

**Issue by oaktreecode** [arco-design/arco-design-pro-vue#47]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
目前无法同openid的授权模式登录

## What problem does this feature solve?
目前无法同openid的授权模式登录

**Comment by oaktreecode** [comment]
或者能提供例子？

**Comment by sHow8e** [comment]
@oaktreecode 目前没有相关的接入规划。可以自行查看对应的文档哈。
