### ISSUE TITLE
如何关闭eslint

### ISSUE THREAD

**Issue by ikilobyte** [arco-design/arco-design-pro-vue#48]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.3.3
- **Browser:** chrome99.0.4844.84
- **Reproduction Link:** https://github.com/arco-design/arco-design-pro-vue

## What is expected?
怎么关闭这个烦人的eslint

**Comment by lt1067066026** [comment]
![image](https://user-images.githubusercontent.com/35676131/161243091-406dfc5f-d34b-40a7-a05a-d5726baa0f17.png)
