### ISSUE TITLE
在page-layout.vue组件中，定义了两个<router-view>

### ISSUE THREAD

**Issue by cqmking** [arco-design/arco-design-pro-vue#49]
## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.3.3
- **Browser:** chrome98.0.4758.102
- **Reproduction Link:** https://arco.design/issue-helper?repo=arco-design-pro-vue

## What is expected?
根据定义的路由层级，正常显示组件

## Steps to reproduce
在page-layout.vue组件中，定义了两个router-view 。导致做路由配置的时候需要配置多个层级才能显示
在 src/views/dashboard/index.vue 中也定义了一个router-view，当我需要在其中增加自定义内容，显示一些额外的信息时，发现不生效。

**Comment by sHow8e** [comment]
@cqmking 嵌套多层当时是参照了官方文档的处理。现在线上文档出现了变更。我这边需要去看一下router的文档以及更新内容再进行处理哈。3q
