### ISSUE TITLE
 将Vuex替换为Pinia作为状态管理仓库

### ISSUE THREAD

**Issue by yanbowe** [arco-design/arco-design-pro-vue#5]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
https://pinia.vuejs.org/

## What problem does this feature solve?
更好的TS支持

**Comment by blackcater** [comment]
PR #7

**Comment by sHow8e** [comment]
@blackcater 首先感谢PR。项目起初也有相关的技术选型考虑到Pinia。但是当时还有一些顾虑的因素在内。所以定下了Vuex。个人感觉这个PR很有价值。前段时间的官宣等造势以及Pinia自身的一些前瞻性特性，相信Pinia后续会有长足的发展。近期需要经过内部讨论，再进行相关后续操作。谢谢。

**Comment by yanbowe** [comment]
现在TS版的Vuex属实太难看了，而且晦涩难懂

**Comment by XM36578** [comment]
plugin:vite:eslint  为啥总是有lint错误呢

**Comment by sHow8e** [comment]
> plugin:vite:eslint 为啥总是有lint错误呢

因为eslint本身也会迭代更新，项目内也没有锁版本以及对所以的eslint规则进行处理。所以安装了新的eslint后会有一些预设的报错暴露出来。后期我们这边也做一些对应预设处理。用户可以自行选择关闭对应规则哈。
PS：无关本次issue的可以新开issue咨询。下不为例哈。

**Comment by sHow8e** [comment]
> 现在TS版的Vuex属实太难看了，而且晦涩难懂

嗯，这也是无奈之举，本身vuex的ts支持就很差，又要完备的代码书写提示，同时还得规避TS报错。所以只能自己去声明定义数据类型了。之后改成pinia就可以。可以期待一下哈。

**Comment by sHow8e** [comment]
已经升级了哈  Enjoy it~ [https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.1.0](https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.1.0)

**Comment by XM36578** [comment]
真的太好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "arco-design/arco-design-pro-vue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月18日(星期二) 晚上8:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [arco-design/arco-design-pro-vue]  将Vuex替换为Pinia作为状态管理仓库 (Issue #5)





 
已经升级了哈  Enjoy it~ https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.1.0
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
