### ISSUE TITLE
请问这个只能基于角色控制权限吗？

### ISSUE THREAD

**Issue by 2211868381** [arco-design/arco-design-pro-vue#51]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.3.3
- **Browser:** chrome100.0.4896.60
- **Reproduction Link:** http://www.baidu.com

## What is expected?
1

## Steps to reproduce
请问这个只有基于角色控制权限吗？没有权限标识的情况下，如何进行按钮级的权限控制呢？需要自己修改吗？还是说这个功能目前在开发中？

**Comment by sHow8e** [comment]
@2211868381 内置了指令directive。[使用文档](https://arco.design/vue/docs/pro/permission)

**Comment by 2211868381** [comment]
@sHow8e 好的，就是文档里面是传入的角色名，我不是很清楚怎么用的，是直接给role之类的字段，传入权限标识就可以了吗，比如 menu@edit 或者 menu@add 这种？

**Comment by sHow8e** [comment]
@2211868381 其实这个和你的业务权限设计有关。比如某个按钮，需要'admin'权限角色的人员才能看到。你就传进去v-permission="['admin']"就行。当然里面的具体逻辑根据需要自行处理。

**Comment by 2211868381** [comment]
@sHow8e 好的，谢谢大佬
