### ISSUE TITLE
用CLI构建的"完整版本"无法正常运行

### ISSUE THREAD

**Issue by 0xSa9** [arco-design/arco-design-pro-vue#52]
## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.3.3
- **浏览器版本:** chrome100.0.4896.60
- 最新的Arco CLI工具, NPM 2.6x

## npm run dev后出现如下错误信息
The following dependencies are imported but could not be resolved:

  @arco-design/web-vue/es/upload/interfaces (imported by D:/Project/vue/pro_sample/src/views/user/setting/components/user-panel.vue?id=0)

Are they installed?

额外补充:
CLI选项里面选择"单个页面"后构建的项目就可以正常运行.

"完整版本"不行,希望可以解决问题.

**Comment by sHow8e** [comment]
这个提示应该是项目已经初始化成功了？感觉是包没下好或者没被resolve，可以删掉node_modules重新install一下试试哈。

**Comment by woxiren** [comment]
我也遇到同样的问题
node版本14.16.1，12.22.9都试了
都报这个错，把项目全部删除，重新生成，问题依旧。

**Comment by sHow8e** [comment]
@gengzhao2020 安装依赖已经是最后的步骤了。如果没成功。先删除node_modules文件夹。换一下npm源，或者使用yarn（推荐）再进行一次安装。

**Comment by gengzhao2020** [comment]
> @gengzhao2020 安装依赖已经是最后的步骤了。如果没成功。先删除node_modules文件夹。换一下npm源，或者使用yarn（推荐）再进行一次安装。

用yarn成功了，但是仍然会提示 错误，不过不影响使用

D:\source>arco init arco-design-pro-vue

        ___                    ____            _
       /   |  ______________  / __ \___  _____(_)___ _____
      / /| | / ___/ ___/ __ \/ / / / _ \/ ___/ / __ `/ __ \
     / ___ |/ /  / /__/ /_/ / /_/ /  __(__  ) / /_/ / / / /
    /_/  |_/_/   \___/\____/_____/\___/____/_/\__, /_/ /_/
                                             /____/

                                                v1.26.1

? 请选择使用的 Arco 物料平台版本 公共版本（使用 GitHub 账户授权登录）
已成功切换至公共环境
? 请选择你希望使用的技术栈 Vue
? 请选择所要创建项目的类型 Arco Pro 项目
? 请选择 Arco Pro 模板 完整版（包含所有页面）

正在初始化项目于 D:\source\arco-design-pro-vue
✔ 获取项目模板成功
✔ 模板内容拷贝完成
✔ 模板内容适配完成
✖ 项目依赖安失败，你可以稍后尝试手动安装项目依赖
Command Error: npm install
******************************************************************************
  Read README.md for help information. Execute following command to start
    $ cd arco-design-pro-vue
    $ yarn dev
******************************************************************************

**Comment by abluepoint001** [comment]
src/views/user/setting/components/user-panel.vue

  import {
    FileItem,
    RequestOption,
  } from '@arco-design/web-vue/es/upload/interfaces**.d**';

**Comment by dyggod** [comment]
> 

这是对的，考虑修复这个问题吗？
