### ISSUE TITLE
关闭暗夜模式

### ISSUE THREAD

**Issue by gitzh2017** [arco-design/arco-design-pro-vue#53]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
修改导航颜色，或者主题颜色

## What problem does this feature solve?
这个是不是有自动切换主题模式的功能，如果只用Light，如何永久关闭Dark，或者我自定义了颜色从哪里添加css样式哈

**Comment by sHow8e** [comment]
@gitzh2017 暗黑模式是内置的 这个无关紧要。你只要把对应的触发代码去掉就行。如果想要自定义颜色。1、重写css变量。2、直接颜色覆盖。推荐主题切换-[风格配置平台](https://arco.design/themes?currentPage=1&onlyPublished=false&pageSize=9&sortBy=starCount&tag=all)
