### ISSUE TITLE
增加全屏按钮

### ISSUE THREAD

**Issue by snowinszu** [arco-design/arco-design-pro-vue#54]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
vue-element-admin

## What problem does this feature solve?
增加全屏按钮，可以让页面在显示器全屏展示

**Comment by sHow8e** [comment]
[done](https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.5.0)
