### ISSUE TITLE
线上演示地址不能正常浏览

### ISSUE THREAD

**Issue by lun324** [arco-design/arco-design-pro-vue#57]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.3.4
- **Browser:** chrome98.0.4758.80
- **Reproduction Link:** https://vue-pro.arco.design/

## What is expected?
线上演示地址不能正常浏览

**Comment by sHow8e** [comment]
@lun324 我这边多部设备不同网络都能正常访问。看看是不是网络串了或者别的缘故哈。
