### ISSUE TITLE
增加权限管理

### ISSUE THREAD

**Issue by cxiniao** [arco-design/arco-design-pro-vue#6]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
https://pro.ant.design/zh-CN/docs/authority-management

## What problem does this feature solve?
通过权限管理解决不同用户的权限不同问题

**Comment by sHow8e** [comment]
关于菜单、路由、管理权限相关的内容。后续会筛选进行补足哈。进行期待。

**Comment by cxiniao** [comment]
隔壁pro-react更新了，咱pro-vue能尽快推进吗？想用上项目了。T.T

**Comment by sHow8e** [comment]
@cxiniao 额。因为两边要升级修改的内容不完全一致。近期就会加入这个功能，后续再告知哈。

**Comment by sHow8e** [comment]
@cxiniao 权限管理推出啦 [https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.2.0](https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.2.0)

**Comment by cxiniao** [comment]
@sHow8e 好滴，3q~
