### ISSUE TITLE
执行vue-tsc - noEmit时非常的慢

### ISSUE THREAD

**Issue by zoonware** [arco-design/arco-design-pro-vue#61]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.3.4
- **System:** win11
- **Browser:** chrome96.0.4664.45
- **Reproduction Link:** https://github.com/arco-design/arco-design-pro-vue/blob/main/arco-design-pro-vite/tsconfig.json

## What is expected?
如何解决

## Steps to reproduce
yarn build 或者 npm run build 卡住不动
最新一次执行vue-tsc - noEmit时花费 36226.08s
用tsc执行没有问题

**Comment by sHow8e** [comment]
@zoonware 纯pro的内容，简易版本约30s出包。普通版本约45s出包。受机子性能影响，可以尝试执行report看看是包的问题或者又是自身代码造成？又或者重新安装依赖。

**Comment by chenbj2333** [comment]
@zoonware @sHow8e  我是纯pro的普通版本，然后也是yarn build的时候卡住不动，重装依赖也不行，有解决方案了嘛？

**Comment by sHow8e** [comment]
@chenbj2333 先自己排查一下。把build 命令的 vue-tsc - noEmit 代码检查去掉看看。同时可以把打包插件先注释。排除依赖包的干扰。

**Comment by chenbj2333** [comment]
@sHow8e 的确是vue-tsc卡住了，去掉以后打包是很快的。
