### ISSUE TITLE
如何设置一级菜单路由

### ISSUE THREAD

**Issue by ssqf** [arco-design/arco-design-pro-vue#62]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.3.4
- **System:** win10
- **Browser:** chrome100.0.4896.127
- **Reproduction Link:** https://github.com/arco-design/arco-design-pro-vue/blob/main/arco-design-pro-vite/tsconfig.json

## What is expected?
无法设置一级菜单路由

## Steps to reproduce
没有配置子菜单，还是显示折叠
也没找到设置一级菜单路由的说明

**Comment by Icecream-zou** [comment]
<img width="733" alt="image" src="https://user-images.githubusercontent.com/48505447/164491681-fa7b0cc3-e24e-48d3-8147-570d385e8616.png">

加一个判断 只有一个children的时候 返回一个menu 目录文件位于 components/menu/index.vue

<img width="800" alt="image" src="https://user-images.githubusercontent.com/48505447/164491969-74d71dcf-cfa2-4a2f-bce9-d0862133a335.png">

**Comment by hehehai** [comment]
@ssqf 你好

这个功能将在近期更新，可以先参考 #59 的代码改动

**Comment by sHow8e** [comment]
@ssqf  [V2.3.6](https://github.com/arco-design/arco-design-pro-vue/blob/main/docs/changelog.zh-CN.md) 已更新
