### ISSUE TITLE
a-table summary 为 true的时候 表格不显示 统计行

### ISSUE THREAD

**Issue by Icecream-zou** [arco-design/arco-design-pro-vue#63]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.3.4
- **Browser:** chrome99.0.4844.51
- **Reproduction Link:** https://github.com/arco-design/arco-design-pro-vue/

## What is expected?
summary 为 true的时候 表格显示 统计行

## Steps to reproduce
从arco init project
修改 /src/views/list/srarch-table/index.vue 134 新增 :summary="true"
yarn dev
页面不显示统计行

<img width="440" alt="image" src="https://user-images.githubusercontent.com/48505447/164487422-14104a29-79d6-439a-946f-3ca5a8f92106.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48505447/164487112-dbe835c5-01d3-4261-bf20-dfd883f1cfb4.png">

**Comment by sHow8e** [comment]
@Icecream-zou 首先查看安装的组件库版本是否是V2.21.0及以上。确认代码书写正确，再者看看样式是否溢出隐藏。如果依旧功能失效可以加入飞书用户群提问或者提个[issue](https://github.com/arco-design/arco-design-vue/issues)。3q
