### ISSUE TITLE
Please update to the latest version of the arco design/请同步最新版本的arco design

### ISSUE THREAD

**Issue by arect** [arco-design/arco-design-pro-vue#65]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 现有案例
for example: Dialog full screen.
例如：对话框全屏。

## 预期解决问题
There are many new features that require the new version of arco design, which hopefully will be updated in time.
有许多新特性需要新版本的arco design，希望能及时更新。

**Comment by sHow8e** [comment]
@arect 今天会发版更新一下。如果想体验使用新版可以自行安装哈。
