### ISSUE TITLE
能否完善示例中查询表格的增删改查功能

### ISSUE THREAD

**Issue by sanshengs** [arco-design/arco-design-pro-vue#67]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
完善示例中查询表格的增删改查功能
## What are the similar cases of this feature
无

## What problem does this feature solve?
用户更容易上手使用表格的相关功能

## Extra info
当前示例中,新增,下载等功能没有代码示例

**Comment by sHow8e** [comment]
@sanshengs 抱歉目前并没有相关规划。不过关于组件的功能使用、问题反馈可以加入我们飞书用户群一起交流学习哈。3q
