### ISSUE TITLE
keep-alive feature doesn't work in multi-tag mode.

### ISSUE THREAD

**Issue by bitichengshi** [arco-design/arco-design-pro-vue#68]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.3.6
- **Browser:** chrome100.0.4896.127
- **Reproduction Link:** http://vue-pro.arco.design/dashboard/workplace

## What is expected?
just fix it.

**Comment by bitichengshi** [comment]
And the dashboard page is not in this cached tab list by default.

**Comment by sHow8e** [comment]
> And the dashboard page is not in this cached tab list by default.

The first default item for tab is Workplace

**Comment by sHow8e** [comment]
@bitichengshi Caching does not work, you can refer to the code in [v2.3.4](https://github.com/arco-design/arco-design-pro-vue/blob/v2.3.4/arco-design-pro-vite/src/layout/page-layout.vue) (src/layout/page-layout.vue). The whole will be fixed in the future. 3q
