### ISSUE TITLE
能不能加个跨域的例子

### ISSUE THREAD

**Issue by 981433814** [arco-design/arco-design-pro-vue#70]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
无

## What problem does this feature solve?
加个跨域的配置

**Comment by sanshengs** [comment]
修改项目目录config/vite.config.dev.ts中server配置
```
server: {
    open: true,
    fs: {
      strict: true,
    },
    // 增加反向代理，跨域
    proxy: {
      '/api': {
        target: 'http://127.0.0.1:8990/',
        changeOrigin: true, // 允许跨域
        rewrite: (path) => path.replace(/^\/api/, ''),
      },
    },
  },
```

**Comment by 981433814** [comment]
> 修改项目目录config/vite.config.dev.ts中服务器配置
> 
> ```
> server: {
>     open: true,
>     fs: {
>       strict: true,
>     },
>     // 增加反向代理，跨域
>     proxy: {
>       '/api': {
>         target: 'http://127.0.0.1:8990/',
>         changeOrigin: true, // 允许跨域
>         rewrite: (path) => path.replace(/^\/api/, ''),
>       },
>     },
>   },
> ```

加了跨域这个配置，还是没有生效

**Comment by 981433814** [comment]
![image](https://user-images.githubusercontent.com/45874392/166184908-06d96cc2-9375-46fc-819b-eea16d6b772f.png)
在axios 切面这里加个前缀会好一点

**Comment by sanshengs** [comment]
@981433814 是的,要处理一下VITE_API_BASE_URL,可以直接把.env.development中VITE_API_BASE_URL注释掉

**Comment by sHow8e** [comment]
@981433814 如果是开发环境三件事要处理。1、关闭对应的mock接口。2、拦截器的baseUrl根据自己的环境处理一下。3、添加vite的proxy。

**Comment by zzzloving** [comment]
> @981433814 如果是开发环境三件事要处理。1、关闭对应的mock接口。2、拦截器的baseUrl根据自己的环境处理一下。3、添加vite的proxy。

你好，我新增一个页面内容，然后我想保留其他的mock借口，新页面的在哪关系mock接口呢？
<img width="1754" alt="image" src="https://user-images.githubusercontent.com/31347659/223097664-31bab3b1-8ace-4761-9f1d-23310ac5f26b.png">
