### ISSUE TITLE
开发时候样式正常，打包后样式顺序有误或样式文件多了一份

### ISSUE THREAD

**Issue by Sanbolee** [arco-design/arco-design-pro-vue#72]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.3.6
- **框架版本:** vue ^3.2.31
- **浏览器版本:** chrome100.0.4896.127
- **复现地址:** https://github.com/

## 预期结果
全局样式应覆盖框架样式

## 复现步骤
新建一个pro项目，直接打包即可

### 全局样式文件global.less
<img width="458" alt="截屏2022-05-08 16 35 43" src="https://user-images.githubusercontent.com/18314958/167289555-d65d8376-b342-4428-899d-169b86f00b8c.png">

### main.ts样式导入顺序
<img width="582" alt="截屏2022-05-08 17 12 59" src="https://user-images.githubusercontent.com/18314958/167289600-bd300ec8-7084-4c7a-afe8-342d03cc2dce.png">

### 打包后样式被覆盖，似乎多出了一份样式
<img width="520" alt="截屏2022-05-08 17 18 18" src="https://user-images.githubusercontent.com/18314958/167289773-fd16578d-4228-4298-9ce9-37e706dd5924.png">

**Comment by sHow8e** [comment]
@Sanbolee hi 看了一下。发现这个问题和 [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components) 这个按需加载插件有关。你可以去它下面提一下issue。如果影响到打包。可以在打包配置里把相关插件注释禁用即可。
