### ISSUE TITLE
打包构建完成后，本地使用live-server启动时，刷新后页面404

### ISSUE THREAD

**Issue by Paradox315** [arco-design/arco-design-pro-vue#73]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.3.6
- **Browser:** chrome101.0.4951.54
- **Reproduction Link:** https://github.com/

## What is expected?
在浏览器刷新页面，不出现404

## Steps to reproduce
1、使用arco-cli创建一个arco项目
2、运行npm run build打包
3、cd dist && live-server ./ --port=$port
4、登录后进入dashboard页面，刷新浏览器
![image](https://user-images.githubusercontent.com/56352258/167297029-c368d026-519a-48e5-b503-c4bc01634089.png)

**Comment by sHow8e** [comment]
@Paradox315 这个不是pro的问题哈。看一下live-server的文档。需要配置重定向到index.html。
