### ISSUE TITLE
主题切换按钮打包编译报错

### ISSUE THREAD

**Issue by johnzhuo9527** [arco-design/arco-design-pro-vue#80]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.4.1
- **浏览器版本:** chrome101.0.4951.54

## 复现步骤
arco-design-pro-vue/arco-design-pro-vite/src/components/navbar/index.vue
主题切换按钮
<a-button class="nav-btn" type="outline" :shape="'circle'" @click="toggleTheme">
打包编译报错
不能将类型“(value?: boolean | undefined) => boolean”分配给类型“(EmitType<(ev: MouseEvent) => void> & ((...args: any[]) => any)) | undefined”。
不能将类型“(value?: boolean | undefined) => boolean”分配给类型“((ev: MouseEvent) => void) & ((...args: any[]) => any)”。ts(2322)
  const isDark = useDark({
    selector: 'body',
    attribute: 'arco-theme',
    valueDark: 'dark',
    valueLight: 'light',
    storageKey: 'arco-theme',
    onChanged(dark: boolean) {
      appStore.toggleTheme(dark);
    },
  });
  const toggleTheme = useToggle(isDark);
如果改成 const toggleTheme = （）=> useToggle(isDark);
打包编译可以通过，但是按钮就失去了切换主题的功能

**Comment by sHow8e** [comment]
@johnzhuo9527 这个是ts类型检测的问题。项目内把相关的类型指定正确就行。后续我发版修复一下。3q

**Comment by sHow8e** [comment]
[done](https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.5.0)
