### ISSUE TITLE
能否提供一个外链的路由示例

### ISSUE THREAD

**Issue by logben** [arco-design/arco-design-pro-vue#82]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
如题

## What problem does this feature solve?
如题

**Comment by sHow8e** [comment]
@logben 这个功能暂时不支持诶。后续版本给加一下。可以自行在菜单组件的goto里做一下判断进行页面跳转哈。3q

**Comment by logben** [comment]
收到，自己简单实现了下，感觉不如大佬们的丝滑！
