### ISSUE TITLE
切换角色报错

### ISSUE THREAD

**Issue by yanbowe** [arco-design/arco-design-pro-vue#84]
- [x] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.0
- **Framework version:** vue 3.2.31
- **Browser:** chrome101.0.4951.64
- **Reproduction Link:** https://vue-pro.arco.design/login

## What is expected?
正常切换

## Steps to reproduce
进入预览 登陆后点击头像下拉中的切换角色报错，左侧菜单栏空白
<img width="1665" alt="image" src="https://user-images.githubusercontent.com/43030980/169199732-64694301-9d75-4b3a-9be2-a9b1c7e0991d.png">

**Comment by sHow8e** [comment]
done

**Comment by yanbowe** [comment]
> done
谢谢
