### ISSUE TITLE
如果我想创建一个一级菜单，没有子集的菜单怎么创建？

### ISSUE THREAD

**Issue by sqlFC** [arco-design/arco-design-pro-vue#85]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What are the similar cases of this feature
如果我想创建一个一级菜单，没有子集的菜单怎么创建？

## What problem does this feature solve?
如果我想创建一个一级菜单，没有子集的菜单怎么创建？

![image](https://user-images.githubusercontent.com/29202691/169237472-219cab38-5278-488c-a788-b3d0ee16993c.png)

**Comment by sqlFC** [comment]
![image](https://user-images.githubusercontent.com/29202691/169239283-db730d20-4c90-442c-b696-cfa1953cb522.png)

如上图创建后，页面不显示

**Comment by sHow8e** [comment]
@sqlFC 加一个标识，hideChildrenInMenu： true

**Comment by sqlFC** [comment]
@sHow8e 十分感谢大佬指导，我这就去试试

**Comment by deluxebear** [comment]
感觉还是有点问题： component 不能复用 DEFAULT_LAYOUT

**Comment by sHow8e** [comment]
@deluxebear 具体描述一下？

**Comment by deluxebear** [comment]
> @deluxebear 具体描述一下？
![acro1](https://user-images.githubusercontent.com/485793/169922794-08b99fe5-2ff4-468c-97b5-bb452bbc2870.png)
![arco2](https://user-images.githubusercontent.com/485793/169922798-50825e5b-8de0-4684-bdf5-35f9915d4a55.png)
一级菜单的页面不好注入到 DEFAULT_LAYOUT

**Comment by sHow8e** [comment]
@deluxebear default_layout是必须的。你可以看一下default-layout的代码以及其它的路由配置。default-layout里面是一个基本布局加上一个router-view。

**Comment by deluxebear** [comment]
我可能没有表述清楚，对于二级菜单没有问题：
![image](https://user-images.githubusercontent.com/485793/170166040-0573023d-871e-4bba-9939-217ddf555e1c.png)
一级菜单存在的问题：
![image](https://user-images.githubusercontent.com/485793/170166282-85dd7bc9-7f9a-457b-8db3-36ced6692df2.png)

**Comment by sHow8e** [comment]
@deluxebear ok。我get到了。你这边可以开一个新的issue。在那边进行讨论。

**Comment by sHow8e** [comment]
@sqlFC  如下图示例代码，类似于套一层重定向即可。
<img width="656" alt="image" src="https://user-images.githubusercontent.com/15161021/171211511-27d5522a-a367-40c9-80e1-a785ffa0da61.png">

**Comment by WangNingkai** [comment]
> @sqlFC 如下图示例代码，类似于套一层重定向即可。 <img alt="image" width="656" src="https://user-images.githubusercontent.com/15161021/171211511-27d5522a-a367-40c9-80e1-a785ffa0da61.png">

这样好像菜单不会高亮

**Comment by sHow8e** [comment]
@WangNingkai activeMenu要配成你项目对应的菜单项。上面那张图是示例代码哈。

**Comment by kmfe** [comment]
@sHow8e  确实这样配置路由是可以的，但是菜单没法高亮，这怎么处理啊

**Comment by mablevi** [comment]
> @sqlFC 如下图示例代码，类似于套一层重定向即可。 <img alt="image" width="656" src="https://user-images.githubusercontent.com/15161021/171211511-27d5522a-a367-40c9-80e1-a785ffa0da61.png">

redirect: '/app/test' 应该是这样吧？（手动狗头）

**Comment by mablevi** [comment]
> @sqlFC 如下图示例代码，类似于套一层重定向即可。 <img alt="image" width="656" src="https://user-images.githubusercontent.com/15161021/171211511-27d5522a-a367-40c9-80e1-a785ffa0da61.png">

这里 redirect: '/app/test' (path) 或者 redirect: 'test' (name)  应该是这样。 直接写 /test 应该是找不到路径吧？

**Comment by zdianjiang** [comment]
@sHow8e 按照图片配置会发现问题就是params无法通过redirect实现，我看vue-router是可以实现的。

```typescript
const DASHBOARD: AppRouteRecordRaw = {
  path: '/app/:user',
  name: 'app',
  component: DEFAULT_LAYOUT,
 redirect: '/test',
  meta: {
    locale: 'menu.dashboard',
    requiresAuth: true,
    icon: 'icon-dashboard',
    order: 0,
    hideChildrenInMenu: true,
  },
  children: [
    {
      path: 'test',
      name: 'test',
      component: () => import('@/views/dashboard/workplace/index.vue'),
      meta: {
        locale: 'menu.dashboard.workplace',
        requiresAuth: true,
        roles: ['*'],
        activeMenu: 'app',
      },
    },
  ],
};
```

以上配置将会被redirect到'/test'路径，而不是'/app/:user/test'.
如果将redirect修改成`/app/:user/test'，重定向地址就是`/app/:user/test'，而不是`/app/username/test'.

> @sqlFC 如下图示例代码，类似于套一层重定向即可。 <img alt="image" width="656" src="https://user-images.githubusercontent.com/15161021/171211511-27d5522a-a367-40c9-80e1-a785ffa0da61.png">

**Comment by foreversmart** [comment]
@sHow8e 建议把这个加到文档里，一路看 issue 看下来有很多人遇到这个问题了

**Comment by moshanghan** [comment]
`
const DASHBOARD: AppRouteRecordRaw = {
  path: '/app',
  name: 'app',
  component: DEFAULT_LAYOUT,
 redirect: '/test',
  meta: {
    locale: 'menu.dashboard',
    requiresAuth: true,
    icon: 'icon-dashboard',
    order: 0,
    hideChildrenInMenu: true,
  },
  children: [
    {
      path: '/test',
      name: 'test',
      component: () => import('@/views/dashboard/workplace/index.vue'),
      meta: {
        locale: 'menu.dashboard.workplace',
        requiresAuth: true,
        roles: ['*'],
        activeMenu: 'app',
      },
    },
  ],
};
`
稍微调整一下，可用

**Comment by zxuanhong** [comment]
@moshanghan @sHow8e 你确定你给的会高亮？？这个不能吧，而且我看了菜单实现，点击菜单获取的是父级信息，而具体重定向却是router完成的，也就是菜单那个地方根本拿不到子类配置的activeMenu，除非你再菜单设置高亮时去找下重定向的菜单，然后获取activeMenu,具体菜单设置高亮代码实现如下
<img width="1060" alt="image" src="https://github.com/arco-design/arco-design-pro-vue/assets/62740686/531dc60e-0394-4d7a-8c9c-d370bbe61842">
