### ISSUE TITLE
没出一个精简版的吗？

### ISSUE THREAD

**Issue by y1324** [arco-design/arco-design-pro-vue#9]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 现有案例
ant、element 都有对应的pro精简版

## 预期解决问题
master带的东西太多了，直接出一个精简版，不用删这么多东西。

**Comment by y1324** [comment]
比如花裤衩的那个

**Comment by sHow8e** [comment]
这个精简版可能需要后续规划了。还是感谢建议吧。后续推出再进行通知哈。3q
