### ISSUE TITLE
权限路由判断

### ISSUE THREAD

**Issue by strongyc** [arco-design/arco-design-pro-vue#90]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## What problem does this feature solve?
在源码中点击菜单栏进行跳转
  const goto = (item: RouteRecordRaw) => {
        router.push({
          name: item.name,
        });
      };
export default function setupServerPermissionGuard(router: Router) {
  router.beforeEach(async (to, from, next) => {
    // A simple example 简单示例

    // 针对来自服务端的菜单配置进行处理
    // Handle routing configuration from the server

    // 根据需要自行完善来源于服务端的菜单配置的permission逻辑
    // Refine the permission logic from the server's menu configuration as needed
    const appStore = useAppStore();
    if (appStore.menuFromServer) {
      const serverMenuConfig = [...appStore.appServerMenuConfig, ...whiteList];
      let exist = false;
      while (serverMenuConfig.length) {
        const element = serverMenuConfig.shift();
        if (element?.name === to.name) exist = true;

        if (element?.children) {
          serverMenuConfig.push(
            ...(element.children as unknown as RouteRecordNormalized[])
          );
        }
      }
      if (exist) next();
      else next({ name: 'notFound' });
    } else {
      next();
    }
  });
}
## What are the similar cases of this feature
该种方式通过name进行跳转，但实际开发中，路径是会带参数传递，带参数传递传递的路径该如何进行权限判断，是否能在Pro
中给一个案例，比如个人中心详情

**Comment by sHow8e** [comment]
@strongyc hihi 解决方法可以看一下这边哈。[#71](https://github.com/arco-design/arco-design-pro-vue/issues/71)

**Comment by sHow8e** [comment]
@strongyc hihi 你提的这些是vue-router的使用问题。路由守卫函数的to参数里面有query信息。[router相关文档](https://router.vuejs.org/zh/guide/essentials/navigation.html#%E5%AF%BC%E8%88%AA%E5%88%B0%E4%B8%8D%E5%90%8C%E7%9A%84%E4%BD%8D%E7%BD%AE)

**Comment by strongyc** [comment]
收到，感谢
