### ISSUE TITLE
一级菜单外链问题

### ISSUE THREAD

**Issue by deluxebear** [arco-design/arco-design-pro-vue#92]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## 基本信息 
- **依赖包名 及 版本:** arco-design-pro-vue@2.5.1
- **框架版本:** VUE
- **浏览器版本:** chrome101.0.4951.67

## 预期结果
但是页面加载不出来，发现报错了

## 复现步骤
在路由文件夹里面增加了一个外链的一级路由
![38lvlj2CFr](https://user-images.githubusercontent.com/485793/170171434-e8413c1b-2b3f-4fca-926b-19d9b4273d3a.jpg)
运行报以下错误：
![1lq9vm4kvo](https://user-images.githubusercontent.com/485793/170171499-b3c0fdcf-9f41-41e2-8c13-89efbe92413b.png)

**Comment by sHow8e** [comment]
done [v2.5.2](https://github.com/arco-design/arco-design-pro-vue/releases/tag/v2.5.2)
