### ISSUE TITLE
项目引入某些组件 导致rollup打包失败，需要手动加入忽略文件

### ISSUE THREAD

**Issue by zoomc** [arco-design/arco-design-pro-vue#95]
rollup不到这个a-image-preview 的css.js文件。我看确实没有这个对应的文件，注掉configStyleImportPlugin()就好了

**Comment by sHow8e** [comment]
@zoomc 感谢提醒哈。已加上！因为组件库这边也不断的新增功能和组件。这些问题会根据实际情况进行调整。3q
