### ISSUE TITLE
webpack版本菜单icon不显示

### ISSUE THREAD

**Issue by Booshaw** [arco-design/arco-design-pro-vue#99]
- [ ] I'm sure this does not appear in [the issue list of the repository](https://github.com/arco-design/arco-design-pro-vue/issues)

## Basic Info 
- **Package Name And Version:** arco-design-pro-vue@2.5.1
- **Browser:** chrome101.0.4951.64

## Extra info
使用了vue-cli5 对照搭建, 菜单icon为空;

  const renderSubMenu = () => {
        function travel(_route: RouteRecordRaw[], nodes = []) {
          if (_route) {
            _route.forEach((element) => {
              // This is demo, modify nodes as needed
              const icon = element?.meta?.icon
                ? () => h(compile(`<${element?.meta?.icon}/>`))
                : null;
              const node =
                element?.children && element?.children.length !== 0 ? (
                  <a-sub-menu
                    key={element?.name}
                    v-slots={{
                      icon,
                      title: () =>
                        h(compile(t(element?.meta?.locale || 'xxx'))),
                    }}
                  >
                    {travel(element?.children)}
                  </a-sub-menu>
                ) : (
                  <a-menu-item
                    key={element?.name}
                    v-slots={{ icon }}
                    onClick={() => goto(element)}
                  >
                    {t(element?.meta?.locale || '')}
                  </a-menu-item>
                );
              nodes.push(node as never);
            });
          }
          return nodes;
        }
        return travel(menuTree.value);
      };

**Comment by sHow8e** [comment]
@Booshaw 因为使用到了h和compile，需要引入编译版本的vue。你看看是不是遗漏了这部分配置。
